rubyforgood/casa

Gemfile, Gemfile.lock, README.md, config/skylight.yml
Resolves #001 
* Breaking change (fix or feature that would cause existing functionality to not 
work as expected)
* Documentation update
=> Setup stuff

app/controllers/dashboard_controller.rb, app/policies/casa_case_policy.rb, app/policies/dashboard_policy.rb, app/policies/user_policy.rb, app/views/dashboard/show.html.erb, config/routes.rb, spec/factories/user.rb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/policies/casa_case_policy_spec.rb, spec/policies/dashboard_policy_spec.rb, spec/policies/user_policy_spec.rb, spec/requests/dashboard_spec.rb, spec/spec_helper.rb
This is a small proof of concept of how to distinguish between admins
and volunteers by role. It needs tests.
=> Policies minimally working

app/assets/stylesheets/dashboard.scss, app/models/casa_case.rb, app/policies/casa_case_policy.rb, app/views/dashboard/show.html.erb, spec/features/admin_adds_new_case_spec.rb, spec/models/casa_case_spec.rb, spec/policies/casa_case_policy_spec.rb
Resolves #033 
- feature test for creating a case
- model test for the ordered scope
=> feat: admin cases dashboard

app/models/casa_case.rb, app/models/case_assignment.rb, app/models/user.rb, db/migrate/20200405112910_remove_volunteer_id_from_casa_case.rb, db/schema.rb, spec/factories/casa_case.rb, spec/factories/case_assignment.rb, spec/factories/user.rb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/models/casa_case_spec.rb, spec/models/user_spec.rb, spec/requests/case_contacts_spec.rb
Fixes #53
@h-m-m Here's my stab at the issue we discussed last night about the relationship between CasaCases and Volunteers. Tests are broken so I know something is wrong with my implementation. Do you mind taking a look and seeing if you can figure it out? I'm also happy to pair on it, if you want!
=> Fix Case/Volunteer relationship in db

README.md
=> Update readme formatting, test heroku master auto-deploy

app/assets/stylesheets/dashboard.scss, app/controllers/volunteers_controller.rb, app/views/dashboard/show.html.erb, app/views/volunteers/_form.html.erb, app/views/volunteers/edit.html.erb, app/views/volunteers/new.html.erb, config/routes.rb, db/seeds.rb, spec/features/admin_views_dashboard_spec.rb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/requests/volunteers_spec.rb
Resolves #32
Creating table view for admins to view volunteers and their respective case numbers by newest volunteer first. Also creates buttons and pages to add new volunteer and edit existing volunteers (functionality not added; should probably be new ticket).
Also modifies the seed file to reflect new model.
To review, start with `app\views\dashboard\show.html.erb`, which contains the bulk of the changes.
Authored by Lee Sharma, Amy Detwiler, and Johncarlo Cerna
=> Admin view volunteers #32

app/models/casa_case.rb, spec/models/casa_case_spec.rb
Resolves #001 
* Breaking change (fix or feature that would cause existing functionality to not 
work as expected)
* Documentation update
=> fix: error message duplicate case

Gemfile, Gemfile.lock, app/assets/stylesheets/dashboard.scss, app/controllers/dashboard_controller.rb, app/models/casa_case.rb, app/models/case_contact.rb, app/policies/case_contact_policy.rb, app/views/dashboard/show.html.erb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/models/casa_case_spec.rb, spec/policies/case_contact_policy_spec.rb
Got through first checkbox of two for #27 
Need some clarification on case contacts? Or just keep it isolated.
Resolves #001 
* Breaking change (fix or feature that would cause existing functionality to not 
work as expected)
* Documentation update
=> Volunteer view case contacts 27

app/views/dashboard/show.html.erb
Co-authored-by: lisale0 <lileung0@gmail.com>
Co-authored-by: tundal45 <tundal45@gmail.com>
Resolves #070 
=> chore: add email to volunteer view

app/views/casa_cases/_casa_case.json.jbuilder, app/views/casa_cases/index.json.jbuilder, app/views/casa_cases/show.json.jbuilder, app/views/casa_orgs/_casa_org.json.jbuilder, app/views/casa_orgs/index.json.jbuilder, app/views/casa_orgs/show.json.jbuilder, app/views/case_assignments/_case_assignment.json.jbuilder, app/views/case_assignments/index.json.jbuilder, app/views/case_assignments/show.json.jbuilder, app/views/case_contacts/_case_contact.json.jbuilder, app/views/case_contacts/index.json.jbuilder, app/views/case_contacts/show.json.jbuilder, app/views/supervisor_volunteers/_supervisor_volunteer.json.jbuilder, app/views/supervisor_volunteers/index.json.jbuilder, app/views/supervisor_volunteers/show.json.jbuilder
=> chore: remove *.json.jbuilder files

app/controllers/volunteers_controller.rb, app/views/volunteers/_form.html.erb, config/routes.rb, spec/requests/volunteers_spec.rb
This PR covers all but last item in #44 
We made the assumption that the `casa_org_id` for the Volunteer is the same as the Admin's
Tested creating volunteer in both RSpec and in the browser
=> Allows admins to create users

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Resolves #001 
* Breaking change (fix or feature that would cause existing functionality to not 
work as expected)
* Documentation update
=> Formatting fixes

.travis.yml, README.md, app/models/case_contact.rb
I think we should update the PR template to be more friendly
=> Try to make the travis build pass with less stuff?

CONTRIBUTING.md, README.md
Resolves #147 
The changes clarify the Setup instructions in the README file:
1. Moved the `yarn` command to preceed the `webpacker:compile` command.
2. Remove the `db:create` command since this step is carried out the the proceeding `db:setup`. 
Also, linked the Setup instruction in CONTRIBUTING
=> Resolves #147. Clarified setup instruction and Contributors file.

Gemfile, Gemfile.lock, README.md, config/initializers/bugsnag.rb
Add bugsnag for tracking errors- they will be posted to slack #casa-bots for now
=> Add bugsnag

app/models/user.rb, app/views/dashboard/_admin_dashboard.html.erb, config/initializers/bugsnag.rb, spec/spec_helper.rb
Resolves #117
Uses paper_trail gem and jquery datatables to give admins the ability to search users by current and past names.
No Impact.
Local testing and existing rspec tests pass
=> Adds search functionality for past names of users

app/models/supervisor_volunteer.rb, app/models/user.rb, app/models/volunteer.rb, db/seeds.rb
Starts #167 
The issue is in progress, but this is a complete chunk of work
Added and updated the database seeds for more realistic demo-ing and to check our system's handling of strings.
will not
no
=> Improve automated seed data 167

app/controllers/case_contacts_controller.rb, config/initializers/bugsnag.rb
Resolves #173
To prevent 404 errors from showing up on Slack, this commit adds the ResourceNotFound class to Bugsnag's ignored classes.
No Impact.
Local Testing.
=> Adds RecordNotFound to bugsnag ignored errors

app/assets/stylesheets/navbar.scss, app/views/layouts/application.html.erb
Resolves #166 
Added Bootstrap classes for [alerts]() in the `application.html.erb` file. This changes will affect all flash messages globally. 
No changes
All existing test work properly.
=> Edit flash message style to include all messages

Gemfile, Gemfile.lock, db/seeds.rb
Continues #167 
Instead of creating just a few users, casa cases and case assignments for the database seed, these changes allow us to create many.  This PR focuses on quantity rather than on careful attention to the kinds of users and associations needed. 
- used the Faker gem for names
- used Faker gem for case numbers--easily adjustable *assumed 6 digits for case numbers*
- creates designated number of volunteers, supervisors and casa cases
Current settings in seeds.rb -- adjust then `rake db:reset` to generate a different number
```
VOLUNTEER_USER_COUNT = 100
CASA_CASE_COUNT = 150
SUPERVISOR_COUNT = 5
```
- *assumes a volunteer will have multiple cases* -- however this may be wrong way round, with cases having multiple volunteers, or both?
- *assumes its good to have a third of cases …
=> Add faker and seed data

Gemfile, Gemfile.lock, app/models/case_contact.rb, lib/tasks/auto_generate_diagram.rake, spec/models/case_contact_spec.rb
Resolves #160
* [ x] I have performed a self-review of my own code
* [x ] I added tests that prove my fix is effective or that my feature works
Added validation for occurred at not being allowed to be in the future. Added tests for added validations. Removed rake task for generating db diagram. 
No change
rspec
👍💪🤺
=> Validates occurred at not in future.

Gemfile, Gemfile.lock, app/mailers/volunteer_mailer.rb, app/views/volunteer_mailer/deactivation.html.erb, config/environments/production.rb, config/initializers/devise.rb, config/initializers/mailgun.rb
Resolves #262
This PR adds Mailgun setup for the production setup. Mailgun has already been added on the Heroku side, so emails (password reset is the only active email at the moment) will immediately start being sent after this is deployed. 
This PR also adds a volunteer deactivation template for testing purposes.
No effect.
Local testing and existing Rspec tests pass.
=> Adds Mailgun Production Email Setup

config/environments/production.rb, config/environments/staging.rb
This PR adds the same mailgun configuration options to the staging environment that we just added to the production environment.
=> Add mailgun configuration settings to staging environment

spec/features/user_inputs_dangerous_values_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/user_input_helpers.rb
Resolves #182 
This PR adds new feature test to test some common dangerous strings on the volunteer edit form.
No effect.
New test has been added.
=> Add feature spec to make sure dangerous strings do not error

.rubocop.yml, app/controllers/case_contact_reports_controller.rb, app/controllers/case_contacts_controller.rb, app/controllers/reports_controller.rb, app/models/case_contact.rb, app/models/case_contact_report.rb, app/views/reports/index.html.erb, config/routes.rb, spec/requests/case_contact_reports_spec.rb, spec/requests/reports_spec.rb
Resolves #306 #305
This PR fixes N+1 queries that were causing major performance issues with the report download feature. It also adds driving reimbursement fields to the case contacts report.
No effect
New tests have been added and existing tests pass.
=> Fix report download performance and add driving reimbursement fields

Gemfile, Gemfile.lock, app/controllers/dashboard_controller.rb, app/decorators/user_decorator.rb, app/views/dashboard/_volunteers_table.html.erb, config/environments/development.rb
Resolves #307
This PR adds a default value of None if a volunteer has not made any case_contacts. It also adds the bullet gem to detect N+1 queries because we had a number of them on the dashboard. I did a quick scan and fixed the ones that I found.
No effect.
Existing tests pass.
=> Adds default value for last contact made

yarn.lock
It looks like I didn't commit the yarn.lock file after my most recent changes, this should fix the deployment issues.
=> Re-run yarn install to fix deployment issue

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Resolves #326
fix header - vs /
=> Fix page header - vs /

app/views/layouts/_footer.html.erb
=> Fix contact Us link to fix bug #324

Procfile
Resolves #142 
We'd like to automatically run database migrations on deploy.
Not at all 😼 Someone with access to Heroku will have to try this out and make sure it actually works.
N/A
=> Add Procfile with release phase for migrations

app/decorators/casa_case_decorator.rb, app/decorators/case_contact_decorator.rb, app/decorators/user_decorator.rb, app/models/user.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/casa_cases/index.html.erb, app/views/casa_cases/show.html.erb, app/views/case_assignments/index.html.erb, app/views/dashboard/_volunteer_dashboard.html.erb, app/views/dashboard/_volunteers_table.html.erb, app/views/volunteers/edit.html.erb, db/seeds.rb
Resolves #113
Add 🐛🦋 to all UI locations for transition aged youth
n/a
😅
=> Pretty transition icons

.travis.yml, README.md
Resolves #346
Add codeclimate api key to travis build, update badge URLs
no
view the badge on the readme
=> Travis test coverage

README.md
N/A
Added documentation for setup on Ubuntu (including WSL1 and WSL2).
No impact
Not a code change
💪
=> Updated docs for Ubuntu and WSL

app/views/casa_cases/show.html.erb, app/views/case_contacts/_case_contact.html.erb, app/views/dashboard/_volunteer_dashboard.html.erb, spec/features/volunteer_views_dashboard_spec.rb
Paired with @leesharma :)
Resolves #394
=> Label case contact created by

app/mailers/volunteer_mailer.rb, app/views/volunteer_mailer/deactivation.html.erb
Resolves #22 
The copy in the volunteer deactivation email, per #22.
N/A
Nothing triggers this email yet, as far as I can tell. We should probably add some tests when that functionality is added.
=> Update text for deactivation email

.travis.yml, Gemfile, Gemfile.lock, README.md
None
This has never worked. It looks like https://github.com/codeclimate/test-reporter/issues/418 is the problem. 
Following instructions in https://docs.codeclimate.com/docs/travis-ci-test-coverage
No
Run a build
=> Test reporting from TravisCI to CodeClimate

config/environments/staging.rb
None
This is a follow-up to https://github.com/rubyforgood/casa/pull/465
no
Send a live email on staging
n/a
=> Stop using mailgun

config/environments/production.rb, config/environments/staging.rb
Sorry, there were a couple of typos and spaces inserted from copy and pasting. This fixes htem.
=> Formatting errors fix from copy paste.

app/controllers/volunteers_controller.rb, app/models/case_contact.rb, app/models/user.rb, config/environments/production.rb, config/environments/staging.rb, spec/models/user_spec.rb
=> Run bundle exec standardrb --fix

app/controllers/volunteers_controller.rb, app/views/casa_cases/_volunteer_assignment.html.erb
Resolves #443
Note that this PR depends on #479 
Allow reactivating volunteers from Casa Case Edit screen.
- Supervisor permissions: Checks to ensure volunteer is supervised by currently-logged-in supervisor
- Admin permissions: Can activate any volunteer
WIP
=> [WIP] Allow reactivating volunteers from Casa Case Edit screen

app/controllers/imports_controller.rb, app/controllers/supervisors_controller.rb, app/controllers/volunteers_controller.rb, app/models/case_contact.rb, app/models/concerns/file_importer.rb, app/models/user.rb, config/environments/production.rb, config/environments/staging.rb, spec/models/user_spec.rb
Some random things in here:
- Change the hardcoded devise-invitable passwords in the app from `123456` to instead use `SecureRandom.hex(10)`
- Some changes from running `standardrb --fix`
- Moved the `check_empty_attachment` on the import page into a before action so it will actually fire if a user attempts to click the import button without first attaching a file.
- Updated the variable `@failed_imports` to instead of throwing in defined values into the list of values it will show the user to instead throw in the entire failed row that they attempted to import. This is useful in the case there they attempt to import the wrong kind of csv -- say they import a `casa_case.csv` instead of a `volunteers.csv`.
=> Change the devise invitable password to something random.

Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, config/environments/staging.rb, config/initializers/send_in_blue.rb
=> Attempt to use sendinblue api

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb, config/initializers/devise.rb
This PR swaps us over to sendgrid. Not sure if it is needed now that sendinblue appears to be working.
=> Put in the sendgrid stuff.

app/controllers/case_contacts_controller.rb, app/models/case_contact.rb, spec/features/admin_adds_a_case_contact_spec.rb, spec/models/case_contact_spec.rb
Resolves #484 
Resolves #490 
Set minimum case contact duration == 15 minutes
Fix when admin adds case contact and gets error, all case contacts appear
- Volunteer permissions: -
- Supervisor permissions: -
- Admin permissions: -
Edited old tests and added a new feature test
=> Add case contact min duration

config/environments/development.rb, config/environments/test.rb
Resolves #519 
Added a Bullet for tests and added a separate bullet log, so that it would be easier to track errors.
=> Edit config for Bullet gem

config/locales/devise_invitable.en.yml
This seems like a good idea, what do you think?
=> Update invite email subject to be more descriptive

app/models/user.rb, app/models/volunteer.rb, app/views/casa_cases/_volunteer_assignment.html.erb, spec/features/admin_assign_a_volunteer_to_case_spec.rb
Resolves #535 
Inactive volunteers do not display in dropdown menu of available volunteers
Added test
=> Hide inactive volonteers from case select

app/javascript/src/case_contact.js
Resolves #485 
Added FE validation for the duration selector
I will work on adding a test
**Sadly this guy 👇  has more hair than me 😢**
=> Add FE duration validation in contact form

app/models/case_contact.rb
Resolves #549 
Add new contact types:
- Medical Professional
- DSS Worker
- Other Support Worker
=> Add new contact types

app/controllers/volunteers_controller.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/case_assignments/index.html.erb, app/views/volunteers/edit.html.erb, spec/features/admin_assign_a_volunteer_to_case_spec.rb, spec/features/case_assigned_to_multiple_volunteers.rb, spec/features/volunteer_assigned_to_multiple_cases.rb, spec/models/case_assignment_spec.rb
Resolves #548
Add tests for existing feature "Volunteer can be assigned to multiple cases" and fix bug
no
capybara
n/a
How to embed:
=> Add tests for Volunteer can be assigned to multiple cases

.erb-lint.yml, Gemfile, Gemfile.lock, README.md
None
Add a linter (but it doesn't run in travis yet)
`bundle exec erblint --lint-all`
https://github.com/Shopify/erb-lint#Linters
nope
`bundle exec erblint --lint-all`
n/a
https://media.giphy.com/media/QBRmnNI3rwxbGELsJR/giphy.gif
=> Add ERB linting

app/controllers/case_contacts_controller.rb
This resolves #537 
This was an error with the redirect_to after the create. I updated the redirect action and it fixes this issue.
=> Fix the first case contact created to redirect to the correct page.

spec/features/admin_assign_a_volunteer_to_case_spec.rb
A time test was not accounting for time zones. I implemented Sean's fix to use `Time.zone.now` instead of `Date.today`.
=> Implement Sean's fix of time zone test error.

LINUX_SETUP.md
I wanted to create a document that would enable developers and administrators to quickly and easily stand up a development and/or runtime environment on Linux, either on a developer's system, or on a virtual or cloud machine.
The result is this document. I tested the procedure several times creating Vagrant Ubuntu 20.04 VM's on a Linux host.
=> Add LINUX_SETUP.md.

db/seeds.rb
=> Add other casa admin to seed data

bin/update
I've found this useful on other projects. It adds a script similar to `bin/setup` that will do gem, db, and yarn updates.
na
run manually
=> Creates a bin/update script

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md
None of the existing issue templates is a good fit for documentation changes/suggestions.
Here is a suggested template. Or, do you have other suggestions/modifications?
=> Add documentation issue template.

app/models/all_casa_admin.rb, db/seeds.rb
Resolves #627
Add a user of type `AllCasaAdmin` as part of `seed.rb`
I also ran this code in staging via heroku console
no
n/a
(actually maybe we *should* write tests for seed... hmm)
n/a
How to embed:
=> Add all casa admin as part of seed

Gemfile, app/controllers/casa_cases_controller.rb, app/models/case_contact.rb, app/models/user.rb, app/views/casa_cases/show.html.erb, app/views/case_assignments/index.html.erb, app/views/imports/index.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, db/migrate/20200818220659_add_is_active_to_supervisor_volunteers.rb, db/seeds.rb, scripts/create_casa_admin.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/imports_request_spec.rb, spec/requests/supervisor_volunteers_spec.rb, spec/requests/volunteers_spec.rb, spec/support/capybara.rb, spec/system/admin_adds_a_case_contact_spec.rb, spec/system/admin_assign_a_volunteer_to_case_spec.rb, spec/system/admin_views_dashboard_spec.rb, spec/system/case_assigned_to_multiple_volunteers_spec.rb, spec/system/edit_user_system_spec.rb, spec/system/new_supervisor_system_spec.rb, spec/system/volunteer_assigned_to_multiple_cases_spec.rb, spec/views/case_contacts/new.html.erb_spec.rb
Better line wraps!
Followed  suggestions by @compwron to improve readability
See screenshots
**First view:**
**Second view:**
How to embed:
=> line wraps in app/views/imports/index.html.erb now semantically relevant

app/models/case_contact_report.rb, spec/models/case_contact_report_spec.rb
Resolves #604 
Add column Notes to Case Contact Reports
Edit test
=> Add notes to case contact report

app/helpers/case_contacts_helper.rb, spec/helpers/case_contacts_helper_spec.rb
Case contact helper methods have being refactored and tests cases were added.
- `set_hours_form`
- `set_minutes_form`
- `set_contact_made_false`
- `set_contact_made_true`
No permissions were affected
We added tests
No UI changes
How to embed:
=> Refactors case_contact_helper methods and adds tests to those methods

db/seeds/development.rb, db/seeds/staging.rb
none
https://edgeguides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data
https://blog.saeloun.com/2019/09/30/rails-6-adds-db-seed-replant-task-and-db-truncate_all.html
https://github.com/rails/rails/issues/34765
no
`rake db:seed`
`rake db:reseed`
=> Add deletes to seed

app/models/case_contact.rb, app/values/case_contact_parameters.rb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/index.html.erb, db/migrate/20200905192934_remove_other_type_text_from_case_contacts.rb, db/schema.rb
Resolves #547 
Remove reference to other_type_text (which wasn't used)
Rerun test suite
=> Remove ref to other_type_text in case contacts model

.gitignore, app/views/casa_cases/_volunteer_assignment.html.erb
=> Volunteer without name set cannot be reached on case view

app/controllers/casa_cases_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/volunteers_controller.rb, app/models/case_contact_report.rb, app/policies/dashboard_policy.rb, app/views/supervisors/edit.html.erb, app/views/volunteers/edit.html.erb
Resolves #519
Resolves N+1 bullet notifications on casa_cases
bullet was raising a n+1 error on case_controller#index.
In order to fix the error, an includes on casa_cases when pulling the organization was added when the current user is not a volunteer.
No permissions were affected
Running bullet the error in that action is not raised.
How to embed:
=> Fixes bullet n+1 on casa cases.

app/controllers/imports_controller.rb, app/lib/importers/file_importer.rb, spec/features/admin_assign_a_volunteer_to_case_spec.rb
These are suggested modifications to PR # 603, branch `603-refactor-file-importer`.
These are just some (IMO) marginal improvements to the PR.
Existing tests will be modified as necessary.
=> WIP: 603b refactor file importer suggestions

app/javascript/packs/application.js, app/javascript/src/all_casa_admin/tables.js, app/javascript/src/case_contact.js, app/javascript/src/shared.js
Resolves #534 
Turned off the flash message alert hiding altogether. If users end up needing it, then it would be okay to turn it back on.
None tests, but there weren't any to begin with 🤷 
stays that way, all day, or ur 💰  back
=> 534 keep errors visible

app/javascript/packs/application.js, app/javascript/src/shared.js
=> remove unused shared.js file

app/javascript/src/case_contact.js
=> fix yarn lint error in case_contact.js

app/controllers/supervisors_controller.rb, app/models/user.rb, app/views/supervisors/edit.html.erb, spec/factories/supervisor.rb, spec/requests/supervisors_spec.rb, spec/system/user_views_supervisor_edit_spec.rb
Resolves #729 
Use method instead of instance variable to handle template rendering in case of error.
Added some system and request specs
=> Fix error that occurs when editing supervisor email to existing email address

Gemfile, Gemfile.lock
=> #739 Eliminate awesome_print gem and replace it with amazing_print.

.gitignore, app/controllers/volunteers_controller.rb, app/models/casa_case.rb, app/views/volunteers/edit.html.erb, spec/factories/casa_case.rb, spec/models/casa_case_spec.rb, spec/system/volunteer_assigned_to_multiple_cases_spec.rb
=> 677 do not double assign case

app/javascript/packs/application.js, app/javascript/src/select.js, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/case_assignments/index.html.erb, app/views/supervisors/edit.html.erb, app/views/volunteers/edit.html.erb, package.json, yarn.lock
Resolves #557 
Add select2 by yarn and class select2 to form selects.
=> Add Select2 for form selects

app/javascript/packs/application.js, app/javascript/src/select.js
none
yarn lint failed, changed some imports, changed linter directives. 
No functional code was modified.
=> Clean up yarn lint errors on selectjs

app/controllers/casa_orgs_controller.rb, app/javascript/packs/application.js, app/javascript/src/select.js, app/policies/application_policy.rb, app/views/casa_orgs/edit.html.erb, app/views/layouts/_header.html.erb, config/routes.rb, spec/requests/casa_orgs_request_spec.rb
Resolves #648 
Added a casa orgs controller and view for admins to edit organization
Test the edit request
How to embed:
=> 648 customize appearance of org

app/controllers/all_casa_admins/casa_admins_controller.rb, app/javascript/src/stylesheets/application.scss, app/javascript/src/stylesheets/shared/dashboard.scss, app/views/all_casa_admins/casa_admins/_form.html.erb, app/views/all_casa_admins/casa_admins/new.html.erb, app/views/all_casa_admins/casa_orgs/show.html.erb, app/views/all_casa_admins/shared/_error_messages.html.erb, app/views/shared/_error_messages.html.erb, config/routes.rb, spec/requests/all_casa_admins/casa_admins_spec.rb, spec/system/all_casa_admins/all_casa_admins_casa_orgs_spec.rb
Resolves #686
Start fleshing out the flow of creating new CASA admins as an All CASA admin.
Still unresolved:
Tests added
=> New CASA Admin creation flow

app/models/volunteer.rb, app/views/dashboard/_volunteers_table.html.erb, spec/models/casa_case_spec.rb, spec/models/volunteer_spec.rb, spec/requests/all_casa_admins_spec.rb, spec/requests/casa_orgs_request_spec.rb, spec/system/admin_views_dashboard_spec.rb, spec/system/supervisor_views_dashboard_spec.rb, spec/system/user_views_supervisor_edit_spec.rb
Resolves #186
- paired with @keithrbennett
- added 🕐 (clock icon) if volunteer has any one case where they haven't made contact in 30 days
No permissions changed
Added tests on the model for each branch within the function
=> Adds flag for users who haven't made contact in 30 days

DOCKER.md, Dockerfile, README.md, bin/update
* Slight optimization to Dockerfile
* Added note about running the webpack-dev-server when using Docker
* Added `rake after_party:run` to the `bin/update` file
* Added notes about After Party in the README
=> Doc updates

app/controllers/casa_admins_controller.rb, app/controllers/supervisors_controller.rb, app/views/casa_admins/new.html.erb, app/views/dashboard/_admins_table.html.erb, config/routes.rb, spec/system/creating_casa_admins_spec.rb
Resolves #001
Added the ability for an admin to add another admin
Test Location: spec/system/creating_casa_admins_spec.rb
How to embed:
=> 774 admin can add new accounts

public/casa_cases.csv
https://github.com/rubyforgood/casa/issues/800
Added a "birth month and year" column header to the example case csv file.
How to embed:
=> 800 Add “birth month and year” column header to example case csv file

app/lib/importers/case_importer.rb, spec/fixtures/casa_cases.csv, spec/lib/importers/case_importer_spec.rb
Resolves #799 
Allows a new csv column containing the birth month and year when importing a case.
Importing a new CASE csv file containing a new column which header is `birth_month_year_youth`. There are automatized tests covering this change.
N/A
How to embed:
=> Import birth month and year of case

app/javascript/src/stylesheets/shared/layout.scss, app/javascript/src/stylesheets/shared/navbar.scss, app/javascript/src/stylesheets/shared/sidebar.scss, app/views/layouts/_flash_messages.html.erb, app/views/layouts/_login_header.html.erb, app/views/layouts/_mobile_navbar.html.erb, app/views/layouts/_sidebar.html.erb, app/views/layouts/application.html.erb
Resolves #878 
Fixes a few alignment and page scrolling issues:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
How to embed:
=> [878] Fixes various UI issues

DOCKER.md, docker-compose.yml
* Have web service depend on database service (can remove one setup step)
* Switch around ongoing development items to improve relevance for development
=> Minor Docker improvement

app/views/supervisors/index.html.erb, app/views/volunteers/index.html.erb, spec/system/admin_views_volunteers_page_spec.rb
Resolves #731 
Changed ids to make them unique for a single page
Fix the old specs
How to embed:
=> Fix unique ids within a single page

app/decorators/casa_case_decorator.rb, app/views/casa_cases/show.html.erb, spec/decorators/case_decorator_spec.rb, spec/system/supervisor_edits_case_spec.rb, spec/system/volunteer_edits_case_spec.rb
this is a copy of https://github.com/rubyforgood/casa/pull/912 without linter changes to make it easier to review and see if the build passes
=> Do not merge- copy of #912 

Gemfile, spec/helpers/application_helper_spec.rb, spec/models/user_spec.rb, spec/requests/casa_admins_spec.rb, spec/system/all_casa_admins/all_casa_admins_casa_orgs_spec.rb, spec/views/layouts/application.html.erb_spec.rb, yarn.lock
=> Yarn updates

db/seeds/staging.rb, spec/lib/db_seed_spec.rb
Also, fix staging seed.rb with a typo
and fix miles_driven nil to 0 value
Resolves #790 
How to embed:
=> Write a tests for dev and staging seed files

public/robots.txt
Resolves #711 
Provides a slight improvement to privacy and security and reduced load of sites not having to block well-behaved search bots.
=> Update Robots per Issue 711

spec/system/volunteer_views_dashboard_spec.rb
Resolves #957 
Redesign changed dashboard for volunteers
=> 957 fix spec for case contacts volunteers

lib/tasks/deployment/20200907142217_populate_prince_george_casa_org_details.rake, spec/lib/tasks/deployment/populate_prince_george_casa_org_details_spec.rb
Resolves #831 
- made task work with empty DB or populated DB
- added tests
- one of the tests had to be commented out because AfterParty is only allowing the task to be run once
- each passes if run in isolation, but either will fail if the other test is run first
Added tests, had to comment one out (see screenshot to see both passing separately)
=> Update task to populate Prince George CASA details

spec/system/supervisor_views_volunteers_page_spec.rb
It variant of spec passes as in local env so in Docker env
=> Fix spec for both docker and local envs

spec/system/admin_adds_new_case_spec.rb
Resolves #958
Fixed the 'admin adds new case' test and added more scenarios
=> Fixed the admin adds new case test and added more scenarios

README.md
Resolves #893 
Added QA env information to README
N/A
How to embed:
=> Added QA environment info to README #893

app/models/case_contact.rb, app/views/case_contacts/_form.html.erb, spec/models/case_contact_spec.rb
Resolves #990 
Updated FE and BE case contact validation for miles driven. Too large of a number would cause a server side error.
- Supervisor permissions: No
Added server side validation test
Backend validation message before adding FE validation check:
Frontend Validation message:
How to embed:
=> Add validation for miles driven

.github/labeler.yml, .github/workflows/label.yml
Resolves #195 
Adds a GitHub action that will automatically apply labels to a Pull
Request based the files that were changed.
Hopefully, this makes it easier to triage PRs.
N/A - this should not impact permissions. This is related to DX.
Unfortunately, I'm not sure that there's a great way to test this without getting it into the repo.
=> Adds labeler GitHub Action.

.github/labeler.yml
This is still a WIP - trying to test the labeler action.
Resolves #195
Updated syntax in `labeler.yml` to fix auto-labeler GitHub actoin
N/A
How to embed:
=> Fixes syntax in `label.yml`

db/seeds/development.rb, spec/lib/db_seed_spec.rb, spec/lib/tasks/deployment/populate_prince_george_casa_org_details_spec.rb, spec/rails_helper.rb
Thanks to @littleforest for figuring out what was causing the build to fail 👏
=> Fix failing build

.github/labeler.yml, .github/workflows/label.yml
Resolves #195 (and fixes the version introduced in #1001 and #1006).
* Adds workflow file for Action that uses the labeler action
* Creates `labeler.yml` file that maps labels to file changes that will
trigger adding that label
Possibly more interesting is what is different between this and #1001 
* This uses only V2 syntax. In the previous PR, I was looking at the docs on the `main` branch for the action which has unreleased syntax (namely the `any` keyword). For [stability purposes](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-to-your-workflow) it is useful to reference the version of the action we are using (as opposed to referencing the `main` branch).
* Fixes some of the globs. For example, drops the …
=> [WIP] Fix labeler action

app/controllers/casa_admins_controller.rb, app/controllers/case_assignments_controller.rb, app/controllers/volunteers_controller.rb, app/policies/casa_admin_policy.rb, app/policies/casa_case_policy.rb, app/policies/case_assignment_policy.rb, app/policies/volunteer_policy.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/case_contacts/_case_contact.html.erb, app/views/users/edit.html.erb, app/views/volunteers/index.html.erb, spec/policies/casa_admin_policy/casa_admin_policy_spec.rb, spec/policies/casa_case_policy/casa_case_policy_spec.rb, spec/policies/case_assigment_policy/case_assigment_policy_spec.rb, spec/policies/volunteer_policy_spec.rb, spec/requests/volunteers_spec.rb, spec/views/casa_cases/edit.html.erb_spec.rb, spec/views/casa_cases/new.html.erb_spec.rb, spec/views/case_contacts/case_contact.html.erb_spec.rb, spec/views/case_contacts/index.html.erb_spec.rb, spec/views/volunteers/index.html.erb_spec.rb
Reverts rubyforgood/casa#1025
This PR is to bring back the logic from this PR once the build is green :)
=> Revert "Revert "Move user permission logic from erb into pundit policy files ""

db/seeds/development.rb, db/seeds/qa.rb, db/seeds/staging.rb, spec/seeds/seeds_spec.rb
Resolves #995 
I modded some constants inside each environment seed file as it was not really necessary to have them set like that. Variables work fine and avoids conflicts when loading them all.
I didn't stub at all, just the environment in order to match the seed file. This makes the run kinda lengthy (see screenshot), but hey, we want to make sure the seeds are working.
None.
Just run:
```shell
rspec spec/seeds/seeds_spec.rb
```
=> Adds tests to DB Seeds

Gemfile.lock, yarn.lock
=> yarn upgrade

app/javascript/__tests__/setup-jest.js, app/javascript/packs/application.js, app/javascript/src/case_contact.js, app/javascript/src/dashboard.js, app/javascript/src/index_reports.js, jest.config.js, package.json
Resolves [#1045](https://github.com/rubyforgood/casa/issues/1045)
Someone actually ran `yarn test`, and it was broken. I ignored the cypress tests from the linter, fixed some linting errors in the javascript files, and imported JQuery properly.
This is just for developer happiness!
This is not integrated into travis (yet), pull it down locally and run `yarn test`
=> fixed 'yarn test'

doc/LINUX_SETUP.md
I used the Linux documentation to create a couple of Vagrant VM's and made some improvements to the documentation based on my experiences.
=> Test and improve the Linux documentation.

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/config.yml
Resolves #1051 
Add new github issue type Chore
For things like updrade gem versions, deleting old db columns, adding missing tests etc
=> Add new github issue type Chore

app/javascript/src/case_contact.js, app/javascript/src/stylesheets/shared/layout.scss, app/views/case_contacts/_case_contact.html.erb, spec/system/volunteer_edits_a_case_contact_spec.rb
=> Add after-quarter edit tooltip

.travis.yml
=> 1095 update node version in travis

.travis.yml
=> A different way to tell travis about chrome

.standard.yml, app/controllers/case_contact_reports_controller.rb, app/helpers/report_helper.rb, app/javascript/src/dashboard.js, app/models/user.rb, app/views/reports/index.html.erb, lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake, spec/requests/case_contact_reports_spec.rb, spec/support/css_helpers.rb, spec/system/admin_views_case_contact_index_spec.rb, spec/system/volunteer_edits_a_case_contact_spec.rb, spec/views/volunteers/index.html.erb_spec.rb
Resolves #1098  
Updated standardrb to ignore the one off after party task. Corrected the linter errors in other files automagically.
No permissions changes
existing test suite
=> Correct linter errors on that were present in master [#1098]

app/javascript/src/stylesheets/pages/login.scss
Tiny PR to fix stylings.
Before:
After:
=> Fixes the login styling where it looks wonky on the sign_in page

.gitignore
none
gitignore, to avoid unwanted local changes for contributors
no
no
=> Add some annoying files to gitignore

db/seeds/development.rb
_Partially_ resolves #1089
I've modified the seeds file (only the development file) in several ways, to:
* Make Faker data random seed configurable via a FAKER_RANDOM_SEED environment variable.
* Reorganize the code with modules & classes
* Add user feedback
I think this is a good first step towards implementing issue #1089 and would like to defer building on it until it is vetted and merged into master.
=> Refactor & improve development seeds script, add faker seed specification.

app/javascript/src/stylesheets/application.scss, app/views/case_contacts/_form.html.erb, spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #820 
The date/calendar picker was not displaying on all browsers because the HTML5 date type is not well supported. `bootstrap-datepicker` was already installed and being used in the reports view for selecting dates. Added the necessary attributes to the `occurred_at` field to enable it in the contact form. However, the calendar was not styled correctly and was difficult to read since the spacing between columns was virtually non-existent (This was also an issue on the reports view). Imported the `bootstra-datepicker` css file which fixed the styling issue.
The keyboard can also be used to select a date. The datepicker also displays on my mobile device, which looks better than the native date picker: Here is screen cap of native date picker on iphone x. For whatever reason it …
=> Use datepicker for selecting dates

app/helpers/report_helper.rb, case-contacts-report-1602730057.csv, case-contacts-report-1602730059.csv, spec/models/contact_type_group_spec.rb, spec/system/edit_casa_org_spec.rb, spec/views/layouts/footer.html.erb_spec.rb
Resolves #1127
Linting
- Volunteer permissions: N/A 
- Supervisor permissions: N/A 
- Admin permissions: N/A 
Lint
Lint
How to embed:
=> Clean up for duplicate names

app/models/casa_case.rb, lib/tasks/scheduler.rake, spec/models/casa_case_spec.rb
Resolves #881 
Created ".clear_court_dates" method in model
Added scope to filter out cases with passed dates
Added tests to "casa_case_spec.rb" 
Added task to scheduler.rake to update dates 
Tested with rspec
=> 881 court date clear

spec/policies/application_policy_spec.rb, spec/policies/casa_admin_policy/casa_admin_policy_spec.rb, spec/policies/casa_case_policy/casa_case_policy_spec.rb, spec/policies/case_assigment_policy/case_assigment_policy_spec.rb, spec/policies/case_contact_policy/case_contact_policy_spec.rb, spec/policies/dashboard_policy_spec.rb, spec/policies/supervisor_policy_spec.rb, spec/policies/volunteer_policy_spec.rb
Just refact policies specs, and let a pattern to this specs
=> refact policies spec

lib/tasks/data_post_processors/contact_type_populator.rb
None.
Refactored ContactTypePopulator and removed some stray disabled code.
=> Refactor ContactTypePopulator.

app/models/contact_type_group.rb, db/seeds.rb, db/seeds/db_populator.rb
* The random setting of volunteers' inactive state was done in two places, but the code in one of them could never be executed, so it wound up behaving correctly. I've removed the duplicate functionality and fixed it.
* I've implemented @littleforest's suggestions regarding some code style improvements.
=> Minor fixes to seeding.

DEPLOY_CHECKLIST.md, README.md
Insert link from README.md to DEPLOY_CHECKLIST.md containing
specified deployment checklist.
Resolves #1119 
A deploy checklist was added as a link to the README file.
No tests for this documentation
How to embed:
`![alt text](https://media3.giphy.com/media/kigfYxdEa5s1ziA2h1/source.gif)`
=> Add deploy checklist, per Issue #1119

spec/models/casa_case_spec.rb
https://github.com/rubyforgood/casa/pull/1157/files#diff-03fbcc0e576942ad7952267e91f0262cffa60706590747f0c52b78dea98425dbR79
=> Revert change to spec for error that was misconstrued

spec/lib/tasks/data_post_processors/contact_type_populator_spec.rb
None
Added missing tests for ContactTypePopulator
It doesn't
NA
NA
=> add tests for ContactTypePopulator

app/controllers/casa_cases_controller.rb, app/models/casa_case.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/index.html.erb, app/views/casa_cases/show.html.erb, db/migrate/20201025162142_add_judge_to_court_cases.rb, db/schema.rb, spec/factories/casa_case.rb, spec/models/casa_case_spec.rb
Resolves #927 as the second part of #1157 
Added the option to select a judge for a casa case
=> Associate judge to court case

app/javascript/src/stylesheets/application.scss, app/javascript/src/stylesheets/pages/casa_orgs.scss
Resolves #1161 
height of the container to match the font size on the input[file], then I found the text was overflowing through the container on small screens, so I added overflow: hidden.
Using the browser dev tools on 1920x1080 and the responsive tool.
**before:**
**after:**
=> Improve upload file button style

Gemfile, Gemfile.lock, app/javascript/__tests__/dashboard.test.js, app/javascript/src/dashboard.js, app/views/case_court_reports/index.html.erb, doc/CONTRIBUTING.md, doc/CYPRESS.md
I might've not followed semver with the last Standard release 😅 . I also wanted to go ahead and update the contributing docs to make it very clear about what needs to pass prior to merging. I've noticed people missing standard and cypress recently :). I went ahead and ran the optional linters as well and this is just what's autofixed, didn't bother to go through and fix any other issues.
Ran all the tests! But no new functionality...
=> update standard, run all linters, and update docs

db/schema.rb
this is cleanup for https://github.com/rubyforgood/casa/pull/1179/ which I merged because it was easier to merge-and-fix than fix-and-merge 😅
=> schema cleanup

spec/spec_helper.rb
It will make test output easier to see
=> Quit printing the names of all the tests

README.md
we are currently on travis.org not travis.com we do want to switch to travis.com eventually
=> we are currently on travis.org not travis.com we do want to switch to travis.com eventually

Gemfile.lock, app/javascript/__tests__/dashboard.test.js, app/javascript/packs/application.js, app/javascript/src/dashboard.js, app/javascript/sweet-alert-confirm.js, app/views/casa_cases/_form.html.erb, package.json, spec/system/admin_edits_a_case_spec.rb, yarn.lock
Resolves #1197
Only visual changes
Add dependency of sweet alert 2 on packeage.json
Apply warning box of sweet alert fire when disable case
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: none
Run default tests only
I'm starting contributing, take easy on me! haha
=> Case#1197 add friendlier warning box admin disables case

spec/requests/all_casa_admins/casa_admins_spec.rb
adding to #1180 
added 2 new tests re: permissions to access edit admin page
2 checks for redirect when user is either not logged in or logged in without correct permissions
N/A
=> adding to #1180

app/mailers/volunteer_mailer.rb, app/views/layouts/mailer.text.erb, app/views/volunteer_mailer/court_report_reminder.html.erb, lib/mailers/previews/volunteer_mailer_preview.rb, lib/tasks/court_report_due_reminder.rake
Resolves #620
Added mailer to be sent 1 week before a volunteer has a court report due.  Added a rake task to be set up on heroku to run every day to send the mailer to those who meet the qualifications.
N/A
I added a mailer preview so we can see the preview.  The other mailers don't have tests, I'm not sure about testing mailers, I'm happy to add them if you want them I just might need a bit of help with this.
=> Court report reminder email

app/models/casa_case.rb
Resolves #1141
Added a check to ensure court date had passed before running the update
See casa_case_spec.rb
Hacktoberfest is over but i wasn't really in it for the T-shirt (Although the tree sounded like a good idea), this is my first (well technically second) open source contribution, Love what you all are doing. Sorry. i know this isn't the place for this hehe
=> Add check before due dates are cleared

app/decorators/casa_case_decorator.rb, app/javascript/src/dashboard.js, app/models/casa_case.rb, app/views/casa_cases/index.html.erb, spec/system/volunteer_views_dashboard_spec.rb, spec/views/casa_cases/index.html.erb_spec.rb
Resolves #1185
- Implemented all requirements listed in #1185
- _As a bonus: the column picker to toggle show/hide was also implemented to similar to volunteers view_
- Added specs that rely on capybara to toggle UI elements changing filters
=> Add filters on cases view

app/models/casa_case.rb
Resolves #1141
https://github.com/rubyforgood/casa/pull/1235/files/9c0db4d77fca263d122524990f62caacbccb323e..5609cc49ff441042c6f9a39ad34e05e770e00c0a#r516410229
no
uh
=> Add a check that court report exists before updating it

app/javascript/__tests__/dashboard.test.js, app/views/all_casa_admins/casa_admins/edit.html.erb, app/views/casa_cases/_inactive_case.html.erb, app/views/casa_cases/edit.html.erb, app/views/casa_cases/index.html.erb, app/views/casa_cases/show.html.erb, app/views/layouts/_sidebar.html.erb, app/views/volunteer_mailer/court_report_reminder.html.erb
None
run erb and js linters
no
existing tests
=> run erb and js linters

app/controllers/volunteers_controller.rb, spec/requests/volunteers_spec.rb
Resolves #1262 
Return to Volunteers page after creating volunteer
Edit test
=> Return to Volunteers page after creating volunteer

.github/workflows/cypress.yml, .github/workflows/erb_lint.yml, .github/workflows/ruby_lint.yml, .github/workflows/security.yml
=> Split out cypress and dont build if only docs are updated

spec/spec_helper.rb
I made the following changes to the SimpleCov configuration:
* Filtered out the db and spec directories
* Provided grouped coverage results
=> Updated SimpleCov configuration

db/seeds.rb, lib/tasks/deployment/20200907142217_populate_prince_george_casa_org_details.rake, lib/tasks/deployment/20200913155303_populate_missing_display_names.rake, lib/tasks/deployment/20201005203140_populate_contact_type_groups_and_contact_types.rake, lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake, lib/tasks/deployment/20201108181154_backfill_court_report_submitted_at.rake
* The puts commands in the deployment tasks are disabled for the test environment only.
* The puts commands in the db/seeds.rb script are commented out to minimize excessive screen output when running the test suite.
=> Make print statements conditional so that they will not show up in rspec

doc/DOCKER.md
* Updated Docker manual vs automatic paragraph text to be more informative
=> Update Docker instructions 

db/seeds/db_populator.rb
Resolves #1323 
Corrects a typo to use comparison rather than assignment.
=> Correct operator.

app/javascript/src/stylesheets/pages/login.scss, app/views/devise/passwords/new.html.erb, app/views/devise/shared/_links.html.erb
=> Fix the styling issue on the reset password page.

app/policies/application_policy.rb, app/policies/casa_case_policy.rb, app/policies/case_contact_policy.rb, app/policies/dashboard_policy.rb, app/policies/user_policy.rb
I removed the duplicate methods inside the policies scopes.
I considered that the tests are already written.
=> Refact: remove duplicate methods in polices scopes

app/policies/application_policy.rb, app/policies/casa_case_policy.rb, app/policies/case_contact_policy.rb, app/policies/dashboard_policy.rb
This is a follow-up to https://github.com/rubyforgood/casa/pull/1361
More naming improvements, inspired by https://github.com/rubyforgood/casa/pull/1361
no change
existing spec
=> Renaming policy aliases

app/javascript/src/stylesheets/pages/dashboard.scss, app/javascript/src/stylesheets/shared/dashboard.scss
Resolves #1272
Added space in between checklist boxes to prevent from clicking the wrong filter
How to embed:
=> Add space #1272 solution

app/policies/case_contact_policy.rb, app/policies/user_policy.rb
=> Fix lint without breaking rspec

app/views/emancipations/show.html.erb, app/views/layouts/application.html.erb
All pages warn if javascript is disabled
=> added no js warning

db/seeds.rb
Resolves #1447
Running the seeds in a test will no longer output anything.
=> Silences db/seeds output when running specs

app/javascript/src/case_emancipation.js, app/javascript/src/dashboard.js, app/javascript/src/emancipations.js, app/javascript/src/stylesheets/pages/case_contacts.scss, app/views/casa_cases/show.html.erb
Resolves #1336 
Removed css rule for casa cases table as the width rule seemed to be causing the issue of the columns failing to align with the headers.
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: none
It's not as I don't think that you can test this 😅😂
How to embed:
=> Align table columns with headers. fixes #1336

Dockerfile
Turn off frozen check for Gemfile.lock in the Dockerfile which should resolve the issues @jhsu802701 is having in #1460 .
=> Turn off frozen for Gemfile.lock in Dockerfile

app/views/supervisor_mailer/weekly_digest.html.erb
=> Fix copy paste old text

bin/git_hooks/README.md, bin/git_hooks/lint, bin/git_hooks/update
I thought I'd polish some of my git hook scripts and add them to the repo in case anyone else wanted to use them. 
See https://github.com/FireLemons/casa/blob/add_git_hooks/bin/git_hooks/README.md for a description of the scripts
=> Git hook helper scripts

bin/git_hooks/README.md, bin/git_hooks/update-branch, bin/git_hooks/update-dependencies
added a script for gemfile updates
=> Git hook script for gem dependencies

config/environments/production.rb, config/storage.yml
=> Active storage configuration

.github/workflows/remove-help-wanted-labels.yml
Uses GitHub Actions to remove the labels once per hour.
Resolves #1362
The label will be removed from all issues in the In Progress column.
N/A
Manually tested in my test harness https://github.com/bjthompson805/hello-world-javascript-action
Screenshot of 2 issues that had "help wanted" before and now have been removed.
Note that I added a test note, which wasn't there in my last PR (#1531). This was due to an error that occurs when notes are present, which I've fixed and that Action and this one are both now working with notes.
=> Removes "Help Wanted" labels from issues in "In Progress".

Gemfile, Gemfile.lock
@compwron @littleforest azure-storage broke qa, so this PR reverts back to azure-storage-blob.  Sorry about that!
=> Gemfile back to using azure-storage-blob

config/storage.yml
@littleforest @compwron trying to figure out why azure isn't working.  Found this difference in the config file.  Hoping this change will fix it?
=> Trying different config for azure storage

app.json, config/initializers/bugsnag.rb
Resolves #1238
Added configuration for Heroku review apps
=> Heroku review app configuration

config/storage.yml
@littleforest changing the config file back - sorry about that!
=> change config file back

app/models/casa_cases_emancipation_option.rb, db/migrate/20210107181908_add_id_and_timestamps_to_case_emancipation_options_table.rb, db/schema.rb
Testing
I was able to recreate the error on my end again
after I made these different changes everything ran fine
=> Fix case/emancipation_options seed bug

app/mailers/application_mailer.rb, app/mailers/casa_admin_mailer.rb, app/mailers/supervisor_mailer.rb, app/mailers/volunteer_mailer.rb
=> mailer issues

yarn.lock
none
yarn update
to keep up to date
no
existing tests
=> yarn update

README.md, db/seeds.rb, db/seeds/db_populator.rb
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1610257613368700
Make seed not delete. Remove versions as the last step in seed
no
run
=> Make seed not delete. Remove versions as the last step in seed

.github/workflows/erb_lint.yml, Gemfile.lock
Resolves #1586
re-enable erb lint now that the fix is released
no
the build runs
meh
=> re-enable erb lint now that the fix is released

app/views/supervisors/index.html.erb, app/views/volunteers/index.html.erb
=> added margin on btn class to make more room between buttons

app.json
resolves #1537 
Heroku's latest stack is `heroku-20`.
Review app works fine so I went ahead and set qa, staging, and prod to get updated the next time they have code deployed.
=> Test heroku-20 stack on review app

app/views/casa_orgs/_judges.html.erb, app/views/judges/edit.html.erb, app/views/judges/new.html.erb, config/locales/en.yml
WIP #1257
I added two text strings and commented in the en.yml file. I want to make sure I am using the proper nesting conventions before continuing. 
N/A
N/A
How to embed:
=> added two test strings to en.yml file

db/seeds/db_populator.rb
* Removed organization prefix from seed data since we fixed all the issues re multitenancy
* Used lorem ipsum text for case contact notes
=> Seed data fixes

.github/workflows/issue-auto-unassign.yml
Resolves #1629
increase autounassign wait
no
How to embed:
=> increase autounassign wait

Gemfile.lock, config/brakeman.ignore
…gnore errors for now
none
https://brakemanscanner.org/docs/ignoring_false_positives/
https://github.com/rubyforgood/casa/pull/1621
github issues for fixing the ignored errors:
1. https://github.com/rubyforgood/casa/issues/1640
1. https://github.com/rubyforgood/casa/issues/1641
no
existing github action
How to embed:
=> gem update brakeman, then make ignorefile, then run brakeman interactive and add errors to ignorefile

app/views/casa_cases/_filter_my_cases.html.erb, app/views/casa_cases/index.html.erb
Resolves #1701
Added a partial to the casa_cases directory, 'Filter by' is not in view of Volunteers.
- Volunteer permissions: No view of 'Filter by:' 
existing tests pass
How to embed:
=>  Remove Filters from volunteer view

app/views/all_casa_admins/casa_orgs/show.html.erb, app/views/casa_cases/edit.html.erb, app/views/casa_cases/index.html.erb, app/views/case_contacts/_form.html.erb
Fixes the lint issues by running `bundle exec erblint --lint-all --autocorrect`.
=> Fix lint issues

app/views/casa_cases/_form.html.erb
Resolves #1706 
Added Court Details sub-header 
Manually by visiting http://127.0.0.1:3000/casa_cases/27/edit
How to embed:
=> add subheader to casa_cases/_form for issue 1706

.github/workflows/rspec.yml
https://codeclimate.com/repos/5eefc9243840e47b620000f6/settings/test_reporter
https://docs.codeclimate.com/docs/configuring-test-coverage
https://github.com/simplecov-ruby/simplecov
=> Report coverage

README.md
Resolves #1748
README.md - Added PostgreSQL install instructions for Widnows
Installed PostgreSQL with both methods suggested and tested rails -> database connectivity with:
`rake db:setup`
`rake db:seed:replant`
How to embed:
=> Add instructions for Windows install of PostgreSQL

bin/rails, spec/spec_helper.rb
none
make tests a little faster
no
`RUN_SIMPLECOV=true rspec`
`rspec # faster`
=> Only run simplecov when env var is passed in

.github/workflows/rspec.yml, spec/support/factory_bot.rb
=> Does this work or does rspec build db fail?

.github/workflows/rspec.yml
Resolves https://github.com/rubyforgood/casa/issues/1591
Uploads code coverage to CodeClimate.
NA
=> Upload code coverage to CodeClimate

yarn.lock
none
update js dependencies
no
existing spec + manual server testing
=> update js dependencies

app/controllers/casa_cases_controller.rb, app/models/case_contact_report.rb, app/services/case_contacts_export_csv_service.rb
Resolves n+1
Fix n+1 query problem in case contacts report
How to embed:
=> fix n+1 query in case contacts report

app/views/volunteers/_manage_cases.erb, app/views/volunteers/_manage_supervisor.erb, app/views/volunteers/edit.html.erb
none
refactoring
no
existing spec
=> Split out partials from edit volunteer to make it smaller

app/policies/case_contact_policy.rb, app/views/case_contacts/_case_contact.html.erb
Resolves #001
- Add policy into the condition in order to show delete/undelete buttons
How to embed:
=> add more condition to display the delete and undelete button

app/views/casa_admins/_form.html.erb, app/views/casa_admins/edit.html.erb, app/views/casa_admins/index.html.erb, app/views/casa_admins/new.html.erb, config/locales/views.en.yml
- Adding localization for casa_admin pages
Same
How to embed:
=> add localization for casa_admin pages

app/views/case_assignments/index.html.erb, config/locales/views.en.yml
- Add localization for case_assignments index
Same
How to embed:
=> add localization for case assignment pages

app/views/case_court_reports/index.html.erb, config/locales/views.en.yml
- Add localization for case_court_report index page
How to embed:
=> add localization for case_court_report pages

app/views/contact_type_groups/_form.html.erb, app/views/contact_type_groups/edit.html.erb, app/views/contact_type_groups/new.html.erb, config/locales/views.en.yml
- Add localization for contact type group pages
Same
How to embed:
=> add localization for contact type group pages

app/views/contact_types/_form.html.erb, app/views/contact_types/edit.html.erb, app/views/contact_types/new.html.erb, config/locales/views.en.yml
- Add localization for contact type pages
Same
How to embed:
=> add localization for contact type pages

app/views/emancipation_checklists/index.html.erb, config/locales/views.en.yml
- Add localization for emancipation checklist pages
How to embed:
=> add localization for emancipation checklist pages

app/views/emancipations/show.html.erb, config/locales/views.en.yml
Resolves #1257
- Add localization for emancipation show page
How to embed:
=> add localization for emancipation show page

app/views/casa_orgs/_contact_type_groups.html.erb, app/views/casa_orgs/_contact_types.html.erb, app/views/casa_orgs/_hearing_types.html.erb, app/views/casa_orgs/_judges.html.erb, app/views/casa_orgs/edit.html.erb, config/locales/en.yml, config/locales/views.en.yml
- Add localization for casa orgs
Same
How to embed:
=> add localization for casa_org pages

app/views/hearing_types/_form.html.erb, app/views/hearing_types/edit.html.erb, app/views/hearing_types/new.html.erb, config/locales/views.en.yml
- Add localization for hearing types pages for easier to translate later
How to embed:
=> add localization for hearing type pages

app/views/imports/_cases.html.erb, app/views/imports/_csv_error_modal.html.erb, app/views/imports/_supervisors.html.erb, app/views/imports/_volunteers.html.erb, app/views/imports/index.html.erb, config/locales/views.en.yml
- Add localization for imports' pages
How to embed:
=> add localization for imports page

app/views/judges/_form.html.erb, app/views/judges/edit.html.erb, app/views/judges/new.html.erb, config/locales/en.yml, config/locales/views.en.yml
- Add localization for judge pages
How to embed:
=> add localization for judge pages

app/views/layouts/_login_header.html.erb, app/views/layouts/_mobile_navbar.html.erb, app/views/layouts/_sidebar.html.erb, app/views/layouts/application.html.erb, app/views/layouts/footers/_not_logged_in.html.erb, config/locales/views.en.yml
- Add localization to layouts
How to embed:
=> add localization for layouts

app/views/all_casa_admins/casa_admins/_form.html.erb, app/views/all_casa_admins/casa_admins/edit.html.erb, app/views/all_casa_admins/casa_admins/new.html.erb, app/views/all_casa_admins/casa_orgs/new.html.erb, app/views/all_casa_admins/casa_orgs/show.html.erb, app/views/casa_orgs/edit.html.erb, app/views/supervisors/edit.html.erb, app/views/supervisors/new.html.erb, app/views/volunteers/edit.html.erb, app/views/volunteers/new.html.erb
Related to #1257
See the commit descriptions for details. Each description has the command which was used to do this with GNU sed.
=> Use localization for buttons/links

app/views/imports/_volunteers.html.erb, config/locales/views.en.yml
Resolves #1698
added: "note: This will email the new volunteers asking them to log in!"
I have not yet learned how to write tests.
How to embed:
`![alt text](https://media.giphy.com/media/DffShiJ47fPqM/giphy.gif)`
=> Volunteer import note

app/views/imports/_volunteers.html.erb, config/locales/views.en.yml
Resolves #1698
Added <strong><%=t(".instruction.note") %></strong> in app/views/imports/_volunteers.html.erb
Still learning to write tests. 
How to embed:
`![alt text](https://media.giphy.com/media/u4EQe6mJf0nTXe3dOx/giphy.gif)`
=> added note to the last instruction bullet under #2.Upload your CSV file

spec/factories/casa_case.rb
Resolves #2044
Added trait `:with_case_contacts` for casa case factory
Won't affect.
It is to be used with tests, but you can test in the rails console with the command: `create(:casa_case, :with_case_contacts)`
=> Adds trait :with_case_contacts

.github/labeler.yml
Resolves #1307, @compwron  or @FireLemons, please assign issue to me before merge, but also this needs a label set up with name `erb` in order to work.
Added section to labeler.yml to auto-label PRs for easier review.
Tested manually.
PR shown is just an ERB change. Also was tested on PRs with multiple files.
=> Issue #1307 Fix - Needs 1 more step on admin side.

.github/ISSUE_TEMPLATE/Problem validation, README.md
I created a new file to submit: problem validation because I thought we were lacking that type of file.
=> Create Problem validation

app/views/devise/mailer/reset_password_instructions.html.erb, app/views/layouts/mailer.html.erb
Not a complete fix but related to https://github.com/rubyforgood/casa/issues/2089
=> Fix email alt text

.gitignore, README.md, package.json, yarn.lock
Created table of contents for README. Added tooling to generate it
No impact
no logic added
How to embed:
=> Create readme table of contents

app/views/layouts/mailer.html.erb
Resolves #2107
- Refactor inline styles into one `<style>` tag in the head of `app/views/layouts/mailer.html.erb`
N/A
N/A
=> Refactor inline styles in mailer layout file

app/views/case_contacts/_form.html.erb
Resolves #2102
- Changed inline styles to bootstrap style classes
N/A
N/A
=> Refactor inline css out of case_contacts/_form

public/404.html
Resolves #2164 
Changed 404 page to look a bit more like CASA.
It will not.
Just type a wrong address.
=> Adds 404 page

README.md
=> add sparkle

app/views/volunteers/index.html.erb, config/locales/views.en.yml
Resolves #2109
Refactor English text in /config/locales/views.en.yml for localization support of app/views/volunteers/index.html.erb
How to embed:
=> Localization support index volunteer

.github/workflows/codeql-analysis.yml, .github/workflows/cypress.yml, .github/workflows/erb_lint.yml, .github/workflows/factory_bot_lint.yml, .github/workflows/rspec.yml, .github/workflows/ruby_lint.yml, .github/workflows/security.yml, .github/workflows/yarn_lint.yml
Resolves #2060 
Skip unnecessary automatic workflows for docs and `*.md` files
None affected
On forked [repo](https://github.com/r-sierra/casa/commits/main)
How to embed:
=> [2060] Skip GitHub Actions on READMEs and docs 

app/views/casa_admin_mailer/account_setup.html.erb, app/views/casa_admin_mailer/deactivation.html.erb, app/views/layouts/mailer.html.erb
Moved css from style tag back to inline to support more email platforms
=> revert styles to use inline for emails

app/views/reports/index.html.erb
=> Changed export data page title

bin/git_hooks/lint, bin/git_hooks/logger, bin/git_hooks/update-branch, bin/git_hooks/update-dependencies
Colorized output for git hooks
=> Color hooks

bin/git_hooks/lint
=> removed duplicate variable in git hook script

bin/git_hooks/lint, bin/git_hooks/update-branch, bin/git_hooks/update-dependencies
- Changed non env variables to lowercase
=> Lowercase non environment variable names ofr git hook scripts

README.md
Resolves #1617 
Mainly this pull-request updates the setup instructions to the current basic situation for Chrome/Chromedriver.  I'm not sure that will fully resolve #1617, but is a step toward it.
This is currently a draft pull-request to get feedback.
Updating the README.md's Chrome/Chromedriver section with current setup information
MacOS only:
- completely uninstall Casa
- reinstall following README.md setup instructions
- run `bin/rails spec` and `yarn test`
- all tests pass
Pseudo screenshots.. :-)
```
bin/rails spec
...
Finished in 4 minutes 44.7 seconds (files took 4.28 seconds to load)
1268 examples, 0 failures, 2 pending
```
```
yarn test
...
yarn run v1.22.10
$ standard && jest
PASS …
```
=> Update Chrome/Chromedriver instructions in README.md

app/javascript/src/stylesheets/shared/sidebar.scss
removed min height rule for sidebar
Volunteer  
Admin  
All admin
=> min-height doesn't seem to be doing anything anymore

README.md
- fewer words
- removed sections no one would search for
- moved org links to under "About" title
- "How casa works" section more reflective of data schema
=> Readme improvement part 1

app/views/casa_admin_mailer/account_setup.html.erb, app/views/casa_admin_mailer/deactivation.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/layouts/mailer.html.erb
=> close style tags

app/views/devise/mailer/reset_password_instructions.html.erb, app/views/layouts/mailer.html.erb
Some email css refers to elements not present
=> Prune unused email css

lib/mailers/previews/devise_mailer_preview.rb, lib/mailers/previews/supervisor_mailer_preview.rb, lib/mailers/previews/volunteer_mailer_preview.rb
Resolves #2276
- Added Email preview.
- Devise's `unlock_instructions` & `confirmation_instructions` are features we don't use. So I have not added a preview to this pull request.
N/A
Mailer Preview tests
=> Update email preview

config/environments/development.rb
Resolves #2144 (possibly)
email previews for staging and QA
=> added previews for development environment?

config/environments/development.rb
Resolves #2144 ?
Attempt `#2` at email previews
=> attempt 2 previews in non prod envs

config/environments/development.rb
Resolves #2144
Trying to serve email previews on QA
=> Email previews for non prod envs

README.md, doc/LINUX_SETUP.md, doc/MAC_SETUP.md, lib/mailers/previews/devise_mailer_preview.rb
- Redid changes erased by rebase mistake  
- linter for ruby file
=> Readme rewrite

.rspec
=> Show rspec warnings

app/datatables/volunteer_datatable.rb, config/brakeman.ignore
Resolves #1640 
- Fix a Brakeman warning by sanitizing the sql subqueries (This changes nothing about the sql strings. It just tells Brakeman that they are safe)
N/A
Existing tests
=> Fix Brakeman warning for VolunteerDatatable

spec/support/factory_bot.rb
Resolves #2332
- Fix a failing docker test using: https://github.com/rails/rails/issues/41991#issuecomment-846947266
N/A
- Two tests use the `upload_file` method. Both are passing in docker now.
=> Fix failing docker test due to IntegrityError

db/seeds.rb, db/seeds/db_populator.rb
Resolves #2342
Add `birth_month_year_youth` attribute, for `CasaCase` examples in seed.
Just running `bin/rails db:seed:replant`
=> Add birthdate for CasaCase examples in seed

yarn.lock
this is using node 12 as specified in .nvmrc
=> Entirely regenerate yarn.lock

README.md
Resolves  #2432 
Common Issues section changed
Install imagemagick to see images locally. Instructions: https://imagemagick.org/script/download.php
- Volunteer permissions: na
- Supervisor permissions: na
- Admin permissions: na
How to embed:
=> #2432 add imagemagick instructions to README

app/models/casa_admin.rb, app/models/supervisor.rb, app/models/user.rb, app/models/volunteer.rb, db/migrate/20210913142024_set_display_name_as_not_nullable.rb, db/schema.rb
Resolves #2500
User#display_name field was made not null
None affected
No tests, sorry
How to embed:
=> Set User#display_name as not nullable

db/seeds/db_populator.rb
Resolves #2469
- `db/seeds/db_populator.rb`
- In order to add court_date and related data when seeding the database
- No permissions will change
- `bin/rails db:seed` in local environment
=> Add seed data for court_dates and court_date related fields in casa_cases

app/views/volunteers/index.html.erb
Improves solution for #2552
Addes suggestion made by @compwron  :)
=> Improves getting active supervisors

app/datatables/application_datatable.rb, app/datatables/volunteer_datatable.rb, config/brakeman.ignore
Resolves #1641
Sanitize string for order clause
No permissions affected
Brakeman no longer issues the warning
How to embed:
=> Fix Brakeman SQL injection warning for ApplicationDatatable

package.json, yarn.lock
Whoops, this breaks docker setup.
=> Revert "Bump webpack-dev-server from 3.11.2 to 4.2.1"

app/views/all_casa_admins/sessions/new.html.erb, app/views/devise/invitations/edit.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/sessions/new.html.erb
You can't submit a password/login form when one of the inputs is blank
Manually
`gh pr checkout 2593`
=> Required login and password fields

README.md, app/views/layouts/mailer.html.erb
- Fix readme badge naming
- Remove broken logo from supervisor weekly mailer
=> 2089 remove supervisor email header image

app/models/case_court_report.rb
Resolves #2602
Sort ascendant the Court Dates 
I tried to write a test but case_court_report just beat me and couldn't figure out how to 😞
=> Sort Case Court's Contact Dates

app/services/case_contacts_contact_dates.rb, app/services/court_report_format_contact_date.rb
follow-up to https://github.com/rubyforgood/casa/pull/2626 which was a follow-up to https://github.com/rubyforgood/casa/pull/2607
=> refactor CaseContactsContactDates

yarn.lock
sorry y'all, I know its a pain but it needs doing
=> regenerate yarn.lock

config/database.yml
Allow customizing of Postgres port
=> Allow customizing postgres port

db/seeds.rb
Resolves https://github.com/rubyforgood/casa/issues/2440
Improve seeds, making setup easier
=> Create all_casa_admin(admin1@example.com) with seeds

app/javascript/src/dashboard.js, config/locales/views.en.yml
Resolves #2618
The javascript function that handles the table filter was changed to also filter based on the case number prefix
=> Fix case prefix filter

Gemfile.lock, app/javascript/src/stylesheets/shared/layout.scss
Resolves #2354 
I added a more specific CSS selector to eliminate unintended spacing in the menu. 
Verified in UI.
My first ever pull request.  😬
=> 2354 Fix "pick displayed columns" spacing issue after supervisor choice

doc/MAC_SETUP.md
The Mac instructions were a bit thin, so I took a minute to expand to cover all the basic applications.  
n/a
Documentation only.
=> Expanded tool installation for macs

app/javascript/src/dashboard.js
Resolves #2624
Added mobile labels to volunteers table.
n/a
There didn't appear to be automated tests to extend for this, so it was manually tested. But it looks like #2684 suggests a lot of work is needed in this area, so it probably belongs in that process anyway.
=> Improve mobile UI for volunteers table

README.md
=> [ci skip] Fix typographical errors in README

app/controllers/case_court_reports_controller.rb, app/controllers/concerns/accessible.rb, app/helpers/template_helper.rb, db/migrate/20200329050100_create_casa_cases.rb, db/migrate/20200329062155_devise_create_users.rb, db/migrate/20200329064203_add_role_to_user.rb, db/migrate/20200329071025_change_casa_case_teen_to_required.rb, db/migrate/20200329071327_change_casa_case_number_to_required.rb, db/migrate/20200329071626_add_unique_index_on_case_case_number.rb, db/migrate/20200329074655_create_supervisor_volunteers.rb, db/migrate/20200329081206_create_case_assignments.rb
None
I am getting lint errors on my PRs, so I ran `bundle exec standardrb --fix` on main
N/A
N/A
How to embed:
=> Lint fixes

bin/git_hooks/lint
Resolves #2854
Add factorybot lint to lint script
made a factory invalid and ran the script
A failing run:
A regular run:
=> Add factorybot lint to lint script

app/views/mileage_rates/_form.html.erb
=> Added USD indicator to mileage rate form field.

app/views/case_contacts/_form.html.erb
This is similar to the prior update to checkbox HTML.  There was only one form affected.
=> Standardized Bootstrap 4 html for radio buttons.

lib/mailers/previews/casa_admin_mailer_preview.rb, lib/mailers/previews/devise_mailer_preview.rb, lib/mailers/previews/supervisor_mailer_preview.rb, lib/mailers/previews/volunteer_mailer_preview.rb
Resolves #2809
Prevent loading a record with a different id than given in the query params.
- Volunteer permissions: No changes
- Supervisor permissions: No changes
- Admin permissions: No changes
=> Fix email previews

config/locales/views.en.yml
=> wrapped reserved words in quotes

.github/workflows/add-help-wanted-labels.yml
Resolves #2634
- Throttle large number of requests
- Fix debug max page value
=> bump bot version

Gemfile, Gemfile.lock
BugsnagAPP  7:54 PM
Event in qa from casa in config/environment.rb:5 (details)
Unhandled error
LoadError: cannot load such file -- net/pop
Location
config/environment.rb:5 - <top (required)>
=> Add gem to fix qa but the build was green whats up with that??

Gemfile, Gemfile.lock, config/boot.rb
=> Remove bootsnap, the thing that needs pop

Gemfile, Gemfile.lock
=> add imap to fix qa

package.json, yarn.lock
=> Revert "Bump faker from 5.5.3 to 6.6.6"

config/initializers/bugsnag.rb
Add current user info to bugsnag events when it is available because it is more useful than IP
=> Add current user info to bugsnag events

app/views/volunteers/index.html.erb
=> Nonexistant translation

.github/workflows/add-labels-based-on-column.yml
Fixed bot hanging on column with no issues
=> fix bot hanging on empty column

.github/workflows/add-labels-based-on-column.yml
Updated js dependencies for bot
=> update labeling bot

.github/workflows/add-labels-based-on-column.yml
Changed version number because it points to a bad commit
=> fix invalid bot version

.github/workflows/remove-label-based-on-column.yml
=> enable manual runs

.github/workflows/remove-label-based-on-column.yml
=> fix version number

.github/ISSUE_TEMPLATE/config.yml
This doesn't resolve anything. All it does is add some more emojis into the issue template, you know, becase we always need more emojis.
=> Added some emojis to the different types of issues. 

.github/workflows/after-deploy.yml
Bot to move QA cards to Done after a deploy
Nope
=> Create After deploy workflow

.github/workflows/after-deploy.yml
Change time of script to run every day 1AM CST
=> change after deploy script time

app/views/court_dates/_form.html.erb, config/environments/test.rb, config/locales/views.en.yml
Resolves #3230
Enables the config option in the test environment only to raise an error for missing translations. 
For example, if I add `t('.umm')` to a view (and the key `umm` doesn't exist), rspec now fails with a helpful "missing translation error":
Once this option was enabled, there were 132 rspec failures due to missing translations that were resolved.
No new tests since only a rails-default config option was added.
I had to work through 132 missing translation errors. Most of these were "silent" errors. If rails can't find a translation, it'll fall back on a default translation, for example `no_court_dates` just becomes "No Court Dates" which is what was wanted anyway. Here are screenshots of the …
=> Raise error in rspec for missing translations

Gemfile, Gemfile.lock
=> add rexml for pdfs to deploy to heroku I guess

app/mailers/fund_request_mailer.rb
=> still send fund email even if pdf fails

.github/workflows/after-deploy.yml
Bot auto archives done cards if there are more than 16
no
=> upgrade bot and auto archive done issues

package.json, yarn.lock
=> Revert "Bump @fortawesome/fontawesome-free from 5.15.4 to 6.1.1"

.github/workflows/after-deploy.yml
added some print statements to see why archiving is broken
=> change to debug version

.github/workflows/after-deploy.yml
Change debug prints to see archive request responses
=> remove recent deploy check

.github/workflows/after-deploy.yml
Fixed cards not archiving in done column
=> fix cards not archiving after deploy

package.json, yarn.lock
=> Revert "Bump jest from 27.5.1 to 28.0.1"

app/views/casa_cases/_court_dates.html.erb, app/views/casa_cases/show.html.erb
Resolves #3214 
Remove N+1 queries, refactor code
None affected
Not yet!
=> CasaCaseController#show improve speed

README.md
None
Typo
No
No
No
How to embed:
=> fixed typo in readMe

README.md
None
Pulled installed CASA step to the top of the readme
NO
No
No
How to embed:
=> rearranged readme

app/views/casa_cases/show.html.erb
Resolves #3456 
This PR updates the `casa_cases/show` view to use strings, rather than pulling them from the `config/locales/views.en.yml`.
This change will not affect user permissions.
N/A: There should be no perceivable differences to test in this PR. 
N/A: There should be no perceivable differences in the UI.
What gif best describes your feeling working on this issue? 
=> Fixes #3456: Update casa_cases/show view to use strings

app/views/casa_org/_contact_types.html.erb
Resolves [32](https://github.com/rubyforgood/casa/issues/3466)
Assigned during RailsConf
- Supervisor permissions: No 
N/A
couldn't get this to run locally with docker so pull request on a prayer. :)
How to embed:
=> swap out internationalization map for contact_types.html.erb

app/views/contact_types/new.html.erb
Resolves #3478
This solves the issue above. This change will simplify the templates and make it easier to maintain the code going forward.
This will not affect permissions.
The header to the new contact type page shouldn't look any different.
How to embed:
=> Railsconf 44 Issue: Change title to actual text in contact type new view

app/views/casa_org/_hearing_types.html.erb, config/locales/views.en.yml
Resolves #3480 
The app will never be translated to other languages so this is no longer needed.
It also removes translations from the dictionary file.
It won't. 
Manually. 
Nothing at the moment.
=> Remove translations from hearing_types.html.erb partial

Gemfile.lock, app/views/contact_type_groups/_form.html.erb, config/locales/views.en.yml
=> update contact_type_group form

app/views/case_assignments/index.html.erb
This is a draft I have failing test
Resolves #3463
- Removed the t("") from the file and replaced it with text found in yml file. 
- This Translation feature is no longer being used.
Not tested
How to embed:
=> Task/railsconf 29 update t in index.html.erb

app/views/all_casa_admins/casa_orgs/new.html.erb
Resolves #23
Substituted actual translations for calls to t() in new.html.erb
Does not affect user permissions
=> added translations for messages in new.html.erb

app/views/casa_cases/_filter.html.erb
Resolves #3446
update t() in app/views/casa_cases/_filter.html.erb
=> Replace instances of t(STRING) to its translation to simplify template

app/views/contact_type_groups/new.html.erb, config/locales/views.en.yml
Resolves #3475
remove translation from app/views/contact_type_groups/new.html.erb
n/a
ran existing specs
How to embed:
=> Railsconf 41 app/views/contact_type_groups/new.html.erb

app/views/casa_cases/_form.html.erb
Resolves #3448
Updated from function to hard-coded string
n/a
=> change from tstring to hard-coded values

app/views/case_contacts/_form.html.erb, config/locales/en.yml, config/locales/views.en.yml
=> Stop using i18n in app/views/case_contacts/_form.html.erb

app/models/case_court_report.rb
=> Add back missing key needed by court templates

app/views/case_assignments/index.html.erb
See https://github.com/rubyforgood/casa/pull/3520
This needs a test
=> Fix app/views/case_assignments/index.html.erb

app/views/all_casa_admins/casa_orgs/show.html.erb
=> Remove translations from all_casa_admins/casa_orgs/show.html.erb

app/views/casa_cases/_other_duties.html.erb
=> Remove translations from _other_duties.html.erb

app/views/case_contacts/new.html.erb
Resolves #3492
replaced t('.title') with hardcoded 'New Case Contact' string
How to embed:
=> replaced t('.title') with hardcoded 'New Case Contact' string

app/views/casa_cases/_form.html.erb, app/views/casa_cases/edit.html.erb
=> fix manage volunteers extending into sidebar

app/views/case_contacts/index.html.erb
=> Remove translations from case_contacts/index.html.erb

app/views/case_contacts/edit.html.erb
Resolves #3490 
Resolves #3469 
Remove translation usage on view
=> issue #3490: Railsconf 55: update t() in app/views/case_contacts/edit.html.erb

app/views/case_contacts/_confirm_note_content_dialog.html.erb
Resolves #3486 
Resolves #3465 
=> Issue #3486: Railsconf 51: update t() in app/views/case_contacts/_confirm_note_content_dialog.html.erb

app/views/case_contacts/_followup.html.erb
Resolves #3488 
Resolves #3467 
=> Replace translation usage with plain text

app/views/casa_cases/new.html.erb
=> Issue #3455: Railsconf 17: update t() in app/views/casa_cases/new.html.erb

app/views/all_casa_admins/casa_admins/_form.html.erb
=> Issue #3435: Railsconf 21: update t() in app/views/all_casa_admins/casa_admins/_form.html.erb

app/views/case_contacts/_contact_types.html.erb
=> Issue #3487: Railsconf 52: update t() in app/views/case_contacts/_contact_types.html.erb

app/controllers/case_contacts_controller.rb
Resolves #3559
I formatted the date string on case contact confirmation notices to be more human readable.
I'm not sure how to test this! :/
Some tests failed but they were failing before I made my change. Please let me know if I need to do anything else!
How to embed:
=> Improve readability in case contact update confirmation

.github/workflows/yarn_lint_and_test.yml
Make js pull request workflow trigger for more files that could possibly affect js execution
=> Add json and yarn.lock to js pr check

app/views/casa_cases/_other_duties.html.erb
Resolves #3589
Refactored the new and edit links for duties to make maintaining the code easier.
n/a
Before:
After:
If anything needs to change, please let me know.
=> Refactored the new and edit links for duties - update t() in app/views/casa_cases/_other_duties.html.erb

.github/workflows/rspec.yml
Resolves #3639 
Removed judge_spec.rb from rspec.yml file- was not removed before PR #3321 
How to embed:
=> Remove judge_spec.rb from line 78 in rspec.yml file

app/policies/checklist_item_policy.rb
n/a
Refactored the checklist item policy.
n/a
I ran tests and tested it in localhost.
=> Refactored checklist item policy

app/controllers/checklist_items_controller.rb, app/policies/hearing_type_policy.rb
Did a small code refactor.
n/a
I ran tests and tested it in localhost.
=> Added policy scope for hearing types

app/views/imports/index.html.erb
=> Remove translations

doc/MAC_SETUP.md
Resolves #3634 
I have added some rough draft ideas that need work
no test yet
How to embed: so so
=> Created extra space. [#3634]

app/views/case_contacts/_form.html.erb
=> remove italics from notes field

Gemfile.lock, db/seeds/db_populator.rb
=> fixed judges not seeding locally

app/views/other_duties/index.html.erb
=> Add an empty state message to the other duties view

config/environments/development.rb
Fixed css not being hot reloaded in development environments
=> fixed css not hot reloading in development environments

README.md, doc/MAC_SETUP.md
None.
I updated the mac setup instructions to match what it took to run this project from scratch on my mac. I updated the readme to remove "help wanted" from the link to the mac section
No unit tests, but I did run through these instructions on my own machine and had a friend repeat the process
See markdown preview :) No UI changes.
How to embed:
=> Update mac setup instructions

app/javascript/all_casa_admin.js, app/javascript/application.js
Fixed js errors from conflicting jquery import
Before
After
=> fix jquery import conflict for all casa admin

app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/async_notifier.js, app/javascript/src/case_emancipation.js, app/javascript/src/type_checker.js
Moved type checking to functions in a module
Limited some scripts to running only on certain pages
Nope
=> DRY type checking in js

docker-compose.yml
Added platform to web image to allow for development on M1 devices.
The platform is the same as in github workflows.
No changes.
Tested locally using docker scripts.
How to embed:
=> Add platform arch for docker

app/policies/application_policy.rb
=> add policy method for volunteer same org

app/views/reimbursements/_table.html.erb, app/views/reimbursements/index.html.erb
Resolves #2XXX
no
insufficiently
http://localhost:3000/reimbursements
=> Change columns shown for reimbursement UI

doc/MAC_SETUP.md
Update MAC_SETUP for Ruby version 3.1.2
=> Update MAC_SETUP for Ruby version 3.1.2

doc/MAC_SETUP.md
On the MAC_SETUP instructions, I updated the Ruby version (3.1.0) to match the one on the .ruby-version: (3.1.2)
=> updated Ruby version from  3.1.0 to  3.1.2

app/views/mileage_rates/index.html.erb
Resolves #3936
Removed localization.
Not required.
=> removed localization

app/views/mileage_rates/_form.html.erb
Resolves #3935 
Removed localizations in mileage rates
spec/system/mileage_rates/mileage_rates_spec.rb
=> removed localization in mileage rates form

app/views/learning_hours/show.html.erb
Resolves #3934
Updated lines 12-16 to remove localization.
No tests to run for these changes.
=> Remove localization

app/datatables/volunteer_datatable.rb
Remove puts in volunteer datatable, because , when I run rspec, it is showing object in console.
=> remove puts in volunteer datatable

app/views/casa_admins/index.html.erb, app/views/casa_cases/show.html.erb, spec/support/webmock.rb
Resolves #3919 
..... I don't know why it has pulled in my other commit. I checked and it is also in my pervious PR. :( 
hardcoded words from config/locales/views.en.yml
N/A
How to embed:
=> 3919 remove casa casa show translations

app/views/judges/edit.html.erb
Resolves #3922
Changed page title from t() to string, per issue.
N/A
Existing tests
=> Remove Translations 6: Judges edit page

app/views/learning_hours/_form.html.erb, app/views/learning_hours/_update_form.html.erb
Resolves #3932
Updated t(STRING) instances with the proper replacement found in the views.en.yml file. This will help manage the code better going forward.
`![alt text](https://giphy.com/gifs/poorboy-poorstudio-WvHRUXYLKxTi0hpehG)`
=> updated t(STRING) instances to requested headers

app/views/layouts/_login_header.html.erb
Resolves #3924 
updated alt text to logo
How to embed:
=> Resolves 3924 Replace t() with string

app/views/judges/new.html.erb
Resolves #3923
Switched t() for the string Judge
N/A
Existing tests
=> Remove Translations 7: Judges new

app/views/layouts/footers/_not_logged_in.html.erb
Resolves #3929 
Updated  the following:
built_by: Built by
link:
report_site_issue: Report a site issue
sms_terms_and_conditions: SMS Terms & Conditions
ruby_for_good: Ruby For Good
How to embed:
=> Resolves 3929: Replace t() with string

app/views/layouts/_mobile_navbar.html.erb
Resolves #3925 
Updated:
mobile_navbar:
button:
menu: Menu
How to embed:
=> Resolves 3925 Replace t() with string

app/views/layouts/_sidebar.html.erb
Resolves #3926 
Updated:
sidebar:
footer:
location: Location
role: Role
image:
alt:
logo: CASA Logo
link:
edit_organization: Edit Organization
edit_profile: Edit Profile
export_data: Export Data
generate_court_reports: Generate Court Reports
reimbursement_queue: Reimbursement Queue
report_site_issue: Report a site issue
system_imports: System Imports
mileage_rate: Mileage Rates
menu_item:
admins: Admins
case_contacts: Case Contacts
emancipation_checklists: Emancipation Checklist(s)
learning_hours: Learning Hours
other_duties: Other Duties
supervisors: Supervisors
volunteers: Volunteers
Volunteer:
Admin:
Super:
How to embed:
`![alt …
=> Resolves 3926 Replace t() with string

lib/tasks/deployment/20221003224029_migrate_court_report_due_date_to_court_dates.rake
follow-up to https://github.com/rubyforgood/casa/pull/3963 to fix https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1664936967603269
=> Add require to fix rake after_party:run

Gemfile, Gemfile.lock, config/schedule.rb
Install whevever gem to start process of replacing heroku scheduler
=> Install whenever gem

db/seeds/db_populator.rb, lib/tasks/emancipation_checklist_reminder.rake
N/A
Use `TRANSITION_AGE` constant in a couple more places
N/A
Existing tests
N/A
How to embed:
=> Use TRANSITION_AGE constant

.erb-lint.yml, app/views/learning_hours/_confirm_note.html.erb, app/views/notes/edit.html.erb, app/views/notifications/index.html.erb, app/views/other_duties/_form.html.erb, app/views/other_duties/edit.html.erb, app/views/other_duties/new.html.erb, app/views/reimbursements/_table.html.erb, app/views/reimbursements/index.html.erb, app/views/reports/_filter.html.erb, app/views/reports/index.html.erb, app/views/supervisors/_manage_active.html.erb, app/views/supervisors/edit.html.erb, app/views/supervisors/index.html.erb, app/views/supervisors/new.html.erb, app/views/users/edit.html.erb, app/views/volunteers/_form.html.erb, app/views/volunteers/_manage_active.html.erb, app/views/volunteers/_notes.html.erb, app/views/volunteers/_send_reminder_button.html.erb, app/views/volunteers/edit.html.erb, app/views/volunteers/index.html.erb
Resolves #4042 
Translations have been replaced with strings
Should be covered by existing tests
=> remove translations in views

app/controllers/application_controller.rb, app/controllers/case_contacts_controller.rb, app/controllers/case_court_reports_controller.rb, app/helpers/report_helper.rb, app/notifications/base_notification.rb, app/notifications/followup_notification.rb, app/notifications/followup_resolved_notification.rb, app/notifications/youth_birthday_notification.rb, app/presenters/case_contact_presenter.rb
Resolves #4040
Translations have been replaced with hardcoded English strings
Existing tests should cover most of these
=> remove translations in controllers, helpers, notifications, presenters

doc/CONTRIBUTING.md
We found some typos, broken links, and opportunities to simplify the grammar.
Our aim is to help new contributors by removing potential stumbling blocks.
Should we create an issue before submitting document fixes as this PR adds?
=> Fix typos and links in CONTRIBUTING.md

config/schedule.rb, lib/tasks/demo_scheduler.rake
=> test scheduler

doc/productsense.md
I found a few misspelled words in this document. Submitting a fix
=> Fix misspellings in document

app/javascript/src/all_casa_admin/patch_notes.js
Related to ##3651
Added ability to edit a patch note
Manually
Screenshots don't really show whether editing works or not
=> All casa admins can edit a patch note

doc/architecture-decisions/0007-controller-specs.txt, doc/architecture-decisions/0008-controller-specs.txt
I want to clarify what tests we want and when
=> architecture decision around tests

config/schedule.rb, lib/tasks/demo_scheduler.rake
I don't think we made one
moved these into `config/schedule.rb`
`whenever --update-crontab` produced this locally
```
flysy@flysy-GA-78LMT-USB3-6-0:~/Projects/casa$ crontab -l
0 11 * * * /bin/bash -l -c 'cd /home/flysy/Projects/casa && RAILS_ENV=production bundle exec rake send_supervisor_digest --silent'
0 15 * * * /bin/bash -l -c 'cd /home/flysy/Projects/casa && RAILS_ENV=production bundle exec rake court_report_due_reminder --silent'
0 23 * * * /bin/bash -l -c 'cd /home/flysy/Projects/casa && RAILS_ENV=production bundle exec rake clear_passed_dates --silent'
0 23 * * * /bin/bash -l -c 'cd /home/flysy/Projects/casa && RAILS_ENV=production bundle exec rake emancipation_checklist_reminder --silent'
```
Running one such command results in this
``` …
```
=> Convert heroku scheduler jobs to whenever syntax

.github/workflows/rake-after_party.yml
Resolves #4155 
A workflow to run after_party on push and pull requests was added.
=> Issue4155 ci build to run rake after party

Procfile
as per https://help.cloud66.com/rails/how-to-guides/rack-servers/puma-rack-server.html
=> tell cloud66 to use puma like we currently do

app/services/short_url_service.rb
=> Quit breaking prod

app/views/contact_types/_form.html.erb, app/views/contact_types/new.html.erb
Resolves #4278 
Changed title for "New Case Contacts" to "New Case Contact Type" and added related description.  
No Test Yet
How to embed:
=> added Type & description to New Case Contact Type

app/views/contact_types/_form.html.erb, app/views/contact_types/new.html.erb
Resolves #4312 
(&& #4301 - I had done a previous PR to add "Type" to "New Case ContacT" as well as a description. I hope it's ok that I added those changes here as well.)
-Removed "field" and "form group" style classes from the form inputs
-Added  plainadmin class wrappers to the title, inputs, and error message
No tests yet
How to embed:
=> 4312 new theme contact types pages

app/javascript/src/reports.js, app/views/reports/_filter.html.erb, app/views/reports/index.html.erb, app/views/static/index.html.erb
Resolves #4325
The new theme was applied to the index reports page and to the filter modal.
But, I have a few questions/observations:
1. Regarding the select input
* I managed to add the placeholder using `prompt: true`, this is a bit different from how it was written before. So I'm not sure if it's a good solution.
* I also had to remove `{include_hidden: false}`, I tested and it seemed ok, but I'm not sure if this was important.
2. Regarding labels
* Should the label be equal to the table headers (from the supervisor's index)? In the tables, we have an h6 with the table header. 'Starting From' label:
3. Buttons
* What do you think? Is this ok?
* Should they all be primary blue?
* Should they have icons? If yes, which?
* I noticed hover isn't working on the primary buttons in the index, …
=> Applied new theme to reports page

app/assets/stylesheets/application.scss, app/javascript/src/select.js, app/views/case_court_reports/index.html.erb, package.json, yarn.lock
Resolves #4308
- Improve select2 component and generate button size 
- go to left menu and access Generate Court Report
=> fix select2 component and button size

app/views/other_duties/_form.html.erb, app/views/other_duties/index.html.erb
Resolves #4323
- refactory index and _form page
index:
form:
=> refactory duties page

app/views/shared/_invite_login.html.erb, app/views/shared/_manage_volunteers.html.erb, app/views/supervisors/_manage_active.html.erb, app/views/supervisors/edit.html.erb, app/views/supervisors/new.html.erb
Resolves #4326 
This PR updates the views in the `/views/supervisors` directory to use the new [plainadmin](https://plainadmin.com/) theme.
=> add new theme to supevisors view

app/views/users/_languages.html.erb, app/views/users/edit.html.erb
Resolves #4327
This PR changes the theme for user edit pages.
n/a
=> Applied new theme to user edit page.

app/views/checklist_items/_form.html.erb
I changed the style for the checklist item submit button.
n/a
If anything needs to change please let me know.
=> Adjusted the style for the submit button

app/views/other_duties/_form.html.erb
=> add icon to submit button

app/javascript/application.js, app/javascript/src/dashboard.js, app/views/shared/_edit_form.html.erb, app/views/volunteers/_form.html.erb, app/views/volunteers/_manage_active.html.erb, app/views/volunteers/_manage_cases.erb, app/views/volunteers/_manage_supervisor.erb, app/views/volunteers/_notes.html.erb, app/views/volunteers/_send_reminder_button.html.erb, app/views/volunteers/edit.html.erb, app/views/volunteers/index.html.erb, app/views/volunteers/new.html.erb
Resolves #4328
Html tags and classes changed for updating to the new theme. Reordered an import statement in `app/javascript/application.js` to eliminate a javascript error.
- Volunteer permissions: Not gonna affect.
- Supervisor permissions: Not gonna affect.
- Admin permissions: Not gonna affect.
This is tested visually. Everything looks good according to the new theme.
1. Index Page
2. Edit Page (includes changes for partials used)
3. New Volunteer Page
How to embed:
=> Issue-4328/Adds new theme to volunteers pages

app/assets/stylesheets/pages/password.scss, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
Resolves #4314 
HTML tags, HTML Classes and some CSS.
- Supervisor permissions: No
Visually.
How to embed:
=> Adds new theme to Devise pages

app/views/shared/_manage_volunteers.html.erb, app/views/supervisors/_manage_active.html.erb, app/views/supervisors/edit.html.erb, app/views/supervisors/new.html.erb
Adjust an already merged PR#4367
Added icons to the buttons and fix table style
It doesn't affect user permissions
How to embed:
=> fix unassign action style and add icons to buttons

app/controllers/reports_controller.rb
Resolves #4400
Fixed calling a method by an old name after a rename
Already tested. Waiting for a green build.
=> fix 500 on email exports

app/views/static/index.html.erb
Resolves #4330 
- Modified colors for accessibility
- Added alt image tags for accessibility
- Added h1 and landmark tags for accessibility
We probably will need to coordinate footer colors and such across the site. I made changes on this page to fix accessibility issues, but it probably doesn't match other pages now.
=> Updates to landing page for new theme

app/views/casa_cases/_court_dates.html.erb, app/views/casa_cases/_filter.html.erb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/_inactive_case.html.erb, app/views/casa_cases/_other_duties.html.erb, app/views/casa_cases/_thank_you_modal.html.erb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/casa_cases/edit.html.erb, app/views/casa_cases/index.html.erb, app/views/casa_cases/new.html.erb, app/views/casa_cases/show.html.erb, app/views/case_contacts/_contact_types.html.erb, app/views/shared/_court_order_list.erb
Resolves #4306 
The following were converted to the new theme:
- Volunteer permissions: noop
- Supervisor permissions: noop
- Admin permissions: noop
How to embed:
=> Add plainadmin theme to casa_cases pages

app/views/reimbursements/_datatable.html.erb, app/views/reimbursements/_filter_trigger.html.erb, app/views/reimbursements/_occurred_at_filter_input.html.erb, app/views/reimbursements/index.html.erb
Resolves #4324
I updated the theme for the reimbursement queue page.
n/a
Before:
After:
The date picker before:
The date picker after:
If anything needs to change please let me know.
=> Changed the theme for the reimbursement queue page

app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/plainadmin.js, app/views/all_casa_admins/casa_admins/_form.html.erb, app/views/all_casa_admins/casa_admins/edit.html.erb, app/views/all_casa_admins/casa_admins/new.html.erb, app/views/all_casa_admins/casa_orgs/new.html.erb, app/views/all_casa_admins/casa_orgs/show.html.erb, app/views/all_casa_admins/dashboard/show.html.erb, app/views/all_casa_admins/edit.html.erb, app/views/all_casa_admins/new.html.erb, app/views/all_casa_admins/patch_notes/_patch_note.html.erb, app/views/all_casa_admins/patch_notes/index.html.erb, app/views/all_casa_admins/sessions/new.html.erb, app/views/layouts/application.html.erb
Resolves #4329 
Plainadmin theme was applied
How to embed:
=> Update theme for all casa admins pages v2

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/rspec.yml, bin/asset_bundling_scripts/build_js.js
Resolves Esbuild Error!
./bin/asset_bundling_scripts/build_js.js
=> Fix esbuild backwards incompatibilty from before v17

lib/tasks/deployment/20230208031806_update_howard_court_report_temp4.rake
=> Fix lint build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- added all casa admin login
- generalized instructions for all testing environments
- added new theme QA site
=> Updated login instructions for issue templates

.github/workflows/rspec.yml
Added the html page selenium generates for each system test to the collection of saved files
Manually
=> save html pages from gh actions runs for system tests

bin/git_hooks/README.md, bin/git_hooks/update-dependencies
added yarn section to `update-dependencies` script which will run after git had altered package.json or yarn.lock
Manually
=> Add yarn to update dependencies

app/views/layouts/_sidebar.html.erb, spec/datatables/reimbursement_datatable_spec.rb
Resolves [4486](https://github.com/rubyforgood/casa/issues/4486)
- Supervisor permissions: adds a link
manually and rspec
=> Supervisors reimbursment

app/models/all_casa_admin.rb, db/migrate/20230316152808_remove_phone_number_from_all_casa_admin_resource.rb, db/schema.rb
Resolves #4652
- Volunteer permissions: X
- Supervisor permissions: X
- Admin permissions: X
How to embed:
=> 4652: Remove phone number from all_casa_admins table

db/seeds/db_populator.rb
Unique dates for mileage seeder to prevent invalid mileage rates throwing an error
Nope
=> try fix flaking seeder

doc/MAC_SETUP.md
N/A
typo in MAC setup.
N/A
How to embed:
=> fix postgresql typo

.github/PULL_REQUEST_TEMPLATE.md
Removes the "2" in `Resolves #2XXX` since we are well past issues that start with a 2.
=> Update Pull Request template to remove leading 2 for issue number

spec/factories/languages.rb
Resolves #4749 (Bug: Factorybot Lint Flake #4749)
languages.rb in spec/factories directory
It will have no issues with permissions.
How to embed:
=> factory_bot:lint issue

db/seeds.rb
=> add missing models to seeder output and alphabetize them

app/services/twilio_service.rb
=> catch twilio error

db/seeds/db_populator.rb, spec/views/casa_cases/show.html.erb_spec.rb
Resolves #4786
Add logic to seeder `db_populator.rb` that guarantees case contacts occurs before and after the most recent past court date to assist in testing reporting in development. Three methods were created to:
- retrieve the date of the most recent past court date, if one
- determine if any case contacts occur before this date
- determine if any case contacts occur after this date
Logic in the `create_cases` method then checks for a past court date and creates a new case contact before/after if none.
Using `puts` statements demonstrates the creation of these case contacts via this logic, corresponding to the UI records shown below: 
`new case contact id 615 before last court date`
`new case contact id 616 after last court date`...
In this image we have a most recent past court date …
=> Issue 4786 Guarantee case contacts before and after most recent past court date in seed data

.github/workflows/remove-label-based-on-column.yml
Try to update the config to clear the "help wanted" label on assigned issues
Manually after merge
=> try update config for clearing help wanted issue on WIP issues

.github/workflows/remove-label-based-on-column.yml
Try to update the config to clear the "help wanted" label on assigned issues
=> try update config for new github projects #2

.github/workflows/rspec.yml
=> Update postgres version in GitHub Actions to match production

.github/ISSUE_TEMPLATE/flaky_test.md
Changed the template to better suit flaky test issues
=> change section title, add instructions

app/models/mileage_rate.rb, db/migrate/20230704123327_add_foreign_key_constraints_to_mileage_rates.rb, db/schema.rb
Resolves #4935
A foreign key constraint has been added to the `mileage_rates` table
=> Issue 4935 add foreign key for casa_org_id in mileage_rates

README.md
https://rubyforgood.slack.com/archives/C04PM108S/p1688757166763019?thread_ts=1688755485.625219&cid=C04PM108S
=> fix readme link from old broken one to new one http://bit.ly/rubyforgood

app/models/note.rb, db/migrate/20230712080040_add_foreign_key_creator_id_to_note.rb, db/schema.rb
Resolves #4950
added migration to add foreign key constraint
=> Add foreign key contraint for creator_id in notes table

lib/tasks/deployment/20230720000759_update_howard_court_report_fix.rake
https://rubyforgood.slack.com/archives/G01143RQ7DG/p1689719637638889
=> overwrite howard template because upload inprod is broken on twilio

Gemfile, Gemfile.lock, spec/rails_helper.rb
https://github.com/titusfortner/webdrivers/issues/247
=> Remove webdrivers gem since selenium-webdriver is updated to 4.10

README.md
- Remove the word 'required', as it feels a bit like we don't want to acknowledge
them but we have to
- Make the image smaller
=> Modify the Acknowledgements section

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/flaky_test.md
Use headings for the Feature template, add heading for the QA info.
=> Some changes for the issue templates

package.json, yarn.lock
Resolves #5019
Added @babel/core@^7.0.0 to fix peer dependency warnings:
Previously:
```
$ yarn install --check-files
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning chart.js@4.3.0: The engine "pnpm" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning " > @babel/preset-env@7.22.9" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/helper-compilation-targets@7.22.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.22.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.2 …
```
=> Add @babel/core@^7.0.0 to fix peer dependency warning

.github/ISSUE_TEMPLATE/flaky_test.md
- Remove redundant "how to replicate" section
- Clarify Environment section
=> Update Flaky spec issue template

db/schema.rb
=> Fix db schema version

doc/LINUX_SETUP.md
Added command to turn on postgres server
=> added turn on postgres step

app/javascript/src/case_contact.js, app/javascript/src/dashboard.js
Fixed some js console errors
Manually
local
qa
=> Fix js errors

app/views/case_contacts/index.html.erb
Resolves #4957
Added styling to the `div` that contains the `New Case Content` button to fix its alignment.
- Admin permissions: no effect
Tested in browser since it's only a UI change.
=> Closes #4957 - Bug: 'New Case Contact' button alignment

app/javascript/src/add_to_calendar_button.js, app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/all_casa_admin/tables.js, app/javascript/src/casa_case.js, app/javascript/src/casa_org.js, app/javascript/src/case_contact.js, app/javascript/src/case_contact_autosave.js, app/javascript/src/case_emancipation.js, app/javascript/src/dashboard.js, app/javascript/src/display_app_metric.js, app/javascript/src/emancipations.js, app/javascript/src/import.js, app/javascript/src/new_casa_case.js, app/javascript/src/password_confirmation.js, app/javascript/src/plainadmin.js, app/javascript/src/reimbursements.js, app/javascript/src/require_communication_preference.js, app/javascript/src/select.js, app/javascript/src/sidebar.js, app/javascript/src/sms_reactivation_toggle.js, app/javascript/src/tooltip.js
updated some old jQuery deprecated methods
=> fix deprecation warnings

config/environments/production.rb
=> add verbose logs to QA

config/environments/production.rb
=> revert verbose QA logs

app/models/placement.rb, db/migrate/20230903182657_add_foreign_key_casa_case_to_placement.rb, db/schema.rb
Resolves #4977 
Update placements table with foreign key casa case
- Volunteer permissions: na
- Supervisor permissions: na
- Admin permissions: na
How to embed:
=> Add foreign key constraint to placements table

app/views/case_contacts/_form.html.erb
Made case contact from `required` client side
Too simple to test
How to embed:
=> Require Contact Medium on the Case Contact Form

app/views/case_contacts/_form.html.erb, app/views/volunteers/index.html.erb
Revert required medium type for no contact made on case contact form
removed "Responsive Data Table" text from volunteer table
=> Revert required medium type for no contact made on case contact form

db/seeds/db_populator.rb
Resolves [5221](https://github.com/rubyforgood/casa/issues/5221)
- updated the logic to generate a random value between 0.00-1.00
- that's the requirement
- This is in seeds.
- NA
What gif best describes your feelings working on this issue? https://giphy.com/
How to embed:
=> updated the amount in mileage rate while creating in the seed.

Procfile.dev, docker-compose.yml, docker-entrypoint.sh
Resolves #5283 
Updates some of the docker configurations to allow for assets to continue being watched during development. The current problem was that when running inside the Docker, a new build is necessary every time an asset is updated.
Running Docker, making a change to an asset and refreshing the browser to see changes registered.
How to embed:
=> Update docker configurations

.github/ISSUE_TEMPLATE/feature_request.md
Added discord link for office hours
=> add discord link for office hours

app/javascript/src/type_checker.js
- Fixed `checkNonEmptyString` calling the wrong function causing an infinite loop
=> fixed function calling itself infinitely

app/services/followup_export_csv_service.rb, lib/tasks/deployment/20230822145532_populate_api_tokens.rake
Resolves #5313 
More explicit about what we want done. Fixes validation.
How to embed:
=> 5313 Bug: Deployment Failed

app/views/layouts/application.html.erb
=> remove debug render

app/javascript/src/case_contact_autosave.js
Replaced 2 boolean checks with one
=> Minor js performance increase

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/flaky_test.md, .github/ISSUE_TEMPLATE/problem_validation.md, README.md, doc/CONTRIBUTING.md
Resolves #5293 
Updated the README.
n/a
Double check the link and make sure you get a valid slack invitation.
=> Update slack invitation URL

.github/labeler.yml
Updated the filetype labeler config to be compatible with the new filetype labeler version
=> Try update config to match new labeler version

lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake
Attempting to see the Case Contact that is causing the validation error
How to embed:
=> Case contact rake task bug

lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1708887684994399?thread_ts=1708887232.591939&cid=CVB0QJGVD
=> let rake task succeed

scripts/import_casa_case_date_of_birth.rb
This refactor doesnt have any issues attached, I was just browsing the files for something to refactor and decided on cleaning up the script a little bit. 
There were no logic or behavior changes, only some cleanup on the code. It was a refactor so no changes to any expectations.
it wont.
From my understanding this is a script that gets run manually with real prod data of which i have no access to. Since there were no changes to funcionalities I believe there is no need for new tests
Sure :D
=> Jd refactor import case date script

scripts/import_casa_case_date_of_birth.rb
fix lint after merging https://github.com/rubyforgood/casa/pull/5577
=> standardrb --fix

app/controllers/application_controller.rb
=> Case contact form fix for referrer

app/controllers/case_contacts/form_controller.rb
=> fix prod more? 

.github/workflows/docker.yml, app/controllers/case_contacts/form_controller.rb, app/views/case_contacts/form/expenses.html.erb, app/views/learning_hours/_learning_hours_table.html.erb
Fixes a couple of failings CI tests. 
One failure was date based edge case. 
The other seems related to weirdly nested erb.
=> fix: failing CI tests

scripts/generate_github_issues_for_missing_spec.rb
This generated issues at https://github.com/rubyforgood/casa/issues?q=is%3Aissue+is%3Aopen+%22Fix+or+remove+xit-ignored+test%22
=> script to generate github issues using gh-cli

.github/PULL_REQUEST_TEMPLATE.md
=> tuning the PR template to be more explanatory and simpler

README.md, bin/lint, bin/setup, bin/update
Updates bin/setup to include full setup
Updates bin/update to include yarn assets
Create bin/lint to run all linters
Updates README with new commands
Resolves #4088
=> feat: update bin scripts

.github/workflows/combine_and_report.yml, .github/workflows/rspec_parallel.yml
If statements were incorrect on main branch, updated with corrections (was not passing secrets in when they were needed).
Additionally, remove code climate from parallel tests, it does not work correctly. Needs investigation. The uploads are unique on a per commit SHA basis meaning if one parallel runner submits then no other submissions can be made under the same SHA.
Works off main https://github.com/rubyforgood/casa/pull/5730/checks and forks https://github.com/rubyforgood/casa/pull/5740/checks
Edit: Merging this because a bunch of open dependabot PRs look like they are failing on main because of the secret issues.
=> feat: more parallel test changes

.github/CODEOWNERS
N/A
Who gets add as a reviewer
How to embed:_
=> Updating Code Owners

.github/workflows/ci.yml, .github/workflows/combine_and_report.yml, .github/workflows/docker.yml, .github/workflows/rspec_parallel.yml, .rspec_parallel
This adds verbose logging to a bunch of places in hopes that maybe we can get to the bottom of why timeouts are occurring in both the parallel CI and docker.
=> testing parallel CI with debugging

README.md, config/environments/development.rb
#5801 Added integration with Github Codespaces, it was a bit rushed to allow use at the RubyforGood 2024 event. 
This PR makes the adds mention to the Readme that the project supports codespaces.
=> Unveil codespaces

gemset.nix
=> feat: update nix gemset

app/components/form/submit_button_component.html.erb, app/components/form/submit_button_component.rb, app/views/case_contacts/form/details.html.erb, app/views/case_contacts/form/expenses.html.erb
Resolves #5819 
Refactor the rest of the form to use the same component and a minor stylistic nit
How to embed:_
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif …
=> Refactor volunteer case contact form to use new submit button component

.github/CODEOWNERS
Removing myself from CODEOWNERS for the time being since I haven't been that active in reviewing code recently.
=> Remove littleforest from codeowners

db/seeds/db_populator.rb
Resolves #5862
Currently, all case contacts are marked as draft by [the seeder](https://github.com/rubyforgood/casa/blob/main/db/seeds/db_populator.rb).
For each case make most of its case contacts completed and leave between 0 and 1 draft for each.
This pr is for the db seeder.
How to embed:_
=> Change the types of case contacts that are created by the seeder

lib/tasks/emancipation_checklist_reminder.rake
typo in the rake task was cause the cron job to not run.
=> fix: reminder service typo

.github/workflows/docker.yml
DB setup includes seeding of database which we don't need to do in your github actions tests.
=> fix: swap db:reset to db:setup

package.json, yarn.lock
=> Revert "build(deps): bump sass from 1.77.6 to 1.79.3"

db/seeds.rb, db/seeds/db_populator.rb
Refactored create_org to not call other functions and moved into a separate function called create_org_related_data out into SeederMain. Also refactored what should be a public function and what should be a private function in db_populator. 
Ran "bundle exec rails db:reset" to verify that the output is still the same as before 
`![alt text](https://giphy.com/gifs/season-17-the-simpsons-17x10-xT5LMHxhOfscxPfIfm)`
=> refactor create_org

doc/MAC_SETUP.md
fix newlines missing from markdown
=> Fix markdown formatting for postgres troubleshooting MAC_SETUP.md

app/controllers/users/passwords_controller.rb
https://app.bugsnag.com/ruby-for-good/casa/errors/65c96d515ff67f00092d7e7b?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production
=> fix: NoMethodError users/passwords#create

Gemfile, Gemfile.lock, app/views/layouts/_all_casa_admin_sidebar.html.erb, config/routes.rb, db/schema.rb
Resolves [#6161](https://github.com/rubyforgood/casa/issues/6161)
- Added pghero and pg_query Gem.
- Added routes for redirection of pg_dashboard and integrated for UI admin.
- This is new feature implementation for monitoring database.
- This has been tested locally on UI. Will be posting screen recording on testing for UI interface.💪_
- Configured to postgres db on local before [configuration](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md)
https://github.com/user-attachments/assets/28d8c9e7-9f1d-48c0-aa67-3ede33c7635a
=> feat: added pg_hero and authentication for all_casa_admin user

Dockerfile
Upgraded the npm version.
changed inside the Dockerfile for npm upgrade.
It has been tested locally using npm version. Attaching snapshot for it.
How to embed:_
=> [#6432] upgraded the npm version to 11.4.2

Gemfile, Gemfile.lock
Resolves #6428
add more scout logging
=> bundle add scout_apm_logging
