README.md, app/models/user.rb, config/locales/devise.en.yml, doc/architecture-decisions/0001-record-architecture-decisions.md, doc/architecture-decisions/0002-disallow-ui-sign-ups
Resolves #35 
- #35 turn off ability to create your own account
- remove devise 'registerable' functionality from user model
=> Remove sign up option

app/views/layouts/application.html.erb, config/initializers/devise.rb
Resolves #36 
There was no logout link, we added a logout link for when you are logged in and a login link for when you are logged out as part of the layout.
=> Displays login and logout links that work

config/webpacker.yml
Changed check_yarn_integrity to false to avoid the yard error we were getting on setup:
`error @rails/webpacker@4.2.2: The engine "yarn" is incompatible with this module. Expected version ">=1.0.0".
error Found incompatible module`
=> Disable check_yarn_integrity to avoid yarn error

app/assets/stylesheets/application.scss, app/assets/stylesheets/casa_cases.scss, app/models/casa_case.rb, app/models/user.rb, app/views/casa_cases/show.html.erb, spec/models/user_spec.rb, spec/spec_helper.rb
Resolves #48 
Shows details for casa_case show path, including case_contacts nested by volunteer.
Test added for method only returning case_contacts for the given volunteer and casa_case and not case_contacts for any other volunteer associated with that casa_case
=> show casa case admin view

app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb
Resolves #79 
Placed "Log in" and "Log out" links that were at the bottom of the pages into the Navbar similar to that shown in the [mockup](https://github.com/rubyforgood/casa/wiki) in the wiki 
* UI update (non-breaking change )
no impact
Minor change of HTML and CSS classes so checked visually
Ran RSpec, all tests passed
No new tests because changes were minor 
Mockup in Wiki for "Log in"/"Log out" buttons in Navbar example:
--------------------------------
Log in before:
--------------------------------
Log in after:
--------------------------------
Log out before:
--------------------------------
Logout after:
=> Put Login / Logout links at bottom of page into Navbar as Buttons

app/assets/stylesheets/navbar.scss, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, spec/helpers/application_helper_spec.rb
Resolves #083
Adds a link to user's dashboard on the page header when user is logged in.
Added two other helpers in the application helper for the session links and edit_profile_link to remove the conditionals from the application.html.erb
no impact
I added a helper spec to test the new application helper methods.
=> Fixes [#83] Add link to dashboard from page header

app/policies/casa_case_policy.rb, app/views/dashboard/show.html.erb, spec/policies/casa_case_policy_spec.rb
This commit also disallows the volunteer from creating new cases
themselves. Instead, only admins should (currently) have that ability.
Display volunteer's active cases in dashboard
This commit also disallows the volunteer from creating new cases
themselves. Instead, only admins should (currently) have that ability.
<!-- Please outline how each level of user permissions will be affected by this change. 
(If user permissions will not be impacted by this change, please say "no impact") 
This removes volunteers' ability to create cases and allows admins to create cases.
Automated tests and confirmed in browser.
=> Display volunteer's active cases in dashboard

app/controllers/case_contacts_controller.rb, app/helpers/case_contacts_helper.rb, app/models/case_contact.rb, app/values/case_contact_parameters.rb, app/views/casa_cases/show.html.erb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/index.html.erb, app/views/case_contacts/show.html.erb, app/views/dashboard/show.html.erb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/models/case_contact_spec.rb
Resolves #88
I ended up implementing the first recommended solution and added two drop down menus: one for duration_minutes and one for duration hours. I then added a new method to the existing CaseContactParameters to calculate the duration_minutes when the form is submitted on update and create.
I also added a new case_contact model method for displaying duration_minutes as hours + minutes. This should probably be moved to a decorator if we add that into the project, but I wasn't sure what the teams thoughts were on draper or other options, so I just left it in the model for now.
I also moved the select_tag generation code into two helper methods in the helpers/case_contacts_helper.rb file.
No impact. 
I've updated the rspec …
=> Adds Hour & Minutes Input for Case Contacts

CONTRIBUTING.md
We discovered that access restrictions prevents people from assigning issues to themselves. Instead of taking on the burden of managing access for each contributor, it makes sense to just ask them to comment on the issue saying they are working on it. It also changes the issue URL to remove the no assignee filter.
=> Updates contributing guidelines again

app/decorators/user_decorator.rb, app/javascript/packs/dashboard.js, app/views/dashboard/_volunteer_filters.html.erb, app/views/dashboard/show.html.erb
Resolves #111
- Adds new decorator function to display if a volunteer is assigned
- Adds new filter using that column to hide/show volunteers accordingly
I wasn't sure how to exactly display the column and it may be a bit long (see screenshot). Maybe someone with domain expertise can shorten the phrase or we can just leave it as is if the team thinks it's fine.
No impact.
All current RSpec tests pass and local testing
=> Adds transition aged youth filter to dashboard

app/views/dashboard/show.html.erb
Resolves #124 
Removed the `new case contact` button from the Admin Dashboard from `show.html.erb` in the dashboard views. 
It does not. 
No new tests were required and this changes passes all existing test.
=> Removed the new casa contact on Admin dashboard

app/assets/stylesheets/navbar.scss, app/views/casa_cases/index.html.erb, app/views/casa_cases/show.html.erb, app/views/casa_orgs/index.html.erb, app/views/casa_orgs/show.html.erb, app/views/case_assignments/index.html.erb, app/views/case_assignments/show.html.erb, app/views/case_contacts/index.html.erb, app/views/case_contacts/show.html.erb, app/views/layouts/application.html.erb, app/views/supervisor_volunteers/index.html.erb, app/views/supervisor_volunteers/show.html.erb
Resolves #130
- Removes duplicates flash notices and adds basic styles using colors from the style guide.
No impact
Local testing and all current Rspec tests pass.
=> Removes duplicated notices and adds notice styles

app/assets/stylesheets/dashboard.scss, app/assets/stylesheets/navbar.scss, app/controllers/reports_controller.rb, app/controllers/supervisor_volunteers_controller.rb, app/helpers/application_helper.rb, app/models/case_contact.rb, app/policies/dashboard_policy.rb, app/views/dashboard/show.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/reports/index.html.erb, config/routes.rb, spec/helpers/application_helper_spec.rb, spec/models/case_contact_spec.rb, spec/requests/reports_spec.rb
Resolves #122
This PR:
- Adds new reports controller to list and download reports
- Changes header nav to a dropdown which gives edit profile and reports links
Alternate Implementations:
I wasn't sure of the best way to show a link to the reports page. I ended up replacing the "Edit Profile" button with a dropdown that includes a link to "Edit Profile" and the new reports page.
Two other possibilities I considered were adding buttons on the dashboard next to "New Case Contact" labeled something like "Export Case Contacts", but it sounded like we might have different kinds of reports moving forward that wouldn't fit so easily into single buttons on the dashboard. I also considered adding a fourth section to the dashboard page listing reports similar to the reports#index in the current PR, …
=> Adds All Case Contacts Report

.rubocop.yml, app/assets/stylesheets/casa_cases.scss, app/controllers/casa_cases_controller.rb, app/javascript/packs/application.js, app/javascript/packs/show_casa_case.js, app/policies/casa_case_policy.rb, app/policies/case_contact_policy.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/edit.html.erb, app/views/casa_cases/index.html.erb, app/views/casa_cases/new.html.erb, app/views/casa_cases/show.html.erb, app/views/case_contacts/index.html.erb, app/views/dashboard/show.html.erb, spec/policies/casa_case_policy/casa_case_policy_spec.rb, spec/policies/case_contact_policy/case_contact_policy_spec.rb, spec/requests/casa_cases_spec.rb
Resolves #108
Resolves #153 
Resolved #95 
- Updates CasaCasePolicy permissions to block volunteers from certain actions
- Adds basic bootstrap styles to all casa case and case contact views
- Adds Rspec tests for CaseContactPolicy
This PR has lots of permission changes for casa_cases. Breaking it down by action:
1) casa_case#index
accessible by all but only shows cases scoped by CasaCasePolicy
2) casa_case#show
accessible by supervisor/casa_admin or volunteer assigned to case
3) casa_case#edit
accessible by supervisor/casa_admin or volunteer assigned to case
4) casa_case#new
only accessible by supervisor/casa_admin
5) casa_case#create
only accessible by supervisor/casa_admin
6) casa_case#update
only accessible by supervisor/casa_admin …
=> Updates Casa Case Pundit Policies and Styles

app/assets/stylesheets/application.scss
Updates for #114 
This fixes the Mixed content error being thrown by Heroku:
`
Mixed Content: The page at 'https://casa-r4g-staging.herokuapp.com/reports' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Montserrat:400,700'. This request has been blocked; the content must be served over HTTPS.
`
No Impact
=> Use https when importing google fonts

spec/features/admin_adds_new_case_spec.rb
Resolves #52 
Removed `login_in admin` from `admin_new_case_spec.rb`. 
All tests passed before the branch was created. 
After the edits, all tests pass.
=> Removed duplication testing of log_in admin in admin_new_case_spec.rb

Gemfile, Gemfile.lock, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, config/environments/development.rb
The current reset password forms from Devise have no styles. This gives them basic bootstrap styles, and sets up the letter_opener gem for easy email testing in development mode.
No Impact.
Local testing
=> Add password reset form styles

config/initializers/bugsnag.rb
To prevent development errors popping up in the Slack channel and for security reasons, I changed the hardcoded API key to an ENV variable.
No Impact
Local testing
=> Convert bugsnag API key to ENV variable

app/controllers/volunteers_controller.rb, app/values/volunteer_parameters.rb, app/views/volunteers/_form.html.erb
Resolved #44 
The new volunteer form currently hangs on submission. It looks like this is because the form is being submitted as JS instead of HTML and so the controller is not able to redirect the user back to the dashboard. This PR fixes that by setting remote to false for the form. It also does minor refactoring on the volunteers controller.
No Impact, admins can still create volunteers.
Local testing
=> Fix New Volunteer Form Hanging on Submit

app/javascript/packs/dashboard.js, app/views/dashboard/_volunteer_filters.html.erb
Resolves #194 
This PR leverages the jquery datatables savestate feature to keep filtered columns and search terms saved across page reloads using browser localstorage. There's also a new javascript function to check the appropriate boxes in the "Pick Displayed Column" modal if state has been saved.
No impact.
Local testing
=> Saves datatable state on page reload

app/decorators/user_decorator.rb, app/views/dashboard/_admin_dashboard.html.erb, app/views/dashboard/_volunteer_filters.html.erb
Resolves #191 
Resolved #190 
This PR fixes a bug where we were iterating over the supervisor_volunteer join table instead of users with the supervisor role giving us lots of duplication. It also changes supervisor column value from email to display_name.
No impact.
Local testing
=> Fixes repeated supervisor filter on volunteer table

app/views/devise/mailer/reset_password_instructions.html.erb
Contributes to #125 
Adds basic styles for password reset email. No logos or special fonts added in this PR.
No Impact
Local testing
=> Adds basic password reset styles

.travis.yml
Resolves #184 
This change runs `brakeman` scanner against the repo. Brakeman is a security scanner tool. This PR just adds running the tool with default configuration. There might be more work that we can do to improve this.
Not applicable
* Ran brakeman locally to make sure runtime was not too slow
Not screenshot but you can see the report in Travis CI's [console output](https://travis-ci.com/github/rubyforgood/casa/builds/162257732#L636-L740)
=> [WIP] Run brakeman on CI

app/assets/stylesheets/navbar.scss, app/views/layouts/application.html.erb
Adds a little more top spacing after recent changes removing flash alerts.
Before:
After:
=> Adds more page content spacing

app/controllers/case_assignments_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/volunteers_controller.rb, app/helpers/application_helper.rb, app/views/dashboard/_admin_dashboard.html.erb, app/views/volunteers/edit.html.erb, config/routes.rb, spec/features/admin_views_dashboard_spec.rb, spec/requests/case_assignments_spec.rb, spec/requests/users_spec.rb, spec/requests/volunteers_spec.rb
Resolves #5 
Resolved #203 
Replaces the case assignments page with an edit volunteer page that includes the relevant editable volunteer fields.
Admins can now edit a volunteer's name, email, and active/inactive status.
Rspec tests have been added.
=> Adds edit volunteer page for admins

app/controllers/dashboard_controller.rb, app/models/case_contact.rb, app/models/case_contact_report.rb, spec/requests/volunteers_spec.rb
Resolves #181
This commit adds newly added fields to the case contacts report, e.g. contact_medium, user/supervisor names, and created_at. It also refactors the report generation code to all be inside the CaseContactReport class.
No impact
Local testing
=> Adds new fields to case contacts report

app/assets/stylesheets/casa_cases.scss, app/javascript/packs/dashboard.js, app/javascript/packs/show_casa_case.js, app/views/casa_cases/show.html.erb
Resolves #205 
Resolves #192 
This commit reorganizes the casa case detail view to put all case contacts in one jquery datatable. Also adds volunteer names as links in the Assigned Volunteer sections.
No Impact
Local testing and all existing tests pass
=> Adds full contacts table to casa_case#show

app/decorators/case_contact_decorator.rb, app/javascript/packs/new_casa_contact.js, app/models/case_contact.rb, app/models/case_contact_report.rb, app/values/case_contact_parameters.rb, app/views/casa_cases/show.html.erb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/index.html.erb, app/views/case_contacts/show.html.erb, app/views/dashboard/_volunteer_dashboard.html.erb, db/migrate/20200422180727_replace_contact_type_with_contact_types_on_case_contact.rb, db/schema.rb, db/seeds.rb, spec/decorators/case_contact_decorator_spec.rb, spec/factories/case_contact.rb, spec/features/volunteer_adds_a_case_contact_spec.rb, spec/models/case_contact_spec.rb, spec/requests/case_contacts_spec.rb
**Nice to have but not necessary before merge**
**Zoe should add as followup issues**
----
Moved `contact_type` from string to array of strings.
Resolves https://github.com/rubyforgood/casa/issues/119
New feature (non-breaking change which adds functionality)
*Warning* This change assumes there is no data that can be lost.
user permissions will not be impacted by this change - "no impact"
As a Volunteer, create a new Case Contact.
When all other parts of the form are completed validly,
Selecting 1 or more `Contact Types` should successfully submit the form.
Selecting no `Contact Type` should be a form validation error.
*FIXME ADD THESE*
=> Change contact_type  to contact_types

app/controllers/reports_controller.rb, app/decorators/case_contact_decorator.rb, app/models/case_contact.rb, app/models/case_contact_report.rb, db/migrate/20200422180727_replace_contact_type_with_contact_types_on_case_contact.rb, spec/decorators/case_contact_decorator_spec.rb, spec/decorators/user_decorator_spec.rb, spec/models/case_contact_report_spec.rb
Initially, the case_contact_report was supposed to have one column for each possible contact_type, e.g. `... type: supervisor, type: therapist, type: youth ...`. This commit adds one `contact_types` column for now to fix a bug where the headers do not align with the row data. It also adds a test to check the number of header columns matches the number of columns in the row data.
This PR also autocorrects some rubocop warnings and removes two deprecated methods in the CaseContact method.
No impact
New tests have been added.
=> Simplify case contact report headers with new contact_types

app/assets/stylesheets/application.scss, app/assets/stylesheets/login.scss, app/assets/stylesheets/shared/flashes.scss, app/assets/stylesheets/shared/layout.scss, app/assets/stylesheets/shared/navbar.scss, app/assets/stylesheets/shared/utilities.scss, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb
This PR adds more styles to the login page, specifically a large image on desktop to fill the empty space. The image at the moment is a placeholder while we wait for high-res images from the CASA organization.
No Impact
Local testing
=> Adds more styles for the login page

app/views/dashboard/_admin_dashboard.html.erb, spec/factories/casa_case.rb, spec/factories/user.rb, spec/features/admin_views_dashboard_spec.rb
Resolves #206
* Make each case clickable as described in #206
* Create associations in factory _after_ the dependent model is saved (otherwise the ID may be `nil`)
* Remove 'loop' in factory: previously `create(:user, :with_casa_cases)` would create 2 `case_assignment` models, which would each create a `casa_case` which would each create another `user`. Effectively calls to `create(:user)` were creating 3 users, instead of 1. If a future test would like a `casa_case` to come with an assignment, maybe it could be added as a `trait` instead?
Via rspec feature specs and locally
=> Make case numbers clickable in volunteer view

app/assets/stylesheets/shared/navbar.scss, app/views/layouts/_header.html.erb
Resolves #213
Web design is not where I have a ton of experience, so if something doesn't seem to make sense here, definitely let me know and I'll be happy to adjust.
* Attempt to simplify the navbar a bit by reducing nesting. Most of the ideas here came from the [Bootstrap navbar docs](https://getbootstrap.com/docs/4.4/components/navbar/)
* Add CASA logo to navbar, following guidance in #213
Manually, Chrome web inspector
=> Add CASA logo to navbar

app/views/volunteers/edit.html.erb, spec/rails_helper.rb, spec/system/admin_edit_volunteer_spec.rb
Resolves #228
I took the most direct path to implement this feature: I added an `onclick` attribute to the "Inactive" radio button. The error message is basically what was described in the issue. There is no existing javascript code in the app assets, so I did not wire this to any javascript events.
Additional thoughts:
- The issue requested the dialog box show up when "Submit" is clicked. That would be a little more complicated than what I did, but practically speaking, this should be the same thing.
- If UI Javascript is added later (for things along these lines) the `onclick` should be extracted from here and put into one of those files
- If the user has JS disabled, they will not see this message; that is the only difference, practically. The radio button would function normally.
- …
=> Add confirm for deactivation of volunteer

app/controllers/application_controller.rb, app/controllers/volunteers_controller.rb, app/policies/volunteer_policy.rb, app/views/volunteers/edit.html.erb, spec/policies/volunteer_policy_spec.rb
Resolves #260 
This gives supervisors the ability to edit all volunteer fields except their email address.
- Supervisors can now edit volunteers
Tests have been updated with new policies.
=> Supervisors can edit all volunteer fields except email

.rubocop.yml, app/policies/dashboard_policy.rb, spec/policies/dashboard_policy_spec.rb
Resolves #251
This PR adds a check that a volunteer has at least one assigned case before showing the create new case contact button.
Rspec tests have been updated.
=> Hide new case contact button if volunteer has no assigned cases

Gemfile, Gemfile.lock, app/assets/stylesheets/form.scss
N/A
This PR pins the `sprockets-rails` gem to v2.3.3. This seems to fix an issue where an error was thrown when using a scss variable.
```
ActionView::Template::Error:
Error: Undefined variable: "$red".
on line 9:25 of app/assets/stylesheets/form.scss
>>       border: 1px solid $red;
```
Solution found in [stack overflow question comment](https://stackoverflow.com/questions/54070093/error-undefined-variable-alert-padding-y).
This change fixes tests that broke due to https://github.com/rubyforgood/casa/pull/269
N/A
=> Pin sprockets-rails to v2.3.3

.travis.yml, app/controllers/case_assignments_controller.rb, app/javascript/packs/application.js, app/views/casa_cases/edit.html.erb, app/views/volunteers/edit.html.erb, config/routes.rb, package.json, spec/factories/user.rb, spec/features/admin_views_dashboard_spec.rb, spec/requests/case_assignments_spec.rb, yarn.lock
Resolves #90 
This PR gives admins the ability to assign and unassign volunteers on the existing edit_casa_case view.
Only admins can access the new page
New tests have been added and local testing
=> Allow admins to edit assigned volunteers on edit casa_case page

app/policies/casa_case_policy.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/casa_cases/edit.html.erb, spec/policies/casa_case_policy/casa_case_policy_spec.rb, spec/views/casa_cases/edit.html.erb_spec.rb
Resolves #293 
This PR adds a new Pundit policy method to hide the volunteer assignment section from the edit casa case page.  
- Volunteer assignment is now hidden for volunteers.
New policy specs and view specs have been added.
=> Remove volunteer assignment from edit casa_case view for volunteers

app/assets/stylesheets/pages/login.scss
Uses Rails asset path to display login page image on Heroku
=> Fix login image asset path for Heroku environment

app/views/layouts/mailer.html.erb, app/views/volunteer_mailer/deactivation.html.erb, config/application.rb, lib/mailers/previews/volunteer_mailer_preview.rb
Resolves #201 
Updates layouts/mailer with better default template for system emails. Styles are still a little rough, especially in the footer, so this will probably need another pass down the road after review from CASA stakeholders.
No effect.
This PR sets up ActionMailer previews, so emails can be previewed in the browser.
=> Adds default email layout and actionmailer previews

app/views/dashboard/_volunteers_table.html.erb, spec/factories/case_contact.rb, spec/factories/user.rb, spec/features/admin_views_dashboard_spec.rb
Resolves #265
Updated volunteer table in the dashboard so that the Last Contact Made is a link to the case for that contact.
It will not affect user permissions
Test was added to verify that link is visible and clicking it takes the user to the cases view.
1. #265 asks for the addition of this column with the title "Last Case contact". Since the column already exists as "Last Contact Made", I left the name of the column as is. Please let me know if the column name should be changed.
2. Is there a better way to do the link? I mostly work on JSON APIs and don't do a lot of views in Rails. If there is a better way to do the link, please let me know.
Note the link in the bottom left corner from hovering over the last contact date.
Page viewed when clicking on link. Note id of the case in the …
=> Adds link for most recent contact in volunteer table

app/models/case_contact.rb, app/values/case_contact_parameters.rb, app/views/case_contacts/_form.html.erb, db/migrate/20200525220759_add_driving_fields_to_case_contact.rb, db/schema.rb, spec/factories/case_contact.rb, spec/models/case_contact_spec.rb
Resolves #24 
Two fields are added to `CaseContact`:
- `miles_driven`
- `want_driving_reimbursement`
Does not affect permissions
Specs and exercised functionality
**Cannot ask for reimbursement when no miles driven**
**Cannot ask for reimbursement when zero miles driven**
**Case contacts saved, one with miles and reimbursement, one without**
Data
```sql
casa_development=# select occurred_at, duration_minutes, contact_made, medium_type, contact_types, miles_driven, want_driving_reimbursement from case_contacts order by id desc limit 2;
occurred_at     | duration_minutes | contact_made | medium_type | contact_types | miles_driven | want_driving_reimbursement 
---------------------+------------------+--------------+-------------+---------------+--------------+---------------------------- …
```
=> Issue 24: add driving fields to case contact

app/controllers/volunteers_controller.rb, app/mailers/volunteer_mailer.rb, app/models/user.rb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/volunteer_mailer/account_setup.html.erb, config/environments/development.rb, config/environments/test.rb, lib/mailers/previews/volunteer_mailer_preview.rb, spec/requests/volunteers_spec.rb
Resolves #125
This PR:
- Updates copy and layout on existing Devise reset password email
- Adds new `account_setup` mailer which is delivered to a volunteer when their account is created 
No effect.
New tests have been added and existing tests pass.
=> Email configuration for password reset

app/views/dashboard/_volunteers_table.html.erb, spec/features/admin_views_dashboard_spec.rb
The existing PRs are failing because of a flaky test that is trying to find specific values in the `Last Contact Made` column of the volunteer table. Even though the `strftime` calls are identical in the test and the view output, it looks like spacing is being automatically fixed in the HTML on the view side, but the same correction isn't being made in the tests.
This PR changes the relevant `strftime` calls to remove any padding in both the view and the tests.
=> Remove blank padding from date display to fix flaky test

app/models/case_contact.rb, spec/models/case_contact_spec.rb
Resolves #302
This PR updates the driving reimbursement error field.
No effect
Existing tests have been updated.
=> Edit driving reimbursement error message

app/assets/stylesheets/application.scss, app/controllers/case_contact_reports_controller.rb, app/javascript/packs/application.js, app/javascript/packs/index_reports.js, app/models/case_contact_report.rb, app/views/reports/index.html.erb, lib/mailers/previews/volunteer_mailer_preview.rb, package.json, spec/requests/case_contact_reports_spec.rb
Resolves #304
This PR adds a date range fields to the report generator page. The datepicker inputs use the bootstrap datepicker npm package. Unfortunately I was not able to use the send_data method with form submission, so I had to resort to using javascript to set the "Download Report" href attribute for now. I've left comments clarifying the unintuitive code.
No effect.
New tests have been added and existing tests pass.
=> Add date range to report generator

app/views/dashboard/_volunteers_table.html.erb
Resolves #001
changed the way volunteer names display to be a link instead of plaintext
=> added link to volunteer name on volunteer table

app/assets/stylesheets/pages/dashboard.scss, app/assets/stylesheets/shared/navbar.scss, app/views/dashboard/_admin_dashboard.html.erb, app/views/dashboard/_volunteer_filters.html.erb
Resolves #193 
This PR adds small CSS changes after web browser responsive mode testing. Specifically this updates the top nav and increases the `<body>` width on tablet views. I think the mobile CSS is now good enough to close #193 and open specific issues when we notice specific problems on native devices.
There are still some issues where there's lots of blank space on certain views, but I'm not sure if there's a good fix for that besides adding some type of filler content.
New View:
Old View:
=> Improve Mobile CSS

README.md
n/a afaik
- Remove reference to db:migrate (db:setup already handles that)
=> Remove db:migrate (already handled in db:setup)

app/controllers/case_assignments_controller.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/volunteers/edit.html.erb, config/routes.rb
Resolves #20 (Also related to number 230)
- Added unassign endpoint
- Includes redirect to volunteer if unassigning from Volunteer edit
- Added Status column to index
- Would really prefer not to have to add get and patch routes. Any advice here?
- Admin permissions: Admins can unassign (remove) a Volunteer from a CasaCase
Help, please!
=> Allow case_assignments to be unassigned

app/models/user.rb, config/locales/devise.en.yml, spec/models/user_spec.rb
If the user is inactive, display a localized error message in the flash message and do not allow them to login, nor see any pages that require authentication.
Resolves #179 
Devise has a [mechanism for determining if a user is active and refusing their login if not](https://rdoc.info/github/plataformatec/devise/master/Devise/Models/Authenticatable). This is checked at login and on every request. This PR hooks it up to our user model and inactive role model.
If a user has their role changed to inactive, they will no longer be able to login or view any content that requires authentication.
I wrote a couple of model specs. I'm open to writing a feature spec if folks think it would be valuable, as pretty much all of the underlying logic is provided by Devise.
=> Validate the user has an active role

app/controllers/volunteers_controller.rb, app/models/user.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/volunteers/edit.html.erb, config/routes.rb, spec/system/admin_edit_volunteer_spec.rb
Resolves #230: Admins can Deactivate volunteers from Volunteer Edit
Depends on casa-cases-unassign PR
- Added deactivate endpoint/route
- Add `active_volunteer` method on `user` to indicate if volunteer is active 
- Wanted a DRY approach to determining if the volunteer's current role is 'volunteer' (vs 'inactive')
- Naming this `is_active` isn't quite right bc they might be an active Supervisor, CasaAdmin, etc. Don't love calling @volunteer.active_volunteer, but, seems needed here bc of volunteer/user obfuscation
- Changed Actions column on Assigned Cases section to only show if volunteer active
- Changed "Assign Volunteer" button to secondary so there's only one primary on the page
- Conditionally displaying Add Cases section only if volunteer is active
- Change casa_case edit …
=> Casa volunteer deactivate

app/controllers/users_controller.rb, app/views/users/edit.html.erb
Resolves #325 
This changes the email form field in users#edit to render as a <p> tag
instead. It uses the form-control class so it appears as it did before.
The UsersController has had its Strong Params modified to only allow
:email as a permissible field if the current_user is a casa_admin
(role).
The Strong Params should probably be done differently, ideally as a
Pundit policy, or similar, but that was not set up for this model, and
felt out of scope.
n/a
Tested manually. Can come back and add tests if necessary (this PR was done as part of a live-stream and time didn't permit testing 😬 )
This looks identical because the `p` tag uses the `form-control` class, so it's rendered similarly to the input field.
grimacing.gif
=> Fixes #325

app/views/volunteers/edit.html.erb
=> Fix formatting on volunteer deactivate warning 

app/controllers/case_assignments_controller.rb, app/controllers/volunteers_controller.rb
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1
app/controllers/case_assignments_controller.rb
app/controllers/volunteers_controller.rb
=> removing deprecation warning: update_attributes

app/models/case_contact.rb
none
The order here 
nope
sorry
see above
=> Sort order for case contact contact types

app/views/layouts/application.html.erb
Resolves #363
CDN datepicker added (css)
=> adding datepicker CDN

app/views/layouts/application.html.erb
Resolves #387 
Styles for the whole site are adjusted. This affects ever page. The top nav bar is different as well as other content. Bootstrap 4 styles are now properly applied rather than bootstrap 4 and 3 conflicting with each other.
I clicked around a few pages, but someone who knows the app better should visually check various pages for oddities.
*Before*
*After*
=> Remove bootstrap 3 styles

app/views/case_contacts/_form.html.erb, app/views/dashboard/_volunteer_dashboard.html.erb, spec/views/case_contacts/edit.html.erb_spec.rb
Resolves #379: Volunteers can edit case contacts
- Added a link to the edit page on the volunteer contact page
- Added logic to the edit form to cycle through the list of contact types and pre-check the checkboxes for applicable values
Added case_contacts/edit is listing all the contact methods from the model to verify that the edit view is returning all the contact types for the case_contact model
💪
=> volunteers can edit case contacts

app/controllers/case_contacts_controller.rb, app/views/case_contacts/_case_contact.html.erb
Related to #406
The volunteer dashboard showed edit links for case contacts that were created by other volunteers assigned to case before. It also did not check the policy on whether they are authorized. This hides the edit button for case contacts current user is not allowed to edit. If they try to guess edit path of another case contact, this prevents displaying the message, routes them to the root path with a helpful message explaining why.
- Volunteer permissions: Volunteers will no longer be able to edit case contacts created by other volunteers. This is good.
- Supervisor permissions: No change
- Admin permissions: No change
It was tested visually but I can write tests for it in a separate PR.
Paired over zoom with @Zrrrpy & @compwron so have seen how this looks.
=> Checks user is authorized to edit case contact

app/controllers/supervisor_volunteers_controller.rb, app/views/supervisors/edit.html.erb, spec/requests/supervisor_volunteers_spec.rb
A follow up to #400, which addressed #362.  
As per discussion in #400 (see [this comment](https://github.com/rubyforgood/casa/pull/400#pullrequestreview-442779204)), this makes two improvements to unassigning a volunteer:
1. It limits this ability to supervisors and admins
2. It removes the requirement that the supervisor's ID be passed in as a parameter.
See this comment: 
- Volunteer permissions: a volunteer cannot unassign a volunteer from a supervisor
- Supervisor permissions: no change
- Admin permissions: no change
Unit tests
Exercised
Database record showing relationship between volunteer bradfordbogan@example.org and supervisor mrs.franecki.rachell@example.com
```sql
casa_development=# select u.email as volunteer_email, su.email as supervisor_email from users u join …
```
=> Unassign volunteer cleanup

app/views/case_contacts/_case_contact.html.erb
Resolves #406 
In the volunteer dashboard, we could see the link to edit profile for previous volunteers assigned to the case in the case contacts section. While clicking on that link brought you right back, it's better to not provide a link in the first place. This change checks if the current user has permissions to edit the contact creator and only them provides the edit link. For all other cases, it just shows the display name of the contact creator.
No impact
Visually. I looked at what existed in terms of tests and it looked daunting. Maybe we can pair in the near future on how to improve test coverage.
=> Removes edit link for previous volunteer

app/views/supervisors/edit.html.erb, spec/features/user_views_supervisor_edit_spec.rb
Resolves #377 and #378 
Addressed #378 by accident before realizing the issue even existed. Can break https://github.com/rubyforgood/casa/pull/416/commits/8444ab2736df16c57db63418fd6472265c634505 (which address #378) out into a separate PR if desired.
Conditionally display the Submit button in the supervisor edit form. Only display it if the current user can update supervisor email or update supervisor name
- Volunteer permissions: No effect
- Supervisor permissions: No effect
- Admin permissions: No effect
Tests were added to verify whether or not the Submit button is present.
1. Just checking for a button with "Submit" on it seems a little brittle. I'm not very familiar with the tests that verify HTML. Is there a better check? I'm happy to update
2. I also wondered if these should be …
=> Issue 377 remove submit button on supervisor

app/controllers/dashboard_controller.rb, app/models/user.rb, app/policies/dashboard_policy.rb, app/views/dashboard/_admin_dashboard.html.erb, app/views/dashboard/_supervisors_table.html.erb, spec/factories/user.rb, spec/features/admin_views_dashboard_spec.rb, spec/models/user_spec.rb, spec/policies/dashboard_policy_spec.rb
Resolves #360 
Added to the dashboard a table showing all supervisors, visible only for admins
- Admin permissions: added dashboard policy to allow admin to see supervisors
The dashboard is pretty big now! You really have to scroll to reach the supervisors table.
Tests written
Supervisors table is only visible to admins. These screenshots show the views for an admin, a supervisor and a volunteer
When logged in as casa_admin1@example.org, the supervisors are visible in a table at the bottom of the (very long) page. Note the hover in the bottom left showing the target for the Edit link.
When logged in as supervisor1@example.com, the user does not see the supervisors table below the cases.
When logged in as …
=> Issue 360 add supervisor view to admin dashboard

app/views/dashboard/_volunteer_filters.html.erb
Resolves #374
The value now includes two emoji. Since we test for an exact match, the `data-value` needs to be updated as well.
N/A
By default, the only volunteers that should be filtered out on the initial page load are those that are inactive. I verified this is the case again.
=> Fix filtering on "Assigned to Transition Aged Youth" column

app/views/dashboard/_supervisors_table.html.erb, spec/features/admin_views_dashboard_spec.rb
Resolves #424 
On the Supervisors section in the admin dashboard, the supervisor's name is changed to be a link that points to the supervisor edit page.
Added test to check that clicking the supervisor's name takes the user to the supervisor edit page
=> Issue 424 - Makes supervisor name a link in admin dashboard

app/controllers/case_contacts_controller.rb, app/models/casa_case.rb, app/values/case_contact_parameters.rb, app/views/casa_cases/show.html.erb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/edit.html.erb, app/views/case_contacts/new.html.erb, app/views/case_contacts/show.html.erb, spec/features/admin_adds_a_case_contact_spec.rb, spec/requests/case_contacts_spec.rb, spec/views/case_contacts/edit.html.erb_spec.rb
Resolves #426
Resolves #393
* Make sure all models in CaseContactsController run through Pundit for authorization.
* Allow CaseContactsController#new to accept URL params to specify which cases to display as checkboxes. Otherwise, admins and supervisors would see an unweildy list as they can create contacts for any case.
* Create 'New Case Contact' button on case details page as described in #393.
* Inadvertently fix #426 along the way: no longer reset `creator` for updates.
As far as I know, no permissions are changed (no policies were changed), but we do enforce them more consistently in CaseContactsController.
There's a new feature spec, and I updated several request and view specs along the way.
=> Allow admins and supervisors to create case contacts

app/decorators/casa_case_decorator.rb, app/views/casa_cases/show.html.erb
Resolves #435 
Add Transition Aged Youth emoji to Volunteer page(to h1 title)
N/A But passed all old tests
=> 435 Add Transition Aged Youth emoji to Volunteer page

app/controllers/case_assignments_controller.rb, app/models/case_assignment.rb, spec/models/case_assignment_spec.rb
Resolves #340 
In #340, it is reported that a case can be assigned to a Supervisor. I could not find a way to do this without either hacking the form using browser developer tools or changing the select box to include supervisors. Regardless, it was not prevented server-side, so the issue makes sense.
This PR adds a validation on case assignments to prevent any assignment to anything other than an active volunteer. Additionally, it adds a flash notification (where there was not one previously) to confirm the action when an assignment is made. See screenshots for examples.
New spec file added for case_assignment model.
=> Require case assignments to be to active volunteers

app/views/case_contacts/_form.html.erb, spec/views/case_contacts/edit.html.erb_spec.rb, spec/views/case_contacts/new.html.erb_spec.rb
Resolves #408 
The form template for a case contact now checks if the "occurred at" value is present and uses that for the "Occurred at" form field value. This change was made because the form template is used in both the "new" and "edit" forms and caused an overwrite when editing an existing case contact since it was always setting it to the current time. This unintended update was then reflected in the table row display. 
* Added test to check that when editing an existing case contact, the "occurred at" form field was set to the occurred time when present.
* Added test to check that when creating a new case contact, the "occurred at" form field was set to the current time. 
When updating:
After updating:
What gif …
=> Issue 408 -  Sets the "occurred at" field value as the occurred time when editing contact case

app/controllers/volunteers_controller.rb, app/views/volunteers/edit.html.erb, config/routes.rb, spec/system/admin_edit_volunteer_spec.rb
Resolves #353
Adds button and functionality to activate an inactive volunteer.
- Supervisor permissions: Their assigned volunteers may be reactivated
- Admin permissions: All volunteers may be reactivated
Spec included. Also tested in local environment.
=> Allow volunteers to be re-activated

app/views/dashboard/_admin_dashboard.html.erb, app/views/dashboard/_supervisor_dashboard.html.erb, app/views/dashboard/_volunteer_filters.html.erb, app/views/dashboard/show.html.erb
Resolves #429 
In our meeting today, CASA mentioned again that they wanted supervisors to see their own volunteers first. This seemed like th easiest way to build it :)
- Supervisor permissions: now default to see their own volunteers first
It is not currently tested but it should be. :(
=> Supervisor dashboard filters for their own volunteers by default

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/shared/flashes.scss, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/javascript/packs/application.js, app/views/devise/shared/_links.html.erb, app/views/layouts/application.html.erb, app/views/users/edit.html.erb, config/routes.rb, spec/system/edit_user_system_spec.rb
Add in some error helpers. Font Awesome. And a bit more.
This resolves #189 
At the core this resolves #189 allowing folks to change their password. We already have the ability for folks to reset their password if they forgot it so the work done, primarily, is for logged in folks.
A summary of stuff with pictures:
-Changed the forgot password button link on the sign-in page to a button to make it more obvious it exists:
becomes: 
Next I changed the edit profile page around a bit:
becomes:
When you click the change password button it opens up the following:
I also added in a helper method with styling for the error messages so they are not plain text and more visible. 
So, rather than doing something like this in our views:
```
<% if @user.errors.any? %>	
<div id="error_explanation"> …
```
=> Allow users to change their passwords.

app/controllers/case_contacts_controller.rb, spec/requests/case_contacts_spec.rb
Resolves #445 
When Supervisor/admin creates case contact for case, redirect to case after creation (not dashboard)
Rewritten old test
=> 445 redirect to case after creation

app/views/casa_cases/_volunteer_assignment.html.erb
Resolves #447
Supervisor can now unassign any volunteer, not just volunteers that the supervisor supervises.
- Volunteer permissions: no change
- Supervisor permissions: Supervisor can now unassign any volunteer from a case. (This is only enforced/allowed based on the logic in the view.)
- Admin permissions: no change
There are no existing tests for the editing of assignments. I did not add any as a part of this change. If feature tests for assigning and unassigning volunteers need to be written, I am not sure I can guarantee a prompt update. If this is pressing and feature tests for assigning and unassigning volunteers need to be written, please feel free to pass this issue along to another person.
Before a new volunteer is added, the supervisor can "Unassign Volunteer" for the existing …
=> Allow supervisor to unassign any volunteer, not just own

Gemfile, Gemfile.lock, app/controllers/imports_controller.rb, app/controllers/reports_controller.rb, app/models/concerns/file_importer.rb, app/models/user.rb, app/views/devise/invitations/edit.html.erb, app/views/devise/invitations/new.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/invitation_instructions.text.erb, app/views/imports/_cases.html.erb, app/views/imports/_supervisors.html.erb, app/views/imports/_volunteers.html.erb, app/views/imports/index.html.erb, app/views/layouts/_header.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise_invitable.en.yml, config/routes.rb, db/migrate/20200726185103_devise_invitable_add_to_users.rb, db/schema.rb, public/casa_cases.csv, public/supervisors.csv, public/volunteers.csv, spec/fixtures/casa_cases.csv, spec/fixtures/supervisors.csv, spec/fixtures/volunteers.csv, spec/models/file_importer_spec.rb, spec/requests/imports_request_spec.rb, spec/requests/reports_spec.rb
Resolves #18 
This PR does a bit more than the issue of just importing volunteers. I also allows the importation of supervisors and casa cases.
I added in the `devise_invitable` gem to make sending emails to new volunteers and supervisors easy. Also added in the mailcatcher gem with some configurations in `development.rb` to enable the testing of sending the emails.
The general process for importing csv's is for folks to download the example csv, edit it, and then upload it.
I also notice that while the dropdown that shows the reports link checks if the person is a casa_admin, the `reports_controller` didn't validate that the user on the page was a casa admin. I updated the controller to use the `before_action :must_be_admin` as well as updated the user in the reports request spec to be a …
=> Allow admins to import volunteers, supervisors, and cases.

app/controllers/case_contacts_controller.rb, spec/requests/case_contacts_spec.rb
Resolves #268
There's already client-side validation to make sure a user selects at least one case, but this should also be present server-side in case a browser doesn't enforce it properly.
Additionally, if a user is not assigned any cases at all, there will be no checkboxes to select, so the client-side validation may be inadvertently bypassed.
Via local development environment and a new request spec.
I waffled on introducing a higher level feature spec, but decided against it because it seemed like an edge case. I'd be happy to take in feedback about this decision though.
=> Enforce server-side that at least one case must be selected

app/controllers/casa_cases_controller.rb, app/controllers/imports_controller.rb, app/models/casa_case.rb, app/models/concerns/file_importer.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/new.html.erb, app/views/imports/_cases.html.erb, app/views/imports/_supervisors.html.erb, app/views/imports/_volunteers.html.erb, config/routes.rb, db/migrate/20200729002247_add_casa_org_to_casa_case.rb, db/schema.rb, db/seeds.rb, spec/factories/casa_case.rb, spec/models/casa_case_spec.rb, spec/models/file_importer_spec.rb, spec/requests/casa_cases_spec.rb
When I was adding in the ability for the casa to import csv files I noticed that casa_case's were not attached to a casa_org. This PR adds in a migration to do that.  Since it is a `belongs_to` this will likely break dev environments for folks. People will either need to do a drop/create/migrate/seed or jump into a console and run something like `CasaCase.update_all(casa_org_id: 1)`
All tests, forms, and whatnot have been updated to have casa_cases use the casa_org_id. Note: In the forms just set it has a hidden_field pointing at the current_user's casa_org id.
I also went and cleaned up the csv import stuff. Namely to make the routes more restful (use the create action) and to add in information about the imports. It also quickly doesn't error out now if the user forgets to attach a csv …
=> Refactor the csv import to give more information. 

app/policies/case_contact_policy.rb, app/views/case_contacts/_case_contact.html.erb, spec/policies/case_contact_policy/case_contact_policy_spec.rb
Resolves #425
Changes permissions for case contact edit page according to specs laid out in #425. This commit allows supervisors to edit case contacts as well.
- Supervisor permissions: Edit and update case contacts
Added policy specs and tested in the browser
Feeling great!!! 😎🤝
=> Add edit hyperlink on case contacts page for admins and supervisors

app/controllers/case_assignments_controller.rb, spec/requests/case_assignments_spec.rb
Resolves #457 
A bug was found where a volunteer who was unassigned from a casa case was not able to be reassigned to that casa case. This PR allows volunteers to be reassigned to casa cases by checking if the case_assigment already exists where `is_active` was set to false, then updates the existing case_assignment by setting `is_active` to true. This reassigns the volunteer to the casa case and gives the volunteer the "ASSIGNED" status in the "Assigned Volunteers" table.  
A test was added to check when trying to assign a previously assigned volunteer to a casa case, the already existing case_assigment is updated by setting`is_active` to true. 
Before reassignment:
After reassignment:
What gif best describes your …
=> Issue 457 - Allows volunteers to be reassigned to a casa case

app/views/supervisors/edit.html.erb, spec/features/admin_views_dashboard_spec.rb
Resolves #380 
The red message should display when there are no active volunteers to assign to a CASA case
Added feature test
=> Add red message when there are no active volunteers to assign to a CASA case

README.md
None
Re-ordered instructions in README to fix issues I had during setup:
* Need to install bundled gems before running rails commands.
* Tests appear to depend on webpacker being set up correctly.
It will not.
Documentation-only.  Written based on my setup experience.
Just read the instructions.  ;-)
=> Reorder setup instructions in README

app/helpers/case_contacts_helper.rb, app/models/case_contact.rb, app/views/case_contacts/_form.html.erb, spec/features/admin_edits_a_case_contact_spec.rb, spec/models/case_contact_spec.rb, spec/requests/case_contacts_spec.rb
Resolves #001
Fixed edit form for CaseContact when no values were displayed for duration_minutes and contact_made fields. And they had to be filled in again.
Also, the validation method for duration_minutes has been changed. Now you can't have zero duration_minutes.
Added models and features tests. Fix one request test.
=> Fix case contact form

app/controllers/volunteers_controller.rb, app/models/user.rb, app/policies/volunteer_policy.rb, app/views/volunteers/edit.html.erb
Resolves #441
Check the Volunteer policy for activating and deactivating users, instead of relying on view logic.
This also adds logic to the User model to consult the `VolunteerPolicy` for all `volunteer` and `inactive` users.
- Supervisor permissions: No effective change, permissions check moved to policy
- Admin permissions: No effective change, permissions check moved to policy
Existing specs and manual testing in the browser.
No visible changes
How to embed:
=> Move auth logic into pundit policyfile

app/javascript/packs/application.js, app/javascript/src/sessions.js
Resolves #451
Proposes using [the tactic suggested by @bklang of clearing all localStorage on login](https://github.com/rubyforgood/casa/issues/451#issuecomment-667559659). (/cc @cliftonmcintosh)
Prevent DataTable saved state from bleeding between sessions.
Manually. Also stepped through via a JavaScript debugger.
=> Clear localStorage on login

app/controllers/case_contacts_controller.rb, spec/features/volunteer_adds_a_case_contact_spec.rb
Resolves #464
We should use `CaseContact` model that has been validated so that the form is displayed with errors, if there are any.
Added a feature spec.
=> Render case contact form with validation errors

app/models/concerns/file_importer.rb
Resolves #486
As it stands now, it is possible to use the CSV import to set any field on a new Volunteer. This is probably not ideal for security, and it can also cause errors if a user imports the wrong kind of file (e.g., supervisors.csv when 'Import Volunteers' is selected).
I've made the logic similar for each import type: ignore any columns that aren't expected. Alternatively, we could instead fail to import any row with unexpected columns. This would better catch a case when an admin is attempting to import supervisors (e.g.) when 'Import Volunteers' is selected instead. Feedback welcomed.
I could add a test that the importer ignores invalid columns, but it felt overly specific and low value to me. …
=> Import only expected columns

app/controllers/application_controller.rb, app/controllers/case_contacts_controller.rb, app/views/casa_cases/index.html.erb, config/locales/en.yml, spec/requests/casa_cases_spec.rb
Resolves #499
* Unify authorization errors, [as suggested in Pundit's README](https://github.com/varvet/pundit#rescuing-a-denied-authorization-in-rails)
* Hide the New CASA Case button if a user is not authorized to create a CASA case
- Volunteer permissions: No policy changes. Will no longer see New CASA Case button
- Supervisor permissions: No changes
- Admin permissions: No changes
Request spec added.
=> Unify access denied handling, hide New Case button if not authorized

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb, config/initializers/devise.rb
This reverts commit 1863663194226d5a63703d668e8ade66aa48038e.
Backstory:
Currently we are banned from sendgrid for unknown reasons. I and Sean have both opened tickets to try to get this fixed. 
We have supervisor training coming up on wednesday and we would really like them to have accounts by then. 
Log into https://my.sendinblue.com/dashboard# by choosing "log in with google" and logging in as casa@ rubyforgood. Sean or I have the password. (you should not need to do this, but just in case)
See emails sent at https://app-smtp.sendinblue.com/statistics
Keep in mind that email delivery is *very* slow. On 4 August 2020 it took about 4-6 hours. On 6 August 2020 it took about 30 minutes. I guess that's what we get for free :/ 
You can see where the env variables used here are configured at: …
=> Switch back to sendinblue which works its just slooooow

app/views/devise/mailer/invitation_instructions.text.erb
Resolves #510 
invitation_instructions.text.erb should have text and not HTML. This converted to a proper text email.
=> Text mailer converted to a proper text email

app/models/case_contact.rb
Only values greater than 15 minutes were valid, but not exactly 15
=> Fix validate error when duration_minutes == 15

app/models/case_contact_report.rb, spec/models/case_contact_report_spec.rb
Resolves #418 
Updated the report so the column "Volunteer name" says "Creator name" and "Creator email"
Edited old test
=> Fix column name for creator's data in report

app/models/concerns/file_importer.rb, spec/fixtures/casa_cases.csv, spec/fixtures/supervisors.csv, spec/models/file_importer_spec.rb
Resolves #508
An error was occurring if the columns containing volunteer email addresses was empty.
Allow supervisors and cases to be imported without volunteers.
Automated tests updated!
=> Allow empty volunteer column on import

app/controllers/supervisor_volunteers_controller.rb, app/controllers/supervisors_controller.rb, app/models/user.rb, app/views/supervisors/edit.html.erb, spec/requests/supervisor_volunteers_spec.rb
Since I was the most familiar with the supervisor page I've started there.
You can see the [before](https://gist.github.com/seanmarcia/466c94732b7bca3134b40aa0ec1ab984) and [after](https://gist.github.com/seanmarcia/b2dec963bfc28c100ca22dd13f5f3857) results. Our ActiveRecord queries are about 10x faster on these pages now.
=> Performance tweaks for supervisor page.

app/controllers/imports_controller.rb, app/views/imports/index.html.erb
Resolves #504
Previously if an admin selected 'Import Supervisors' or 'Import Cases' and there was an error with the import, they'd be directed back to the imports page with 'Import Volunteers' selected. This could easily cause confusion unless they looked closely.
Now, attempt to preserve the tab that was previously selected if there's an error.
Also change the rendering to use tabs, rather than pills, which I find a bit more clear that they are selectable. But I'm happy to switch back to pills if there's feedback that pills are superior.
This is _mostly_ view logic changes, so I did not add any additional tests.
=> Keep same import tab selected on import errors

app/views/casa_cases/_volunteer_assignment.html.erb, spec/features/admin_assign_a_volunteer_to_case_spec.rb
Resolves #538
add start date and end date columns to the table that shows volunteer assignments
- Admin permissions: no effect
~~No tests! AFAICT, there are no tests for this view written yet. If we want them written as part of this PR, please say so, and we can figure out how to set up tests for this view.~~
I had originally missed the existing tests for the case assignments feature. Tests for the presence of the dates have now been added.
=> add start and end date to list of assignments

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Resolves #541 
Created config file for issue templates - this replaces the front matter for the issue-template.md files. The url can be placed int the config file specifying which template to use and any other query params that are desired.
- Volunteer permissions: na
- Supervisor permissions: na
- Admin permissions: na
na
na
=> Assign project on all new issues

app/views/casa_cases/_volunteer_assignment.html.erb, spec/features/admin_assign_a_volunteer_to_case_spec.rb
Resolves #538 
Element ids are changed to `data-test` attributes in the volunteers table that appears when editing a case.
This is a follow-up to #551. As @compwron [noted](https://github.com/rubyforgood/casa/pull/551#discussion_r471617645), element ids should be unique. When there is more than volunteer in the table, then the ids added in #551 would no longer be unique. Using a data element instead allows for identifying and accessing a column during test without breaking the rule that ids should be unique
- Admin permissions: no effect
tests updated
=> use data attribute for accessing repeated column for test

app/controllers/supervisor_volunteers_controller.rb, app/controllers/supervisors_controller.rb, app/models/supervisor_volunteer.rb, app/models/user.rb, app/views/supervisors/edit.html.erb, config/routes.rb, db/migrate/20200818220659_add_is_active_to_supervisor_volunteers.rb, db/schema.rb, spec/models/user_spec.rb, spec/requests/supervisor_volunteers_spec.rb
Resolves #449
Introduced the ability to define a supervisor_volunteer relationship as not active so that volunteers who were unassigned can appear in the list of volunteers for a supervisor.
When the volunteer is assigned to a new supervisor, this inactive relationship is removed in favor of the new active relationship.
- Volunteer permissions: no change
- Supervisor permissions: no change
- Admin permissions: no change
Tests written
Reva Marquardt originally assigned to Gloria O'Malley
Reva Marquardt unassigned from Gloria O'Malley
Reva Marquardt re-assigned to Gloria O'Malley
Database records for this relationship
```sql
-- after unassigning Reva Marquardt (user #2)
casa_development=# select * from supervisor_volunteers where volunteer_id = 2;
id | supervisor_id | volunteer_id | …
```
=> Issue 449 track non active supervisor volunteer relationships

app/controllers/volunteers_controller.rb, app/models/case_assignment.rb, app/models/user.rb, app/models/volunteer.rb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/volunteers/edit.html.erb, config/routes.rb, spec/models/volunteer_spec.rb, spec/requests/volunteers_spec.rb
Resolves #550
* Send volunteer activation and deactivation emails
* Push logic down into model
* Rely on autogenerated methods where possible
- Volunteer permissions: No changes
- Supervisor permissions: No changes
- Admin permissions: No changes
Tests added
=> Send emails when volunteers are activated and deactivated

app/controllers/dashboard_controller.rb, app/models/user.rb, app/views/dashboard/_supervisors_table.html.erb, spec/models/user_spec.rb
First PR for speeding up the dashboard -- this focuses on the supervisor table and cuts about a second from the load time. There is still the volunteer table and some tweaking on the supervisors but I wanted to get this up for @armahillo to see.
=> Supervisor dashboard performance

app/controllers/casa_cases_controller.rb, spec/requests/casa_cases_spec.rb
Resolves #572 
This PR lets users to stay on the same page after making an edit to a casa case and still be able to see the success message. The issue stated that users should remain on the same page instead of being redirected to the homepage after making an edit to the casa case.
Adds a test to check that users will remain in the edit casa case page after making an edit to a casa case.
How to embed:
=> Issue 572 - Enables users to remain on the same page after editing a casa case

DOCKER.md, spec/spec_helper.rb
These additions to the Docker doc add detail to the Chrome driver instructions and add Linux support.
=> Add to Docker VNC instructions.

config/routes.rb, spec/requests/security_meta_spec.rb, spec/system/authentication_spec.rb
Resolves #581 
* For authenticated users, set root path to be the `dashboard#show` page.
* For unauthenticated users, set root path to be the sign in page.
* When guest visits root path: "/", and when user signs out, it no longer has the "you need to sign in or sign up message" displayed.
* Added a system spec that checks root path for guest and authenticated user, verifies incorrect flash messages aren't displayed
=> Create separate root paths for authenticated, unauthenticated users

app/views/volunteers/edit.html.erb
Resolves #575 
Directs users to the casa case details page instead of the edit page when the user clicks on a casa case number anywhere on the platform. The casa case number links in the "Assigned Cases" table in the volunteer edit page was the only place I found where this was happening 👀 
How to embed:
=> Issue 575 - Directs users to details casa case page instead of edit page when clicking on casa case number

Gemfile, spec/rails_helper.rb
Resolves #621 
Removed conditional installing of webdrivers gem since it caused discrepancies in Gemfile.lock (🤦‍♀️ ). Instead, require it conditionally in the spec helper file.
Tests should pass as normal.
=> Require webdrivers conditionally #621

app/models/case_contact.rb, app/values/case_contact_parameters.rb, app/views/case_contacts/_form.html.erb, config/locales/en.yml, db/migrate/20200830011647_add_notes_to_case_contacts.rb, db/schema.rb, spec/views/case_contacts/new.html.erb_spec.rb
Resolves #600 
A new field `notes` is added to the CaseContact ActiveRecord and displays this field as a `textarea` input in the create case contact form. The placeholder text specified in the issue is added in `locales/en.yml`.
Adds a test to check that the `textarea` input for the `notes` field is display in the create case contact form.
How to embed:
=> Issue 600 - Adds notes field to CaseContact and displays field on the create case contact form

app/helpers/case_contacts_helper.rb, app/views/case_contacts/edit.html.erb, spec/helpers/case_contacts_helper_spec.rb, spec/views/case_contacts/edit.html.erb_spec.rb
Resolves #638 
The Back link was previously trying to go to a non existent show page for case contacts if you are trying to submit changes unsuccessfully.
We have removed the Show link from the Edit view.
Depending on the users role:
- if volunteer, Back link will redirect to the home page of the user.
- otherwise, Back link will redirect to case show page.
This will not affect user permissions.
Added a test for the case contact helper
Visually it looks the same, the error is handled now.
=> Fixes the Back link on case contact edit view

app/helpers/ui_helper.rb, app/views/casa_cases/new.html.erb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/new.html.erb, app/views/supervisors/new.html.erb, app/views/volunteers/_form.html.erb, app/views/volunteers/new.html.erb, spec/rails_helper.rb, spec/support/session_helper.rb, spec/views/casa_cases/new.html.erb_spec.rb, spec/views/case_contacts/new.html.erb_spec.rb, spec/views/supervisors/new.html.erb_spec.rb, spec/views/volunteers/new.html.erb_spec.rb
Resolves #635 
This satisfies the request of the issue to add "Return to Dashboard" button in place of the "Back" links.
Additionally, it:
- Creates a new helper file (`UiHelper`) that defines a `return_to_dashboard_button` helper. (This will reduce future editing should the behavior or classes need to change)
- Creates a new SessionHelper for RSpec to mediate sign-ins, and applies those to the affected specs
- Creates some new View specs to test this feature
n/a
Tests are written!
We used View specs because there were already view specs created, and TBH it would be overkill to test it with a full system test.
I also tested it manually
spin up your server and click these links:
- http://localhost:3000/casa_cases/new
- http://localhost:3000/case_contacts/new
- …
=> Adds "Return to dashboard" button

app/controllers/reports_controller.rb, spec/requests/reports_spec.rb
Ref #493 (Is there additional work?)
Changed `ReportsController` to allow supervisors to access the `reports#index`
- Supervisor permissions: Supervisors can now access Reports
We wrote tests and added an additional test to verify volunteers cannot access reports
How to embed:
=> Adds additional tests, allows supervisors to access reports

app/helpers/case_contacts_helper.rb, app/views/case_contacts/_form.html.erb, spec/helpers/case_contacts_helper_spec.rb, spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #673
a change was previously made that checked "No" for contact made if `!case_contact.contact_made`. This returns true if `contact_made` is `nil`, so it was effectively defaulting to false. Added back in code and tests that checks if the value is actually set to false. We could potentially simplify this and remove the helper, but that makes it harder to test, so I'm in favor of keeping the helper.
No
Added a system spec that validates that, if it's not selected, it doesn't get automatically selected on submit.
=> fixes bug that defaults contact made to false

app/views/all_casa_admins/sessions/new.html.erb, spec/system/authentication_spec.rb, spec/system/can_sign_in_as_all_casa_admin_spec.rb
Reused devise/sessions/new erb on the all_casa_admins/sessions/new page. 
Fixes #683
Added positive and negative sign in tests (can sign in as, can't sign in as) for all three `User` derived and the `AllCasaAdmin` user types.
=> update all casa admin sessions/new to match main login

app/policies/application_policy.rb, app/views/layouts/_header.html.erb, spec/policies/application_policy_spec.rb
added an additional if statement so that the admin and supervisor roles can see the reports in the dropdown
Resolves #493 
The supervisor needs access to the reports, but not the system imports.
view only: can now see the report in the nav dropdown.
no
How to embed:
=> 493 changed logical conditions for dropdown

app/controllers/all_casa_admins/dashboard_controller.rb, app/views/all_casa_admins/dashboard/show.html.erb, spec/system/all_casa_admins/all_casa_admin_dashboard_spec.rb, spec/system/can_sign_in_as_all_casa_admin_spec.rb
Resolves #628 
For all CASA admins, a dashboard with the list of organizations is displayed on login.
Test added.
=> Implement all CASA admin dashboard page with list of organizations.

app/models/concerns/file_importer.rb, config/routes.rb, spec/models/file_importer_spec.rb, spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #565
Error message was not displaying volunteer already assigned to a supervisor. Created a list of volunteers not updated to show in message to user.
We added tests for this use case
=> fix bug where error message not showing for supervisor imports

app/models/volunteer.rb, app/views/dashboard/_volunteers_table.html.erb, spec/models/volunteer_spec.rb, spec/system/admin_views_dashboard_spec.rb
Resolves #704 
* Added `has_supervisor?` method to volunteer that will return true if volunteer has active supervisor
* Only display email for active supervisors in Volunteers table
* Added unit tests for the new volunteer method
* Added system spec to check that unassigned supervisor email does not display
=> 704 volunteer unassigned bug

app/controllers/volunteers_controller.rb, app/models/casa_case.rb, app/models/volunteer.rb, app/views/volunteers/edit.html.erb, spec/requests/volunteers_spec.rb, spec/system/admin_edit_volunteer_spec.rb
Resolves #708 
When the volunteer form had to re-render due to an update error, the instance variables defined in the `edit` method were not available, causing errors. Instead of re-defining the instance variables in the `update` method, I moved the instance variables to methods.
Added request and system specs to test the case when a non-unique email address is used to update the form.
Will create follow-up task to prettify the error message.
=> Fix page errors caused when volunteer form re-renders due to update error

app/controllers/application_controller.rb, spec/system/user_attempts_to_load_an_unauthorized_page_spec.rb
Resolves #536
Adds a couple of high level tests that users see friendly error message when they encounter an authz error. More scenarios can be added if there are unique situations or coverage is desired.
Via system tests
=> Add tests for user redirection on authz error

app/controllers/dashboard_controller.rb, app/models/casa_org.rb, app/policies/dashboard_policy.rb, app/views/dashboard/_admin_dashboard.html.erb, app/views/dashboard/_admins_table.html.erb, spec/policies/dashboard_policy_spec.rb, spec/system/admin_views_dashboard_spec.rb
Resolves #714
Adds a small table at the bottom of the dashboard, only viewable by Admins, that lists other admins for the org.
- Volunteer permissions: n/c
- Supervisor permissions: n/c
- Admin permissions: Admins have access to view this
Added system spec and policy spec to vet it. The test checks to ensure that other-org-admins are not displayed as well as non-admin users.
=> Admins can view admins on dashboard

app/controllers/all_casa_admins_controller.rb, app/views/all_casa_admins/edit.html.erb, app/views/layouts/_header.html.erb, config/routes.rb, spec/requests/all_casa_admins_spec.rb, spec/system/all_casa_admins/edit_spec.rb
Resolves #630
* Added Edit Profile link 
* Added edit email and password view
* Added system and request specs
=> Allow all_casa_admin user to edit email/password

app/controllers/case_contacts_controller.rb, app/controllers/supervisor_volunteers_controller.rb, app/models/casa_case.rb, app/models/case_contact.rb, app/models/case_contact_report.rb, app/models/user.rb, spec/models/case_contact_report_spec.rb, spec/views/case_contacts/case_contact.html.erb_spec.rb
abstracted the filter logic in the case contact report model to make it easier to test. then added tests to the case contact report spec. successfully added one new creator filter
Resolves [#662](https://github.com/rubyforgood/casa/issues/662)
How to embed:
=> 662 add filters to case contact report

Procfile
Add `after_party:run` rake task to Procfile so it will run automatically on Heroku.
But @compwron if you are not a fan of After Party for other reasons, happy to move away from it.  I just feel like it is safer than having brittle migrations down the line.
=> Add after_party:run to Procfile

app/controllers/all_casa_admins/casa_orgs_controller.rb, app/javascript/src/stylesheets/pages/dashboard.scss, app/views/all_casa_admins/casa_orgs/new.html.erb, app/views/all_casa_admins/dashboard/show.html.erb, spec/system/all_casa_admins/all_casa_admins_casa_orgs_spec.rb
Resolves #687
Added a simple "Create CASA Organization" form to the all casa admin section of the site.
System tests on the new `new` and `create` actions.
It's bootstrap defaults 🤷
=> 687 allcasaadmin can create orgs

app/views/case_contacts/_case_contact.html.erb, spec/system/link_admin_creator_case_contact_spec.rb
or supervisor-created.
Resolves #491 
When admin-created case contact - it's linked to admin page
when supervisor-created case contact - it's linked to their own personal edit supervisor page
Added tests
How to embed:
=> Fix admin link on admin-created case contact

app/controllers/supervisor_volunteers_controller.rb, spec/policies/casa_case_policy/scope_spec.rb, spec/requests/supervisor_volunteers_spec.rb
Resolves #449 
Do not delete old supervisor-volunteer relationships when creating new ones.
Modified a spec
Only change I'm going to make on this as other related changes are getting handled in #756
=> Do not remove old supervisor-volunteer relationships

app/javascript/src/case_contact.js, app/views/case_contacts/_confirm_note_content_dialog.html.erb, app/views/case_contacts/_form.html.erb, app/views/case_contacts/edit.html.erb, app/views/case_contacts/new.html.erb, spec/system/volunteer_adds_a_case_contact_spec.rb
…urate when creating and editing a case contact.
Resolves #618 
The behavior is added when creating or editing a casa case.
When the user with permissions to add or edit a casa case clicks on 'Submit' button, if the notes field has content, we are going to ask to review that content before submitting the form. If the note field is empty, the form will be submitted.
No permissions were affected
HAVING a user login as a admin or supervisor
WHEN user go to create or edit a case contact
AND the user create or edit a case contact WITHOUT content in the note field
THEN the user should be able to create or edit the form
HAVING a user login as a admin or supervisor
WHEN user go to create or edit a case contact
AND the user create or edit a case contact WITH content in the note field
THEN the user …
=> [issue-618] Adds modal to confirm that the content of the note does not include specifics about the youth.

DOCKER.md, README.md, config/docker.env, config/environments/development.rb, docker-compose.yml
Resolves #754 
The `letter_opener` gem had been set up in April, but then the `mailcatcher` gem also got added in July. However, the mail configuration was still set up for `letter_opener` so Mailcatcher was never actually working at all. Removed all references to mailcatcher.
=> Use letter_opener instead of mailcatcher

app/views/users/edit.html.erb, spec/system/edit_user_system_spec.rb
Resolves #748
Admin user will be able to change his or her email form 'Edit Profile'.
No permissions were affected
Tests were added
How to embed:
=> [issue-748] Allows admin to edit his or her email from Edit Profile.

DOCKER.md
Don't need special instructions about copying test failure screenshots out of container since the tmp directory is not a volume for this Docker setup.
Added some more general docker-compose commands.
=> Minor documentation update for Docker

app/controllers/dashboard_controller.rb, spec/requests/dashboard_spec.rb
https://github.com/rubyforgood/casa/issues/779
Added `.sort_by(&:email)` to the @admins
Added a test to spec/requests/dashboard_spec.rb
How to embed:
=> 779 Show new admins in alphabetical order on admin dashboard

app/policies/case_contact_policy.rb, app/views/case_contacts/_case_contact.html.erb, spec/policies/case_contact_policy/case_contact_policy_spec.rb, spec/views/case_contacts/case_contact.html.erb_spec.rb
Resolves #776.
Changed the rules to edit or update a case contact according to the task description.
- Supervisor permissions: supervisors now can only see case contacts created by themselves or by creators who are supervised by them.
Added [specs](https://github.com/rubyforgood/casa/blob/2bac2d6a76140fbc2602fea21515c7de5d6f1135/spec/policies/case_contact_policy/case_contact_policy_spec.rb)
How to embed:
=> Restrict permissions to edit case contacts

app/controllers/casa_cases_controller.rb, app/javascript/src/stylesheets/pages/casa_cases.scss, app/models/casa_case.rb, app/policies/casa_case_policy.rb, app/views/casa_cases/edit.html.erb, app/views/casa_cases/new.html.erb, db/migrate/20200922144730_add_birth_month_year_youth_to_casa_cases.rb, db/schema.rb, spec/factories/casa_case.rb, spec/support/session_helper.rb, spec/views/casa_cases/edit.html.erb_spec.rb, spec/views/casa_cases/new.html.erb_spec.rb
Resolves #760
Adds a `birth_month_year_youth` datetime attribute to `casa cases` model and allow admins to select a month and year. 
- Admin permissions: Only admins can add/edit `birth_month_year_youth`
=> 760/Admin can enter Casa Case's birth month and year

app/controllers/casa_admins_controller.rb, app/models/casa_admin.rb, app/views/casa_admins/_form.html.erb, config/locales/en.yml, config/routes.rb, spec/models/casa_admin_spec.rb, spec/requests/casa_admins_spec.rb, spec/system/admin_edits_another_admin_spec.rb
Resolves #772  
Allow the deactivation of casa admin users. I've followed the same idea of the activation/deactivation of Volunteers to offer the same UX experience and keep a visual integrity.
- Admin permissions: now the admins have permission to deactivate other admins.
1. Ensure that a admin can deactivate other admins accounts;
2. Ensure that non-admin cannot deactivate admins accounts;
Automatized tests covering these cases were also added.
How to embed:
=> Deactivate casa admins

app/models/volunteer.rb, app/views/supervisors/edit.html.erb, spec/factories/supervisor_volunteer.rb, spec/models/volunteer_spec.rb, spec/views/supervisors/edit.html.erb_spec.rb
Resolves #797 
It turns out the check for displaying the `Unassign` button was incorrect and now, the button is only displayed for volunteers being currently supervised by the given supervisor.
None
1. Assign a volunteer to one supervisor.
1. Unassign that volunteer from that supervisor.
1. Assign the volunteer to a different supervisor.
1. Visit both supervisors' edit pages and note that the "Unassign" button is now **only** visible for that volunteer on the currently active supervisor page.
=> [#797] volunteer with two supervisors after re assign

app/controllers/volunteers_controller.rb
https://github.com/rubyforgood/casa/issues/751
When creating a new volunteer, use DeviseInvitable instead of VolunteerMailer to send the invitation email. This will consolidate how users are sent invitation emails.
This was tested locally in development by configuring ActionMailer to send emails via smtp through Gmail; an email was received after calling `invite!` on the volunteer object.
How to embed:
=> 751 Use DeviseInvitable for volunteer invites

app/helpers/ui_helper.rb, app/models/casa_case.rb, app/views/volunteers/edit.html.erb
https://github.com/rubyforgood/casa/issues/558
- added 2 new scopes to `CasaCase` for actively_assigned_excluding_volunteer and not_assigned
- use these 2 new scopes to build `<optgroup>`s to group cases by “Not Assigned” and “Assigned” in the “Assign a New Case” dropdown on the edit volunteer page
TODO: need to write tests for new scopes
How to embed:
=> 558 Group cases in "Assign a New Case" dropdown on the edit volunteer page

app/controllers/case_contacts_controller.rb, app/models/case_contact.rb, spec/models/case_contact_spec.rb
Resolves https://github.com/rubyforgood/casa/issues/869
Ideally, this should be fixed with a better nested association
between contact types and case contacts, but since this is a
bug I'm going with the quick and dirty solution to unblock
deployments to stagging and prod
It won't
=> Ensure contact types for a case contact can be edited

app/controllers/contact_type_groups_controller.rb, app/controllers/contact_types_controller.rb, app/models/contact_type.rb, app/models/contact_type_group.rb, app/views/casa_orgs/_contact_type_groups.html.erb, app/views/casa_orgs/_contact_types.html.erb, app/views/contact_type_groups/_form.html.erb, app/views/contact_types/_form.html.erb, db/migrate/20200925180941_add_active_to_contact_type_groups.rb, db/migrate/20200925181042_add_active_to_contact_types.rb, db/schema.rb, spec/requests/contact_type_groups_spec.rb, spec/requests/contact_type_spec.rb
Resolves #869 
Ensure it is possible to toggle the active flag of `Contact Type Groups` and `Contact Types` (covered by integration tests).
How to embed:
=> Add active flag to contact types and groups

app/controllers/concerns/organizational.rb, app/models/all_casa_admin.rb, app/models/concerns/roles.rb, app/models/user.rb, app/views/layouts/_sidebar.html.erb, spec/models/all_casa_admin_spec.rb, spec/models/casa_admin_spec.rb, spec/models/supervisor_spec.rb, spec/models/volunteer_spec.rb, spec/views/layouts/sidebar.html.erb_spec.rb
Resolves #866 
The **Role** information on the sidebar will be computed based on the current logged in user's role rather than being staticly set to `Supervisor`.
No.
1. Log into Casa as all user types;
2. Verify that the Role section of the sidebar reflects the expected role of the currently logged in user.
Logged in as `All Casa Admin` user:
Logged in as `Volunteer` user:
Logged in as `Casa Admin` user:
Logged in as `Supervisor` user:
=> [#866] Display user role on the sidebar based off of current logged in user

bin/login
Resolves #812
A `bin/login` script is added that automates the launching and logging in of users seeded in development mode.
This can make the developer workflow faster, eliminating the need for manual browser input of URL, user id, and password.
=> Add bin/login script to automate application launching and logging in

app/models/casa_case.rb, app/policies/casa_case_policy.rb, app/views/casa_cases/_form.html.erb, db/migrate/20200928233606_add_court_report_submitted_to_casa_cases.rb, db/schema.rb, spec/requests/casa_cases_spec.rb, spec/system/admin_edits_a_case_spec.rb, spec/system/supervisor_edits_case_spec.rb, spec/system/volunteer_edits_case_spec.rb
Resolves #619
* Added new `court_report_submitted` field to casa_cases table
* Added form field for `court_report_submitted` on casa cases edit page
* Added and updated system and request specs related to this change
=> Add court report submitted field to casa case form

app/policies/casa_case_policy.rb, app/views/casa_cases/_form.html.erb, spec/requests/casa_cases_spec.rb, spec/system/admin_edits_a_case_spec.rb, spec/system/supervisor_edits_case_spec.rb, spec/system/volunteer_edits_case_spec.rb
Resolves #896 
Removed the ability to change the `transition_aged_youth` flag. I still allowed the field to be used when creating the case.
=> Prohibit changing of transition_aged_youth

app/controllers/users_controller.rb, spec/system/edit_user_system_spec.rb
Resolves #902
Load Active CASA admins on update with error
Have tested manually
Added a test
=> Fix error while saving profile with invalid values as an admin 

app/javascript/src/stylesheets/shared/typography.scss
Add font-family fallback values to `option` elements.
Resolves #886 
Option elements now have a fallback `font-family` to work around a Firefox bug that prevents web fonts from being applied correctly.
For more details, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1536148#c19
None
In Firefox, navigate to the contact types creation form and verify that the dropdown uses the fallback font values since `Montserrat`, being a web-font, won't work.
On Firefox:
On Chrome:
I haven't tried "vendorizing" the `Montserrat` font, perhaps that could work? Worth trying?
How to embed:
=> Add font-family fallback for option elements

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/locales/en.yml, spec/helpers/application_helper_spec.rb, spec/views/layouts/application.html.erb_spec.rb
Resolves #539
Add meta tags:
- title and description: for browser context
- og tags: for embed previews, used by external services to collect the data that will be shown
No permission changes
Copy and paste a public URL for this application into the slack to see the link preview
Or you can use this website to see it working https://metatags.io/
Slack | Facebook | Twitter
------- | ------------- | ----------
=> #539 Meta tags to link preview

app/models/casa_case.rb, lib/tasks/scheduler.rake, spec/models/casa_case_spec.rb, spec/policies/case_contact_policy/scope_spec.rb, yarn.lock
Resolves #831 
Added a scope to check if youth is 14 and not marked as transitioned and a task to update all youth who match that criteria.
Not a user-facing change.
Added a test for the scope change.
=> Issue 831: add tasks to update transition_aged_youth when 14

app/javascript/src/stylesheets/shared/dashboard.scss, app/views/volunteers/index.html.erb
Resolves #924
Provides a new style for checkboxes on drop down menus to enlarges the box, and includes the previously used inline margin style.
N/A
Manually (if you have tests of the SCSS I can try to add something for this.
=> Added style to enlarge checkbox and removed inline.

config/application.rb, config/skylight.yml
Resolves #916
* Removed auth token from repo since repo is public
* Set the following environment variables (see [Skylight documentation](https://www.skylight.io/support/environments#for-rails-using-environment-variables)):
**staging**
```
SKYLIGHT_AUTHENTICATION:  QA1OKxp4SPmHTUWVtgDo3xyYHswM-bhbEvvxy8sRxCQ
SKYLIGHT_ENABLED:         true
SKYLIGHT_ENV:             staging
```
**qa**
```
SKYLIGHT_AUTHENTICATION:  QA1OKxp4SPmHTUWVtgDo3xyYHswM-bhbEvvxy8sRxCQ
SKYLIGHT_ENABLED:         true
SKYLIGHT_ENV:             qa
```
**production**
```
SKYLIGHT_AUTHENTICATION: QA1OKxp4SPmHTUWVtgDo3xyYHswM-bhbEvvxy8sRxCQ
SKYLIGHT_ENABLED:        true
```
(will default to "production" environment on Skylight).
For someone who has access to Skylight, please change the access token and set the new token on …
=> Set Skylight environments using environment variables

config/environments/production.rb, config/initializers/bugsnag.rb
Since all environments are using the production config file now, specifically set the release environment on Bugsnag.
https://docs.bugsnag.com/platforms/ruby/rails/configuration-options/#release_stage
=> Bugsnag environment

app/views/volunteers/index.html.erb
Resolves #953
Previously, the ability to search for volunteers by the old version of the name was added, because of this, the ability to search by the current one was lost. This has now been fixed.
=> Fix search volunteers by current name

spec/system/admin_views_volunteers_page_spec.rb
Resolves #965 
The previous version of the spec passes in Docker but fell in my local environment. At the moment, the local environment is not configured to work with js (judging by the screenshots from some other tasks, this problem is not only mine). Specifically in this case, the test does not see the table header(thead), so it has one tr less everywhere. If we count only the tr in the tbody of the table, it can help unify the tests.
=> Fix spec admin can_filter_volunteers

spec/system/supervisor_views_volunteers_page_spec.rb
Resolves #968 
Example on line 7 was failing (and ignored) due to UI rewrite: was looking for 4 active users but only created 3; 3 inactive users but only created 2; and 2 <tr> but only one is created when all users hidden.
I have 2 unrelated tests failing. These are be failing on my `master` branch too, so not sure where they're coming from.
`![It works, I guess... ?](https://iruntheinternet.com/lulzdump/images/gifs/red-and-green-power-rangers-shrug-who-cares-so-what-1381971694L.gif?id=)`
=> fix 'can filter volunteers' example in supervisor_views_volunteers

Gemfile, Gemfile.lock, app/models/casa_case.rb, spec/support/capybara.rb, spec/system/supervisor_edits_case_spec.rb
Resolves #954 
- Add capybara-screenshot gem to help debug capybara specs
- Add error message for incorrectly added court date for casa cases
- Checks for both an invalid date and a partial date
Added two additional tests for when a supervisor edits a casa case
=> Fix error message for bad court date for casa cases

spec/support/capybara.rb, spec/system/admin_views_volunteers_page_spec.rb, spec/system/all_casa_admins/all_casa_admins_casa_orgs_spec.rb, spec/system/authentication_spec.rb, spec/system/can_sign_in_as_all_casa_admin_spec.rb, spec/system/edit_user_system_spec.rb, spec/system/supervisor_views_volunteers_page_spec.rb
Resolves #967 #966 #964 #960 #959
Travis runs with [selenium_chrome_headless](https://github.com/rubyforgood/casa/blob/9da2c4497b41fd026b6a758808ee5d443491bc0e/spec/spec_helper.rb#L34) that is configured with [default values from capybara](https://github.com/teamcapybara/capybara/blob/b154720822bd5b182b4071f1ec624406030ec27b/lib/capybara/registrations/drivers.rb#L27-L36). So, I registered our own [selenium_chrome_headless](https://github.com/rubyforgood/casa/pull/979/files#diff-1b366f44043971d2660c6cd2050cdf5bR22-R28) with window size setting
I removed skipping from this tests:
- spec/system/admin_views_volunteers_page_spec.rb 
- spec/system/all_casa_admins/all_casa_admins_casa_orgs_spec.rb 
- spec/system/authentication_spec.rb 
- spec/system/can_sign_in_as_all_casa_admin_spec.rb 
- …
=> fixes capybara window size issue

app/controllers/casa_admins_controller.rb, spec/requests/casa_admins_spec.rb
Resolves https://github.com/rubyforgood/casa/issues/952
I created a error treatment (Errno::ECONNREFUSED) in the methods that active/deactive Admins.
- Admin permissions:N/A
I created tests in requests spec files forcing the error using Mock.
=> Fixed the error treatment to emails send fail

spec/rails_helper.rb
None
Trying to make this error niot happen (it doesn't happen on my machine, so it's hard to know if this helps)
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1601945719142500
> I'm unable to run any specs and getting this error:
```
An error occurred while loading ./spec/system/volunteer_edits_case_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__) # Prevent database truncation if the environment is production
ArgumentError:
Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
```
> I've been doing some google-fu but can't seem to make any headway on resolving this. The only thing that seems to keep coming about is that perhaps it's a Ruby 2.7 issue but I don't know if that's it....any thoughts?
> …
=> Help for ppl debugging env

app/javascript/src/dashboard.js, app/views/volunteers/index.html.erb, spec/factories/volunteer.rb, spec/system/admin_views_volunteers_page_spec.rb, spec/system/supervisor_views_volunteers_page_spec.rb
~~If this looks good, please don't merge yet, I will rebase and update tests after PR #965 is good/merged~~
Resolves #934 
Created filter to view unassigned volunteers
Unassigned volunteers no longer show up with assigned volunteers by default
~~I need to use the changes in PR #965 to update the tests for the filters- Once that PR is merged - I will update this PR.~~
Added test that checks result count when the `No supervisor` filter is applied
This was added to the admin view test page. Adding it to the supervisor test page seems redundant.
How to embed:
=> Create unassigned volunteer filter

app/views/volunteers/index.html.erb, spec/system/supervisor_views_volunteers_page_spec.rb
Resolves #933
View updated to select logged in supervisor on filter by default. This way, when a supervisor accesses the Volunteers page they will initially only see volunteers assigned to them.
In the existing tests, 3 active and 2 inactive volunteers are created. I assigned the mocked supervisor to 1 active and 2 inactive volunteers, and changed the expectation for active volunteers displayed to only select those assigned to the mocked supervisor. If there's a more elegant way to do this (such as mocking it or adding it to factories), please let me know and I will update the tests. I tried `active_volunteers = create_list(:volunteer, 3, :with_assigned_supervisor, casa_org: organization, supervisor: …
=> update view to only show volunteers assigned to supervisor by default

app/controllers/case_court_reports_controller.rb, app/views/case_court_reports/index.html.erb, app/views/layouts/_sidebar.html.erb, config/routes.rb, spec/views/case_court_reports/index.html.erb_spec.rb, spec/views/layouts/sidebar.html.erb_spec.rb
Resolves #923 
- Added a route to "Generate Court Report": `<domain_name>/case_court_reports/`, and placed it to the sidebar.
- When visit "Generate Court Report" link, users can see a form with a select element showing their actively assigned cases.
- The form also has 2 buttons: "Generate Report" & "Download Court Report" as specified in #922 acceptance criteria.
- The buttons do nothing for now. The functionalities are to be developed in #922. 
N/A
Currently, all users can see visit the link and see the form.
- 1 test to check if link 'Generate Court Report' on sidebar is generated
- `spec/views/layouts/sidebar.html.erb_spec.rb`
- Tests to check if the page loads and the form elements (case selection & buttons) are present
- `app/views/case_court_reports/index.html.erb`
=> add route "Generate Court Report" to sidebar

app/controllers/casa_cases_controller.rb, app/models/casa_case.rb, app/policies/casa_case_policy.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/show.html.erb, db/migrate/20201004165322_add_court_report_due_date_to_casa_cases.rb, db/schema.rb, spec/system/admin_adds_new_case_spec.rb, spec/system/admin_edits_a_case_spec.rb, spec/system/supervisor_edits_case_spec.rb, spec/system/user_views_supervisor_edit_spec.rb, spec/system/volunteer_edits_case_spec.rb
Resolves #808
- Adds a  `court_report_due_date` column to the `CasaCase` table.
- Adds a `court_report_due_date` date field in the details view that
admins and supervisors can edit. Volunteers will see a non-editable
date.
- Minor refactor of date parse method in `CasaCase` to allow court report
due date validation.
- Volunteer permissions: View court report due date.
- Supervisor permissions: View/Edit court report due date.
- Admin permissions: View/Edit court report due date.
- Test that the court report due date field is editable in
`supervisor_edits_case_spec` and `admin_edits_case_spec`.
- Test the the court report due date field is visible in
`volunteer_edits_case_spec`.
- Test that an invalid court report due date throws an error in
`supervisor_edits_case_spec`.
=> Allow supervisors/ admin to update court report due date

app/controllers/casa_admins_controller.rb, app/controllers/case_assignments_controller.rb, app/controllers/volunteers_controller.rb, app/policies/casa_admin_policy.rb, app/policies/casa_case_policy.rb, app/policies/case_assignment_policy.rb, app/policies/volunteer_policy.rb, app/views/casa_cases/_form.html.erb, app/views/casa_cases/_volunteer_assignment.html.erb, app/views/case_contacts/_case_contact.html.erb, app/views/users/edit.html.erb, app/views/volunteers/index.html.erb, spec/policies/casa_admin_policy/casa_admin_policy_spec.rb, spec/policies/casa_case_policy/casa_case_policy_spec.rb, spec/policies/case_assigment_policy/case_assigment_policy_spec.rb, spec/policies/volunteer_policy_spec.rb, spec/requests/volunteers_spec.rb, spec/views/casa_cases/edit.html.erb_spec.rb, spec/views/casa_cases/new.html.erb_spec.rb, spec/views/case_contacts/case_contact.html.erb_spec.rb, spec/views/case_contacts/index.html.erb_spec.rb, spec/views/volunteers/index.html.erb_spec.rb
Resolves #996 
I moved all of the permission logic from UI/views into pundit policy files.
- Well, I added new tests in `spec/policies` for check permissions in actions.
- I needed to refactor and fixed some tests because some view does not have a pundit activate.
-  I think to improve organization in some tests using let and before.
I'm not changed anything views, only move the logic into pundit policy files.
How to embed:
=> Move user permission logic from erb into pundit policy files 

app/controllers/casa_admins_controller.rb, spec/requests/casa_admins_spec.rb
Resolves #1015 
Change redirect after create or edit casa admins to admins page
fixed old spec
How to embed:
=> Change redirect after create or edit

app/javascript/src/dashboard.js, app/views/case_contacts/_form.html.erb
Resolves #1003 
- I configure a scroll in X-axis for case details datatable.
- I'm found another UI issue when users permitted need to create a new case_contact and fixed this too.
I don't know, what type of test I need to write for this issue, if exist a test for this case, I would like to learn. 
How to embed:
=> Fix funky UI for case details on narrow screen

app/controllers/imports_controller.rb, spec/requests/imports_request_spec.rb
Resolves #1012
- Changed the response format when an import fails because invalid headers.
How to embed:
=> Change the format invalid headers when imports

app/javascript/src/stylesheets/shared/layout.scss
Resolves #1020 
quick fix for Case Contacts page
currently showing header names (`span.mobile-label`) in table cell
added a rule to hide `mobile-label` on desktop view
N/A
Manual QA
=> quick fix for Case Contacts page, add a rule to hide mobile label on desktop

app/javascript/src/index_reports.js, app/views/reports/index.html.erb
Resolves #1014 
Currently when user entering start_date and end_date there was no check if start date is bigger than end date. With this PR we aim to block this. If user enters bigger starting date then end date this error will be show. (Screenshot 1)
After invalid dates entered I made download button hidden, because of wrong url creation on datepicker.js (SS 2)
After user changes dates and correct the mistake download button will appear again. (SS 3)
I also notice small typos on index_reports.js and fixed them.
- Volunteer permissions: No change
- Supervisor permissions: No change
- Admin permissions: No change
I didn't see any form view testing. I tested manually
**Screenshot 1**
**Screenshot 2**
**Screenshot 3** …
=> #1014 - Arrange datepickers to block incompatible dates

app/controllers/case_contact_reports_controller.rb, app/controllers/reports_controller.rb, app/views/reports/index.html.erb, spec/requests/case_contact_reports_spec.rb, spec/system/reports/index_spec.rb
Resolves #1039 
* Added csv format to case contacts report url
* Added restrictions in case_contact_reports controller to not allow volunteers
* Fixed case contact report request spec to test that volunteers cannot access route but supervisors and admins are allowed
* Modified Report controller to use Pundit authorization to be consistent with view
- Volunteer permissions: volunteers no longer allowed to access the /case_contacts_report url
* Fixed up request specs, added system test
=> Fix case contact reports downloading

spec/requests/case_contact_reports_spec.rb
Resolves #1065
A call to `Time.local` was changed to `Time.zone.local` to ensure that the time zone being used in the tests was the time zone for which the Rails server was configured (and not necessarily the server host's native time zone).
=> Fix time zone error (#1065).

app/models/user.rb, config/locales/devise.en.yml
Resolves #1043
https://github.com/rubyforgood/casa/issues/1043
Error message changed.
When admin deactivates himself/herself, On his/her login, the error message was to be changed.
Manually:
- deactivating the admin user on it's own.. and then logging in. Works as expected.
- when the admin is deactivated by someone else. Works as expected.
- when admin deactivates other user, Works as expected. 
1.
2.
How to embed:
=> Admin login message fix when logging back in

app/javascript/src/dashboard.js, app/javascript/src/stylesheets/pages/case_contacts.scss, spec/system/admin_views_case_contact_index_spec.rb
Resolves #1038 
Our data tables were calculating the wrong width. Overwriting those classes width's to be `100%` made them render as expected. 
-- Another way we could fix this is by turning the autoWidth function off, just like how we're doing in `dashboard.js` to the `volunteersTable`. However if we do this, the table doesn't scale when shrinking and expanding the window.
Added a test to make sure both the `case-contact-table`'s have the same width. 
Scaled
=> Turn off auto width for case contacts dataTable

app/decorators/case_contact_decorator.rb, app/models/case_contact.rb, db/migrate/20201013171632_remove_contact_types_from_case_contacts.rb, db/schema.rb, db/seeds/development.rb, db/seeds/qa.rb, db/seeds/staging.rb, spec/decorators/case_contact_decorator_spec.rb, spec/factories/case_contact.rb, spec/factories/case_contact_contact_type.rb, spec/models/case_contact_report_spec.rb, spec/models/case_contact_spec.rb, spec/requests/case_contacts_spec.rb, spec/system/admin_adds_a_case_contact_spec.rb, spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #1050 
- Removes Contact Types column from Case Contact Table (code uses ```case_contact.case_contact_types``` instead of```case_contact.contact_types```)
- Case Contact now ```has_many contact_types``` (previously ```db_contact_types```)
- This has been updated in seeding files, tests, and models
- Current tests have all been updated to reflect changes
- Not sure if any other tests are wanted/required for this since this is cleaning up, not changing functinality
=> Remove case_contact.contact_types

spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #1059 
Re-enabled tests in ```volunteer_adds_a_case_contact_spec.rb``` that were previously x'ed for a deployment [here](https://github.com/rubyforgood/casa/commit/e70258b69e9420fd91921aeaede916b364c26501)
The tests pass!
That said, if there are any screenshots from what errors happened in deployment I'm happy to take a look at those. 
*waits suspiciously for CI tests to fail, because that seemed too easy*
=> uncomment tests in volunteer_adds_a_case_contact_spec.rb

app/javascript/src/dashboard.js, spec/system/volunteer_views_dashboard_spec.rb
Resolves #1067
This PR updates the "My Cases" table to display "No active cases" (instead of "No data available in table") to help users understand why the table is empty. 
resources:
- DataTables [language.emptyTable](https://datatables.net/reference/option/language.emptyTable) parameter 
- added a test that searches for the `No active cases` text when the volunteer viewing the dashboard has no case assignments (spec/system/volunteer_views_dashboard_spec.rb)
How to embed:
=> [Issue#1067] change My Cases table text when empty

spec/rails_helper.rb, spec/support/css_helpers.rb, spec/system/admin_views_case_contact_index_spec.rb
The method added assists in testing CSS specified attribute values. I say _specified_ attributes because it tests the values _specified_ for the element, which may be modified at runtime. It parses the string returned by `capybara_element['style']` and returns a hash of attribute key/value pairs.
I don't know, is this functionality provided somewhere else? It is _not_ the same as interrogating the actual values at runtime.
In addition, I've modified a unit test to use this method so that it is more immune to future unrelated attribute changes.
I've put the method in `rails_helper.rb` but realize there is probably a better place for it. What would that place be?
=> WIP: Add specified_style_attributes method, use it in a test to restrict test to 1 attribute.

app/policies/application_policy.rb, app/views/layouts/_sidebar.html.erb, spec/policies/application_policy_spec.rb, spec/views/layouts/sidebar.html.erb_spec.rb
Resolves  #1103
I created a new policy to manage who can see the "Generate Court Report" link in navbar
- Supervisor permissions: will not see the link in navbar for "Generate Court Report"
- Admin permissions: will not see the link in navbar for "Generate Court Report"
- Added a new policy spec
- Added new expectations to sidebar spec
**Volunteer view:**
**Admin view:**
**Supervisor view:**
=> Remove route to "Generate Court Report" from sidebar for admins and supervisors

app/views/layouts/_sidebar.html.erb, app/views/layouts/footers/_not_logged_in.html.erb, spec/views/layouts/footer.html.erb_spec.rb, spec/views/layouts/sidebar.html.erb_spec.rb
Resolves #1104 
**Changes**
Have added link to report issues on the sidebar for logged in users & in footer for users not logged in.
Opening the form link in new tab as it is a different domain. Please confirm if this behaviour is okay.
**Tests:**
Have added tests in sidebar.html.erb_spec & created footer.html.erb_spec
**Screenshots:**
For logged in user, the link appears on the sidebar
For users not logged in yet, it appears on the footer
=> #1104 added bug report formlink in sidebar and footer

app/views/casa_orgs/_hearing_types.html.erb, spec/system/edit_casa_org_spec.rb
Resolves https://github.com/rubyforgood/casa/issues/1073
Changed the "Manage Court Details" table to display Yes/No instead of true/false for Active.
I've added to the edit page system a test that checks there is a row with 'Spec Test Hearing Type', 'Yes', 'Edit' in the hearing types table.
I've have preferred to use the `:with_cols` option to only match on "Active: Yes" rather than coupling the test to the other values in the same row. However this matcher doesn't understand the layout of the table as is.
Should I also change the column header from "Active" to "Active?" for consistency?
=> Make "Manage Court Details" Active column match columns above it true vs Yes

app/models/contact_type_group.rb, case-contacts-report-1602730057.csv, case-contacts-report-1602730059.csv, spec/models/contact_type_group_spec.rb
Resolves  #883
I added validation to the contact_type_group model to fix the duplication of the group names, so there isn't a confusion when creating groups. 
- Volunteer permissions: Makes it easier to create group forms.
- Supervisor permissions: 
- Admin permissions: 
It's tests are in the ./spec/models/contact_type_group_spec.rb to test the error we get back "ActiveRecord::RecordInvalid, 'Validation failed: Name has already been taken'"
How to embed:
=> Fix "contact_type_group" duplication of names 

db/seeds/development.rb, db/seeds/qa.rb, db/seeds/staging.rb
Resolves #1123
**Changes**
development, qa and staging seeds to create multiple AllCasaAdmins
Following admin users will work now
1. allcasaadmin@example.com
2. all_casa_admin2@example.com
3. all_casa_admin3@example.com
**Screenshots**
Able to login with ``all_casa_admin2@example.com`` in development environment
=> #1123 modified seeds to create3 AllCasaAdmins

app/controllers/case_contacts_controller.rb, spec/system/admin_adds_a_case_contact_spec.rb, spec/system/volunteer_adds_a_case_contact_spec.rb
Resolves #1004 
Changed the way contact_type_groups are pulled from the database in the case_contacts_controller. The resulting record sets should no longer contain contact_type_groups that do not have any contact_types or only hidden contact_types.
The desired behavior is tested in the admin_adds_a_case_contact_spec and volunteer_adds_a_case_contact_spec. The volunteer version of the test is waiting for a re-factor for full functionality
How to embed:
=> Do not show empty contact type groups or those with only hidden contact types on the create/edit case contact page

app/models/casa_case.rb, app/models/casa_org.rb, app/models/user.rb, db/seeds/development.rb
...which will make the development seeding script idempotent.
Resolves #1112
Some `dependent: :destroy` relationships have been added. Currently, the only top level objects that need to be destroyed in order to empty the data base are `CasaOrg`, `AllCasaAdmin`, and `ContactType`.
A test has been added to the script to ensure that all the known tables have been emptied before records are added.
=> #1112 - Add dependent/destroy relationships to models as appropriate so that seeding is idempotent

app/models/case_contact.rb, app/views/case_contacts/_case_contact.html.erb, spec/models/case_contact_spec.rb
none
Change tooltip copy to make it more understandable based on user testing feedback
> I checked under cases and made sure - these are both cases assigned to this Supervisor.  I see that the ? says "disallow edit contact after quarter" -- not sure if that's a note to programmers or if that would be the note to me as a supervisor. But I'm not sure why some get it and others don't?
no
existing spec us updated
=> Improve copy and error for past-quarter case contact editing

app/models/case_contact.rb, spec/models/case_contact_report_spec.rb
Resolves the first 2 bugs mentioned in #1117 
Refactored scope `contact_type_groups` to fix unhandled bug for 
- unhandled situation when user selects the prompt option (with value as am empty string) in Contact Type Group filter
- `where("contact_types.contact_type_group_id in (?)", contact_type_group_ids)`: `contact_type_group_id` is expecting a `bigint` type, but is given empty string `""`
- duplicate records when `case_contact` involves many `contact_types` of the same `contact_type_group`
```rb
scope :contact_type_groups, ->(contact_type_group_ids = nil) {
if contact_type_group_ids&.join&.length&.positive?
joins(contact_types: :contact_type_group)
.where(contact_type_groups: { id: contact_type_group_ids })
.group(:id)
end
}
```
In test file `app/models/case_contact.rb`, move other …
=> 1117 bugfix casa admin download csv report

.travis.yml, Gemfile, Gemfile.lock
Resolves #1040 
Simplecov version, after some time searching and looking at the errors and logs on Travis and checking the configuration for the test reporter I found a problem with simplecov 0.18+ and CodeClimate Test Reporter, some changes in simplecov 0.18 are not compatible with the actual CodeClimate Test Reporter, to make it work together I fixed the version of simplecov to 0.17.1, as stated on the issue https://github.com/codeclimate/test-reporter/issues/418 CodeClimate core team is trying to work with simplecov to make 0.18 compatible with test reporter.
I need someone with permission to edit the settings on this repo to add an env var called `CC_TEST_REPORTER_ID` with the CodeClimamte Test Reporter ID, that can be achieved similar to the example below:
_**note that I tested the …
=> Fix simplecov and Code Climate Test Reporter

app/views/reports/index.html.erb, spec/system/reports/index_spec.rb
This commit ensures that the default date range set for
the case generation page is 6 months as opposed to the
previous 30 days.
Resolves #1148 
The default date range for generate case reports was set to 6 months because it was requested.
There were two lines added into the test that ensures that if the page can be viewed, the date fields are set properly.
How to embed:
`![alt text](https://media2.giphy.com/media/1ykCCe2A2pHsCIR1QX/giphy.gif)`
=> default date range for reports 6 months

app/javascript/src/stylesheets/shared/layout.scss, app/views/devise/sessions/new.html.erb, app/views/layouts/_login_header.html.erb, app/views/layouts/_sidebar.html.erb
This commit make the size of the page header dynamic so that in
mobile it is completely legible. Spaces are added to the top and
bottom of the login page to create spacing in mobile. Additionally,
an empty list element was added to combat a known bug in bootstrap
list-groups with height calculation on small screens.
Resolves #1151
The following view bugs have been fixed:
now looks like:
and the collapsible menu that looked like this
now looks like:
Visual testing
See above
How to embed:
`![alt text](https://media0.giphy.com/media/KBfKueAjIJV8Q/giphy.gif)`
=> Fix bugs in mobile view

app/controllers/case_court_reports_controller.rb, app/controllers/concerns/accessible.rb
As part of the conversation in #1164, we noticed that it was autocorrecting `and return` to `&& return` which isn't the same. Added a comment to disable the rule for those three lines.
=> and return not && return

app/views/casa_cases/_form.html.erb, spec/views/casa_cases/edit.html.erb_spec.rb, spec/views/casa_cases/new.html.erb_spec.rb
Resolves #1166 
* Reverted to `current_organization` in casa case form.
* Stubbed `current_organization` in view spec. Did not figure out why the stack level too deep error was occurring, but since view spec doesn't actually hit the controller, okay to stub. There are existing request specs that work that test the controller and form view work just fine.
=> Stub current_organization in view spec

spec/seeds/seeds_spec.rb
Now that the same seed code is used for all three environments, we can test that code once. This cuts the seed test time to a quarter of what it was before.
=> Test seeding for only development, no longer for qa and staging.

app/controllers/casa_orgs_controller.rb, app/controllers/judges_controller.rb, app/models/judge.rb, app/views/casa_orgs/_hearing_types.html.erb, app/views/casa_orgs/_judges.html.erb, app/views/casa_orgs/edit.html.erb, app/views/judges/_form.html.erb, app/views/judges/edit.html.erb, app/views/judges/new.html.erb, config/routes.rb, db/migrate/20201023233638_create_judges.rb, db/migrate/20201023234325_add_active_to_judge.rb, db/migrate/20201024003821_add_name_to_judge.rb, db/schema.rb, spec/factories/judges.rb, spec/models/judge_spec.rb, spec/requests/judges_spec.rb, spec/system/create_judge_spec.rb, spec/system/edit_casa_org_spec.rb
Resolves #929 
* introduces a new `Judge` model which belongs to a casa_org.
* allows a new judge to be added per organization
* allows existing judge to be edited
* allows `active` status to be set per judge
* ensures that new judge can be added to org.
* ensures that judge exists on Edit organization page.
=> Introduce Judge model

app/models/hearing_type.rb, spec/models/hearing_type_spec.rb, spec/requests/hearing_types_spec.rb
Resolves #1162 
removed validation for hearing type to be active
when active checkbox unticked, saves status as inactive
allows for inactive status where it would previous throw error if empty
inactive status saving successfully via manual testing
How to embed:
=> resolves #1162 - added option to mark hearing type as inactive

app/views/volunteers/index.html.erb, spec/views/volunteers/index.html.erb_spec.rb
Resolves #1154 
cdbb83f Create test for volunteer links
- Created a test to check if the volunteer name is a link. Moved the test
setup code to the top level scope. Also added an addtional test to check the happy path of an existing test.
- In the index file I prepended some messages with the decorate message.
For some reason in the view test it would error with message not found.
I'm not sure what the architecture of the decorator is; however it seems
strange that when live testing it is not needed. Does anybody have any
insight on this?
fcd042c Add closing quotes
- There was an ending quote missing causing the links to not display.
- It seems this bug was introduced in PR #973
Unit test created.
=> Fix bug where volunteer link was not displaying

app/views/layouts/_sidebar.html.erb, spec/views/layouts/sidebar.html.erb_spec.rb
Per issue #1181, remove the route to the case contacts in the
sidebar for admin and supervisor users.
Resolves #1181 
The Case Contacts item was removed from the sidebar for admin and supervisor users.
The sidebar test were modified to expect there not to be a link for the supervisor and admin users.
How to embed:
=> remove Case Contacts from admin/supervisor sidebar

app/controllers/application_controller.rb, spec/helpers/application_helper_spec.rb, spec/system/can_sign_in_as_all_casa_admin_spec.rb
Make the sign out path for all_casa_admmin lead to
the new session path for all_casa_admin
Resolves #1187 
Clicking log out now leads to the correct log-in page for all_casa_admins.
Check for "All CASA Log In" text after log out redirect.
How to embed:
=> Modify sign out for all_casa_admin

app/controllers/all_casa_admins/casa_admins_controller.rb, app/views/all_casa_admins/casa_admins/edit.html.erb, app/views/all_casa_admins/casa_orgs/show.html.erb, config/routes.rb, spec/requests/all_casa_admins/casa_admins_spec.rb
Resolves #1180 
- added edit link to casa org admins table & added edit page to allow all casa admins to edit other admins details
- updated controller with update, activate & deactivate
- added new routes to include activate & deactivate
- all casa admin can now update email, activate & deactivate other admin
manual testing & rspec tests to check that updates to email & active status are successfully saved
=> resolves #1180 - all casa admin can edit/activate/deactivate other admins

README.md
Resolve #1215
Add command to install libpq-dev for Fedora
Add line on Readme.md on postgress installation
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: none
No apply
How to embed:
=> Add command to install libpq-dev for Fedora

app/views/casa_cases/_volunteer_assignment.html.erb
Resolves #1219 
The table-responsive class has been added, it allows the contents of the table to be scrolled horizontally when  table items do not fit completely [Check table-responsive use on bootstrap docs](https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables)
The text-wrap class has added to the button, that allows text to be wrapped. So the button takes up less space and its contents are displayed completely in a large part of the viewport [Check text-wrap use on bootstrap docs](https://getbootstrap.com/docs/4.4/utilities/text/#text-wrapping-and-overflow)
This not affect user permissions
This is a UI fix. Is automated testing necessary for this?
=> 1219 unassign volunteer button overflow

app/lib/importers/case_importer.rb, spec/fixtures/existing_casa_case.csv, spec/requests/imports_request_spec.rb
An additional check was made to provide a different error
message to an admin importing an existing case that is
inactive. This Provides more useful information than just telling
them that the case already exists.
Tests were added to ensure that the error message renders correctly.
Resolves #1190 
An additional check was made to provide a different error
message to an admin importing an existing case that is
inactive. This provides more useful information than just telling
them that the case already exists.
Tests were added to ensure that the error message renders correctly.
How to embed:
=> error when admin imports inactive casa_case

app/views/all_casa_admins/sessions/new.html.erb, app/views/all_casa_admins/shared/_links.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
Resolves #1223 
In both Log In pages, the styles for the 'Log In' button and the 'Forgot Password' have been swapped. This way, the Log In button  is now filled and might be more eye-catching as a main action button.
No changes.
As this change does not impact system behavior in any way, no tests have been written.
=> Swap styles for Login and Forgot Password buttons

Gemfile.lock, app/helpers/ui_helper.rb, app/models/casa_case.rb, spec/system/volunteer_inactive_case_assignment.rb
Resolves #1184 
Added a `active` scope on `CasaCase` and chained that scope onto the `not_assigned` scope used in `ui_helper` to display available cases for assignment. 
This is important to prevent the accidental assignment of an inactive case to a volunteer. 
- Volunteer permissions: no affect
- Supervisor permissions: no affect
- Admin permissions: no affect
Added a system test and tested manually
How to embed:
=> inactive cases are hidden in assignment selector

app/decorators/case_contact_decorator.rb, app/views/casa_cases/show.html.erb, app/views/case_contacts/_case_contact.html.erb, app/views/case_contacts/index.html.erb, spec/system/admin_adds_a_case_contact_spec.rb
Resolves #1133
* This adds a `Notes` column to the case contact table.
* If notes are greater than 100 characters it gets truncated with a `Read more` toggle. Clicking `Read more` shows the full text, and a `Hide` toggle will appear in place. 
* If notes are less than 100 characters it gets shown in full without any toggles.
* Tested adding a short note and a long note in a system spec. The short note will get shown in the table in full, while the long note will get shown truncated but with a `Read more` toggle option. Tested that showing and hiding text works.
=> Add notes to casa_contact show table

app/policies/casa_case_policy.rb, app/views/casa_cases/_form.html.erb, spec/factories/hearing_type.rb, spec/requests/casa_cases_spec.rb, spec/system/admin_edits_a_case_spec.rb, spec/system/volunteer_edits_case_spec.rb
Resolves #1268 
*  Removed Hearing Types and Judges from Casa Case form for volunteers
* Added `hearing_type_id` and `judge_id` to strong parameters so supervisors and admins can actually update those fields
- Volunteer permissions: fixed so can't select hearing types or judges for casa cases
* Added admin/supervisor/volunteer specs
* Added request specs
=> Do not allow volunteers to set hearing type or judge on casa case form

app/controllers/casa_cases_controller.rb, spec/factories/casa_case.rb, spec/requests/casa_cases_spec.rb
Resolves #1193
The following actions are guarded by Pundit in the views, but there is nothing checking in the controllers for permissions.
- This PR is authorizing `deactivate` and `reactivate` methods with `Pundit` as well.
- Adds specs to methods in controller.
Permissions are already set.
- Volunteer permissions: -
- Supervisor permissions: - 
- Admin permissions: - 
New and old code paths got specs  👍 
It does not introduces any new UI it just relies on default authorization and existing forms.
=> Authorizes deactive and reactivate controller's method

app/controllers/emancipation_checklists_controller.rb, app/policies/application_policy.rb, app/views/layouts/_sidebar.html.erb, spec/policies/application_policy_spec.rb, spec/views/layouts/sidebar.html.erb_spec.rb
Resolves #1267
Remove Emancipation Checklist from the sidebar for supervisors and admins
Added specs
=> Don't show Emancipation Checklist to non-volunteers

app/decorators/casa_case_decorator.rb, app/models/casa_case.rb, lib/tasks/deployment/20201108181154_backfill_court_report_submitted_at.rake, spec/decorators/casa_case_decorator_spec.rb, spec/models/casa_case_spec.rb, spec/requests/casa_cases_spec.rb, spec/system/admin_adds_new_case_spec.rb, spec/system/admin_edits_a_case_spec.rb, spec/system/supervisor_edits_case_spec.rb, spec/system/volunteer_edits_case_spec.rb
Resolves #806 
`court_report_submitted` as a boolean only tracked whether or not the report had been submitted. It did not track when it was submitted nor if it was completed. This PR adds `court_report_status` which tracks the current status of the court report, and `court_report_submitted_at` which tracks when it was submitted.
Cases will now have a court report status of 'Not submitted' by default. All users can update `court_report_status`. When the `court_report_status` is set to 'Submitted', 'In review', or 'Completed' for the first time, the `court_report_submitted_at` field is immediately set. If the `court_report_status` is ever set to 'Not submitted', the `court_report_submitted_at` date field will be cleared.
This PR also adds an after_party backfill that modifies all cases …
=> Update specs to reflect new court report status select

app/views/casa_cases/show.html.erb
Resolves #1269 
In Casa Case Detail View, volunteer names appeared as a link to all users. Now it appears as plain text if the current user is a volunteer.
=> WIP: render volunteer names in plain text if current user is volunteer

doc/DOCKER.md, docker/test-log
#1229 # What github issue is this PR for, if any?
Resolves #1206 .
The "-fd" flag is removed from the RSpec command in the docker/test-log script and the instructions in the doc/DOCKER.md file.    Omitting the "-fd" flag means omitting the printing of every test.  The resulting cleaner output makes it easier to see warning and error messages.  This makes debugging the troubleshooting much easier.
=> Removed the -fd flag to clean up the screen output

spec/views/casa_cases/show.html.erb_spec.rb
Resolves #1269 
Added missing specs for `casa_cases` show view
tests are in `views/casa_cases/show.html.erb_spec.rb`
=> add specs for casa_cases show view

app/views/casa_cases/_form.html.erb, spec/system/supervisor_edits_case_spec.rb
Resolves #1153
This ensures the "Select Judge" dropdown is not displayed when
editing/creating cases belonging to a Casa org that has no Judges
assigned. This is done by wrapping the select with a conditional that checks if there are any judges for the current organisation.
The PR adds two tests in the `spec/system/supervisor_edits_case_spec.rb´,  ensuring the Judge select menu is available when there are judges assigned and checking the menu is not available when there are none.
Select menu unavailable:
Select menu available:
=> Only display judge names if Casa org has judges

app/decorators/case_contact_decorator.rb, app/views/case_contacts/_case_contact.html.erb, db/seeds.rb, db/seeds/db_populator.rb
Resolves #1334
Show linebreaks in notes in case contact view with simple_format. 
Add linebreaks to notes seed. 
Add casa org prefix to volunteer names and as postfix to casa case numbers (prefix breaks filter search)
no
existing spec + run seed and server locally
How to embed:
=> case_contact.notes viewing and seeding tuning

app/views/layouts/_sidebar.html.erb
Resolves #1299 
There was an empty list item at the bottom of the sidebar menu, leaving a black dot at the bottom. Removed it.
haven't added tests for this
=> remove empty list item

app/javascript/src/stylesheets/shared/sidebar.scss, app/views/layouts/_sidebar.html.erb
Resolves #1275
Currently in the mobile view, the side bar nav is not scrollable, making
the log out button inaccessible. This PR adds an `overflow-y: scroll` property to 
the sidebar container.
This PR also updates `list-group-item` from `div` to `li` for greater
consistency with the rest of the file, and for correct semantics.
Sorry these screenshots aren't great 😅. Let me know if I should retake. 
Before: Can't access log out button
After:  Can access logout button
=> Fix hidden logout button on mobile view

.github/workflows/cypress.yml, .github/workflows/erb_lint.yml, .github/workflows/rspec.yml, .github/workflows/ruby_lint.yml, .github/workflows/security.yml
Another attempt from where I left off in PR #1341 
This can speed up build times when deps are not altered.
I don't believe there is an issue for this. Is it preferable to have one?
Cache dependencies when building on the CI server
hmmm. There are no tests. If it runs it runs.
How about a gif?
How to embed:
=> cache deps in CI

README.md
Resolves rubyforgood#1354
Readme.md has a new badge.
It won't.
By checking the README.md
[Oh, even better, you can look at the live change](https://github.com/notapatch/casa)
=> Add isitmaintained badge to readme

app/controllers/casa_cases_controller.rb
None
Added eager loading to CasaCasesController#index action. Why? If optimization isn't compelling enough, then I'd say that removing N+1 means there will be fewer warnings in the log file allowing you to concentrate on what's left.
Every time you loaded in the CasaCasesContrller#index action you get the following in the log:
```
user: [censored]
GET /casa_cases
USE eager loading detected
CasaCase => [:hearing_type]
Add to your query: .includes([:hearing_type])
Call stack
/Users/[censored]/Documents/code/projects/casa/app/models/casa_case.rb:66:in `hearing_type_name'
/Users/[censored]/Documents/code/projects/casa/app/views/casa_cases/index.html.erb:130:in `block in _app_views_casa_cases_index_html_erb___1018416056451763536_64540' …
```
=> Added eager loading to CasaCasesController#index action

app/models/all_casa_admin.rb, app/models/casa_admin.rb, app/models/supervisor.rb, app/models/user.rb, app/models/volunteer.rb, db/migrate/20201120103041_remove_remember_created_at_from_users.rb, db/migrate/20201120103146_remove_remember_created_at_from_all_casa_admins.rb, db/schema.rb
- the application only uses the Devise timeoutable module to
time limit user access. It does not use Devise's Rememberable
module. However, the remember_me attribute has been configured
by accident.
- this was noticed when script attacks in production caused
exceptions on the app on the remember_created_at attribute.
https://github.com/rubyforgood/casa/issues/1348
- this PR removes the remember_me attribute from the application
---
Resolves #1348
Described in the git commit above.
It won't
The wasn't part of the application and wasn't tested. It's removed now. I've
checked that the timeout works as before (no reason to have broken!).
=> Remove Devise remember_me attribute

app/controllers/volunteers_controller.rb
- Adds supervisor_volunteer to eager loading
- from Bullet log message
---
Applied against #1234 - this fixes an N+1 in `/volunteers` I do not know if it changes the loading time in QA.
/volunteers is slow loading in QA. This fixes an N+1 bug which may or may not help.  
It won't
When you load` /volunteers` you get the following suggestion from Bullet: 
```
user: [censored]
GET /volunteers
USE eager loading detected
Volunteer => [:supervisor_volunteer]
Add to your query: .includes([:supervisor_volunteer])
Call stack
/Users/[censored]/Documents/code/projects/casa/app/models/volunteer.rb:47:in `has_supervisor?'
/Users/[censored]/Documents/code/projects/casa/app/views/volunteers/index.html.erb:143:in `block in _app_views_volunteers_index_html_erb___3469684865829442258_43140' …
```
=> Added eager loading to VolunteersController#index action

lib/tasks/send_supervisor_digest.rake
More follow up on  #1346 
Sorry, one more small change for the weekly supervisor summary email.
I went to schedule this on Heroku Scheduler and we can only schedule daily, hourly, or every 10 minutes.  So I'll have to run this every day and check if it's Monday before executing the code.
This isn't exactly ideal.  Maybe if someday we have lots of tasks we'll want to find another solution?  This seems like a fine solution for now, and it's free.  But let me know if you want me to do something else, otherwise if you merge this code I'll schedule heroku to run daily.
=> Only send email if day is Monday

app/javascript/src/stylesheets/shared/sidebar.scss
=> Hide sidebar scroll when theres no overflow

app/views/supervisors/index.html.erb
Resolves #1239 
Spans with a mobile only class were added to the supervisors index view
I wouldn't typically write a test for something like this since it does not alter the logic of showing/hiding links or buttons. See the _after_ screenshot below.
How to embed:
=> Improves mobile view of supervisors index

app/javascript/src/stylesheets/shared/layout.scss
Resolves #1265 
Added a `margin` rule to add 6px of vertical spacing to the top and bottom of each "Filter By" button. This means that there will be effectively 12px of vertical space between buttons when screen size forces these buttons to go above/below each other. This creates a more discernible separation between the buttons, making them easier to interact with.
It will not.
=> issue 1265: add vertical spacing "Filter By" buttons

app/models/contact_type_group.rb
Resolves #1255 
Adds `.order(:name)` to the appropriate `scope` in the `ContactTypeGroup` model to sort the Select Field options on the `Edit Contact Type` view. i.e. `/contact_types/1/edit`
- Admin permissions: n/a 
It's not 😢 . See issue #1391 
But I did verify that it's working manually. See Screenshot. 
Because I didn't write a test:
=> Sort Contact Type Groups in Edit page select field

db/seeds/db_populator.rb, lib/tasks/data_post_processors/case_contact_populator.rb
The ContactType data was not being inserted prior to the CaseContact
data being created, which caused case contacts to not have any contact
types associated with it. I've added a new statement to insert the
ContactType data prior to CaseContact data being created.
Resolves #1505
I added a line to insert the ContactType data into the tables prior to the CaseContact data being created, so that the CaseContact data can be associated with contact types instead of having no contact types.
I've tested it on my local machine and confirmed that all of the case contact data have 2 contact types associated with each of them.
=> Fixes issue where case contacts have no contact types.

.github/workflows/issue-auto-unassign.yml
The workflow will run once per hour and will post a warning message in
issues that are older than 5 days telling the user that the issue will
be unassigned after 7 days. After 7 days it will be unassigned. The
algorithm to determine the time of inactivity will account for comments
made but not events.
Resolves #1409
A new workflow file was created in order to unassign inactive issues.
I tested it manually in a test harness I created:
https://github.com/bjthompson805/hello-world-javascript-action
Here is what it looks like when the bot comments as well as unassigns the issue.
I suggest a code review of the action itself as well:
https://github.com/bjthompson805/unassign-issues
Also, you may want to fork …
=> New workflow to unassign inactive issues.

lib/tasks/send_supervisor_digest.rake
Supervisor weekly mailer wasn't going out since it was missing `deliver_now` or `deliver_later`
=> Add deliver_now to mailer method

.github/workflows/add-help-wanted-labels.yml
Uses GitHub Actions to add the labels once per hour.
Resolves #1363
The label will be added to all issues in the To Do column.
N/A
I tested it manually in a test harness I created:
https://github.com/bjthompson805/hello-world-javascript-action
Running the action once in the test harness, the issues ended up looking like this:
Running it multiple times had no issues.
=> Adds "Help Wanted" labels to issues in To Do.

app.json, db/seeds/casa_org_populator_presets.rb
Resolves #1238 
- Use `db:migrate` instead of `schema:load` since `schema:load` is a destructive action on the database and requires an extra flag to run
- Running the seed file was causing an error since `production` was not available as an option for which dataset to use. Modified the seed code to use the `APP_ENVIRONMENT` environment variable to determine the dataset since we no longer have qa and staging environments. Set the review apps to have `APP_ENVIRONMENT` of "qa".
=> Heroku review app configuration

.github/workflows/issue-auto-unassign.yml
Issues found to be in the In Progress column will now be moved to the To
Do column. The unassign-issues action has been modified to output the
issues that were unassigned.
Resolves #1541
The issue-auto-unassign.yml file changed to retrieve the new outputs from the unassign-issues action and pass them to the new move-issues action. It also prints them out for better debugging.
Here is the new action: https://github.com/bjthompson805/move-issues
Tested manually in my test harness: https://github.com/bjthompson805/hello-world-javascript-action
Here, issue number 4 and number 6 were self-assigned, and the same workflow as in this PR was ran so that the issues were unassigned and then the move-issues action moved them from In Progress to To Do.
=> Move unassigned issues from In Progress to To Do.

docker-compose.yml
Resolves #1539 
Production is now running version 12.5, so upgrading Docker dev environments to match.
=> Upgrade postgres version for Docker

README.md
Updating readme with the seed admin user info for the second tenant.  I have forgotten this a couple times and had to look it up, I think it would be helpful to have here.
=> Add second tenant seed admin to readme

app/javascript/src/stylesheets/application.scss, app/javascript/src/stylesheets/shared/select2.scss, app/views/reports/index.html.erb
I couldn't find an issue for this.
While I was fixing the report bugs I noticed it was a bit difficult to find and
select what I was looking for. This adds the `select2` class to the 4
multi-selects on this page. We're already using `select2` in some other forms.
There is already tests for this selects so adding more seemed like overkill.
Before:
After:
How to embed:
=> Better UX for Generate Reports multi selects

app/views/supervisor_mailer/weekly_digest.html.erb
Small update to the language of the supervisor weekly digest email as discussed at the casa meeting.  Just want to be clear that nothing was logged, we're not sure if contacts were made but not logged.
@Zrrrpy for added info, I looked it up and in the email we show any contacts that have an `occured_at` this week.  So if they logged it this week for a contact they made last week it won't show up.  If we want to we could show anything that was created this week OR we could show anything created/updated this week regardless of when the contact was made.  Thanks for getting clarification from the pg casa folks.
=> Update language for weekly digest when no case contacts have been logged

app/javascript/src/dashboard.js, app/views/supervisors/index.html.erb
Resolves #001
Uses the DataTable function in dashboard.js to make the table used for displaying the supervisors index sortable. See #1573 for motivation.
- Admin permissions: No change
Manually tested that sorting is applied to the table, and DataTable itself already has unit tests.
=> add sorting to supervisors dashboard

app/javascript/src/dashboard.js
Resolves #1600 #1599
Tune the parameters to DataTable call used to add sorting to the supervisors view so that the horizontal scrolling is disabled and you can't sort by the actions column anymore.
- Admin permissions: None changed.
I just changed stuff and checked that it looked ok. Not sure how you'd unit test it though.
=> fix up supervisors view

app/controllers/emancipations_controller.rb, app/javascript/src/case_emancipation.js, app/javascript/src/stylesheets/pages/emancipation.scss, app/views/emancipations/show.html.erb
- Checking an emancipation option will disable the element until the request is complete. (Before it never disabled)
- An emancipation option will only appear checked after the sent request returns with a successful response. (Before it would appear checked and uncheck itself on error responses)
- Auto deleting emancipation options is now handled by a single request. (Before multiple requests would be sent quickly)
=> Improve client side sync for emancipation checklist

app/javascript/src/stylesheets/shared/layout.scss, app/views/casa_cases/show.html.erb
Resolves #1642
Added some small margin between the buttons and card on the case details page when the page is smaller.
When the page is super small the spacing was messed up if all the buttons didn't have the same margin added, this screenshot shows the spacing is working when the page is really compressed.
=> Add margin between buttons and card on case details page

app/views/casa_cases/_form.html.erb
Resolves #1707 .
Moved youth's birth month & year up on the page so that it will be easier to find.  
How to embed:
=> Moved youth's birth month & year up on the page

app/mailers/supervisor_mailer.rb, app/views/supervisor_mailer/weekly_digest.html.erb
Resolves https://github.com/rubyforgood/casa/issues/1628
- Adds a message to the supervisor weekly email if they have no volunteers
- Fixes apostrophe in a plural noun
It won't.
Manually, using mailer previews.
=> Add a message to the supervisor weekly email if they have no volunteers

app/models/casa_case.rb, app/views/casa_cases/show.html.erb
Resolves #1705 
https://github.com/rubyforgood/casa/issues/1705
Per Issue, hiding judge and hearing type when null was requested.
Manually, not sure how to write tests for this, to be honest.
How to embed:
=> Hiding Judge and Hearing Type When Null  - Issue #1705

app/javascript/packs/application.js, app/javascript/src/readMore.js, app/views/case_contacts/_case_contact.html.erb
Resolves https://github.com/rubyforgood/casa/issues/1259
Moves read more JS code from a partial which was being rendered N times. Uses vanilla JS event delegation to handle read more and read less link clicks. We can reuse this feature in other views by using the`.js-*` classes the script expects.
NA
=> Move read more JS code from partial

app/controllers/casa_orgs_controller.rb, app/views/casa_orgs/_contact_type_groups.html.erb, app/views/casa_orgs/_contact_types.html.erb, app/views/casa_orgs/edit.html.erb
Resolves https://github.com/rubyforgood/casa/issues/1390
Sorts contact type groups and contact types by name on the edit organization page.
NA
=> Sort contact type groups and contact types by name

spec/support/factory_bot.rb
This is a super minor PR pretty-printing the stats from FactoryBot.
**Before**
**After**
NA
=> Pretty print FactoryBot object creation stats

.github/workflows/factory_bot_lint.yml
This is a minor PR fixing the factory bot lint workflow which uses the same workflow name and job name as the `rspec` workflow.
**Before**
**After**
NA
=> Fix factory bot lint workflow and job names

app/javascript/src/case_contact.js
Working PR and open to suggestions
Resolves #1835
Added in a JS function to create an alert if a future date is selected to potentially improve the 'new case contact' process.  Hopefully this will help users catch a quick mistake before an attempted form submission.  This warning does not currently prevent a future date from being selected after a user is notified.  Open to adding that feature, but wanted to keep my changes minimal initially.
As of now, no tests have been written.  Could use some advice and instruction in this area
=> Adding a JS alert before the case_contact form is submitted to notify of invalid date selection

app/views/volunteers/_manage_supervisor.erb
none
Make supervisor a link on edit volunteer page
seemed nice
no
😰
=> Make supervisor a link on edit volunteer page

app/views/casa_cases/_form.html.erb, app/views/casa_cases/edit.html.erb
none
Make case number a link on Editing CASA Case page
Seemed nice
no
😰
=> Make case number a link on Editing CASA Case page

doc/CONTRIBUTING.md
Not much, but I've noticed this while reading the document.
=> Fix broken link in doc/CONTRIBUTING.md

.erb-lint.yml, .github/workflows/erb_lint.yml, Gemfile
Installing erb_lint is now unneeded in the erb_lint GitHub workflow since it's now part of the bundler cache, like all gems in the test group.
The erb_lint GitHub workflow should still pass.
=> Move erb_lint to development and test groups in Gemfile

app/controllers/case_court_reports_controller.rb, app/views/case_court_reports/index.html.erb, config/locales/controllers.en.yml
… found
Resolves #1917 
- show error when the template is not found
How to embed:
=> show error on failed case cort report generation when template is not found

app/models/case_court_report.rb
Resolves #1931 
- Change the date format of `volunteer.created_at`
How to embed:
=> fix case court report appointed date format

Gemfile.lock
The changes were generated after running `bundle install` on the current `main` branch. This is reverting changes from #1938.
Mimemagic isn't needed since it was dropped from Rails' dependencies in Rails 6.1.3.1. Active Storage (and thus Rails) is now relying on Marcel for MIME type data. See upstream: https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/
=> Remove unneeded mimemagic dependency from Gemfile.lock

bin/git_hooks/lint, bin/git_hooks/update-dependencies
the linter script for git hooks only uses bundle exec <linter> now
fixed `--unpushed` not working for branches with no remote counterparts
added message indicating when linting was done
=> Fix hooks not using bundle exec

app/models/case_assignment.rb, app/views/case_contacts/_case_contact.html.erb, db/seeds/db_populator.rb
```
I, [2021-04-24T08:12:26.554329 #33]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of ActiveRecord::RecordInvalid
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Volunteer Case assignee must be a volunteer
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/validations.rb:80:in `raise_validation_error'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/validations.rb:53:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:302:in `block in save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/connection_ad …
```
=> unbreak qa seed

app/views/casa_cases/_form.html.erb, config/locales/views.en.yml
Resolves #1966
Added a notice on the Court Mandate section of the Edit Case Form. The notice warns editors not to include youth names in the body of the description.
time | img
--- | ---
Before | ![image](https://user-images.githubusercontent.com/8124558/116820505-835cfd00-ab43-11eb-8537-f5ce62941cec.png)
After | ![image](https://user-images.githubusercontent.com/8124558/116820465-4e50aa80-ab43-11eb-895e-7a9e52129f27.png)
- Volunteer permissions: No Changes
- Supervisor permissions: No Changes
- Admin permissions: No Changes
No additional tests added, because it's a visual change.
=> Add alert to avoid saving youth names in Court Mandates

db/seeds/db_populator.rb, lib/tasks/deployment/20210507200644_fix_transition_aged_youth_for_nil_birth_month_year_youth.rake
Resolves #1996
- Add an after_party task to fix an invalid scenario in staging data
- Fix seeder so this scenario doesn't happen again
It does not affect user permissions
=> after_party task to fix transition_aged_youth when DOB is nil

app/views/casa_cases/show.html.erb
Resolves #2040 
- Update logic to check whether the casa case has case contacts or not to show the download button
- all
Has case contacts:
Has no case contact:
=> Hide Download All button if there are no case contacts

app/views/case_contacts/_case_contact.html.erb, app/views/case_contacts/_followup.html.erb
Resolves #2049 
Updated column tags to allow columns to display properly across multiple browsers.
Manually. Unsure of how to test this.
Purpose of showing Followup button: original fix forced Edit button outside of card.
How to embed:
`![Slaughter to Prevail band member pointing at camera. Much Aggressive!](https://media.giphy.com/media/ihwuwUEZ3nYRwNZuSo/giphy.gif)`
=> Fixed #2049 - UI button overlap bug for case contacts

app/views/case_contacts/_case_contact.html.erb
Tweaks to fix #2049 more cleanly.
Delete button was showing as a giant button rather than a clean, evenly sized button.
- Volunteer permissions: No effects on permissions for any, but screenshots are below to show how the buttons will display for each.
Tests are already implemented
@compwron , I actually just made it somehow a bit better, as it's not as... idk, awkward?
Volunteer View:
Admin View When Followup Selected:
Admin View When Followup Not Selected and Delete Button Post Fix:
=> Final fix of #2049 - Post initial PR Merge.

app/controllers/case_court_reports_controller.rb
Resolves #2038 
- Rescue StandardError beside Zip::Error to handle error log when generating court report fails.
=> Handle error when generating court report fails

app/views/devise/mailer/reset_password_instructions.html.erb, lib/mailers/previews/devise_mailer_preview.rb
Resolves #2121
The "Reset password instructions" email used a hardcoded logo (and text) of Prince George CASA.
It now shows a generic CASA logo and information.
I also added a preview for the reset password mail.
No permissions will be affected.
Since this is only a style change, automated tests have not been written.
Manual testing:
- Request password reset
- Receive/preview e-mail, check if the style and displayed information is correct
How the email looked before the change:
After the change:
=> [#2121] Fix reset password mail hardcoded image

app/javascript/src/stylesheets/shared/dashboard.scss, app/views/volunteers/index.html.erb
Resolves #2108 
- Removed a `style` attribute and used scss instead
N/A
N/A
=> Refactor inline style out of volunteers/index view file

app/javascript/src/stylesheets/application.scss, app/javascript/src/stylesheets/shared/noscript.css, app/views/layouts/application.html.erb, config/webpacker.yml
Resolves #2106
In order to move the inline styles from the application layout to a stylesheet, I needed webpacker to extract css files into the `public` folder since all of these files were not accessible within the `noscript` tag (i.e. without Javascript).
Now that the styles are available without Javascript, the site looks a lot better if a user navigates to the site with Javascript disabled, but they will still see a warning message on every page that Javascript is required (see screenshots below).
N/A
Existing tests
**Before**
**After**
=> Refactor inline styles out of application layout

README.md
Resolves #2045
- Add npm jest test badge (`yarn lint`) to README
- Update badge urls to go to GitHub Actions instead of just going to badge.svg page
N/A
N/A
=> Update readme badges to go to github-actions page

app/views/casa_admin_mailer/deactivation.html.erb, lib/mailers/previews/casa_admin_mailer_preview.rb
Resolves #2155 
Refactored the inline CSS into a <style> element in the deactivation mail.
It will not affect.
No changes to be tested, the content continues the same.
* With inline CSS:
* With <style> tag:
=> Refactor inline CSS into a <style> element in deactivation mail

.github/workflows/issue-auto-close-done.yml
When an issue is created, moved or edited in the 'Done' column this workflow will automatically close it. Based on the examples provided from [Issues States](https://github.com/marketplace/actions/issue-states)
Resolves #2003
Added new workflow
No user permission is affected
Tested on personal repo [Workflows Test](https://github.com/r-sierra/workflows-test/)
=> [2003] Add workflow to close issues when moved to the 'Done' column

bin/git_hooks/README.md, bin/git_hooks/lint
No issue
Updates hook so that if the linter cannot
auto-fix the issues, the hook terminates after the linter's error message.
Previously, if there were linting errors that could not be fixed, the
linter would tell you, but the hook would continue and allow the git
action to go forward.
🤔 
Screenshots using `lint` as a pre-commit hook
Before fix:
After fix:
How to embed:
=> Fix lint hook

app/views/casa_admin_mailer/account_setup.html.erb, app/views/casa_admin_mailer/deactivation.html.erb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/layouts/mailer.html.erb, app/views/supervisor_mailer/account_setup.html.erb, app/views/supervisor_mailer/deactivation.html.erb, app/views/supervisor_mailer/weekly_digest.html.erb, app/views/volunteer_mailer/account_setup.html.erb, app/views/volunteer_mailer/case_contacts_reminder.html.erb, app/views/volunteer_mailer/court_report_reminder.html.erb, app/views/volunteer_mailer/deactivation.html.erb
Resolves #2224
Added css warnings as comments for email layouts with inline css because inline css is the only css supported on some email platforms.
Corrected HTML indentation for `app/views/devise/mailer/reset_password_instructions.html.erb `
Removed CASA org name to describe supervisors in  
`app/views/volunteer_mailer/case_contacts_reminder.html.erb`  
`app/views/volunteer_mailer/deactivation.html.erb `
=> Add warnings to email layouts

app/javascript/src/stylesheets/shared/sidebar.scss
Resolves #2152 
Change `.sidebar-wrapper` height to have a max-height of 100% of the
viewport and get rid of the calculated height on `.sidebar-container`.
This should ensure that the sidebar is always the size of the viewport,
no matter the image size and any extra height will scroll.
I don't think we need a test for this.  If we do, let me know how and I'll write it up.
How to embed:
=> Make sidebar height 100vh regardless of image size

app/javascript/src/stylesheets/shared/sidebar.scss
Resolves #2152 
Added flexbox to `.sidebar-wrapper` and set the `.sidebar-container` to 100vh.  This lets the sidebar stay the full height of the screen, but adjusts the container size based on the image size in `.sidebar-heading`.  This change was necessary because #2251 only fixed the size problem when there were enough sidebar items to fill the whole height of the window.  If there were less, the sidebar container would shrink to fit them if it had no specified height.
N/A
Admin dashboard:
All Casa Admins dashboard:
=> Add flexbox to .sidebar-wrapper

app/javascript/src/stylesheets/shared/layout.scss, app/views/supervisors/index.html.erb
Resolves #2201 
Removed inline CSS and added in "layout.scss"
Do not affect
No tests, just a minors change in the code.
The same layout as with the inline CSS.
=> Refactor inline css of "supervisors/index.html.erb"

app/views/casa_admin_mailer/account_setup.html.erb
No issue, just a quick typo fix
Previously the email said "your volunteer account" even though this is for admin, and it also had "PG CASA" hardcoded into it.
N/A
How to embed:
=> Fix typos in admin account setup email

app/views/layouts/mailer.html.erb
Resolves #2223
Refactored some CSS from style tag to inline. But "@media" queries can't go in inline form, so they need to stay in style tag.
It will not.
No changes to test.
* After moving CSS o inline:
=> Removes CSS out of style tag

app/javascript/src/case_emancipation.js
Addresses #1602
- Undo previous change from #2269
- Escape message string to prevent HTML injection attacks
- This _actually_ fixes [two of the alerts](https://github.com/rubyforgood/casa/pull/2290/checks?check_run_id=3105970606) 🎉 
N/A
Test introduced in #2269
=> Fix CodeQL alert by escaping HTML message

config/environments/production.rb
Addresses #1834
- Change the logging level in production from `:debug` to `:info` to reduce the size of logs in Heroku
N/A
=> Set production log level to INFO

config/application.rb, config/environments/development.rb, config/environments/production.rb
reverted changes
check if rails root is nil before calling
Tried to enable previews in `production.rb`
=> Email previews for non prod envs

lib/mailers/previews/casa_admin_mailer_preview.rb, lib/mailers/previews/devise_mailer_preview.rb
Resolves #2313 
- select which admin to show an email preview for via user id
- Fixed a Lint error in this commit.
https://github.com/rubyforgood/casa/commit/ea26bb1f5b8bc6a8ef3be4dbd0486bdde9af8dd5
Email Preview
=> Add Params to CasaAdmin Mailer Preview

lib/mailers/previews/volunteer_mailer_preview.rb
Resolves #2310
The case_contacts_reminder method was executing account_setup, fix it to execute case_contacts_reminder.
Mailer Preview
=> fix account_setup -> case_contacts_reminder

.github/workflows/erb_lint.yml, app/views/casa_cases/edit.html.erb, app/views/supervisor_mailer/weekly_digest.html.erb, app/views/supervisors/edit.html.erb, app/views/volunteers/edit.html.erb, config/locales/views.en.yml
N/A
- I noticed that a r[ecent successful erblint GitHub action](https://github.com/rubyforgood/casa/runs/3193964212) actually had failures. I have changed the GitHub action so it will fail the action when this happens.
- If you look at the first commit of this PR, you can see that the action failed correctly.
N/A
N/A
=> Fix erblint github action so it will actually fail

app/views/devise/sessions/new.html.erb
#2397 
All changes have been made on the new session page (login). Removed break lines tags, using [spacing classes](https://getbootstrap.com/docs/5.0/utilities/spacing/) instead helps tweaking more easily; overlapped view within a div with container class since it's [required](https://getbootstrap.com/docs/5.0/layout/containers/) for the grid to work properly; form class has being completed refactored, but it's now able to fit better different resolutions while keeping centralized on user screen.
Not affected.
No new tests are required since it's still keeping the same functionalities.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Fix new session view responsiveness

.github/workflows/docker.yml, docker-compose.yml, spec/support/capybara.rb
Addresses #2246
- This is only the **first** step to fixing these errors. Now, these tests pass locally. The last step must be related to GitHub actions, but I'm having trouble figuring out the last piece here.
- By using `:selenium_chrome_in_container` and `vnc://localhost:5900`, I was able to spy on the test as it was running in docker. I could see that the download was working correctly. It was downloading to `/home/seluser/Downloads` so I created a shared volume from the host (/tmp/downloads/) to the container
N/A
The existing tests pass locally!
=> Fix file download tests in docker (locally)

app/javascript/src/select.js
Resolves #2396
- Fix the dropdown search by removing the custom matcher and let select2 do what it already knows how to do.
N/A
n/a
=> Fix dropdown search in Manage Cases section

config/locales/views.en.yml
Resolves #2411
It fetches the correct local for the form when an admin is being edited
- no test for that :(
=> Show activated / deactivated text when activating / deactivating admin

app/models/casa_case.rb
`past_court_dates.order("date").last` reduces the amount of database queries needed
```
irb(main):003:0> CasaCase.first.past_court_dates.order("date").last
CasaCase Load (0.5ms)  SELECT "casa_cases".* FROM "casa_cases" ORDER BY "casa_cases"."id" ASC LIMIT $1  [["LIMIT", 1]]
PastCourtDate Load (37.6ms)  SELECT "past_court_dates".* FROM "past_court_dates" WHERE "past_court_dates"."casa_case_id" = $1 ORDER BY date DESC LIMIT $2  [["casa_case_id", 21], ["LIMIT", 1]]
=> nil
irb(main):005:0> CasaCase.first.past_court_dates.where(date: CasaCase.first.past_court_dates.select("MAX(date)"))[0]
CasaCase Load (0.8ms)  SELECT "casa_cases".* FROM "casa_cases" ORDER BY "casa_cases"."id" ASC LIMIT $1  [["LIMIT", 1]]
CasaCase Load (0.3ms)  SELECT "casa_cases".* FROM "casa_cases" ORDER BY "casa_cases"."id" …
```
=> reduced database query count for latest_past_court_date

.github/workflows/docker.yml
Resolves #2246
Resolves #2333
- The download tests were failing in docker bc the runner did not have a `tmp/downloads/` folder so the docker volume was not mounted to anything on the runner. I changed the GitHub action to create the folders with write permissions before spinning docker up.
n/a
all tests pass now in CI!
=> File download tests in docker

db/seeds/db_populator.rb
Resolves #2430
- In `create_cases`, if there was already a CasaCase that existed for a generated case_number, that case would be used to generate volunteers. But since that CasaCase was not just created with the script, the casa_org was not correct with what was given as a param to the volunteer. So I fixed this by using `new_casa_case.casa_org` as the param so it's always the correct organization.
N/A
I could reliably get `seed_spec.rb` to fail roughly 1 in 5 times that I ran it locally. I could never get it to fail after this change.
=> Fix flaky seed test

app/views/reports/index.html.erb
Resolves #2384
- Added a class to give top and bottom margin to `card-container` on Export Data page
n/a
n/a
=> Add spacing around Mileage Report button box

config/environments/development.rb
Resolves #2457
Added new configuration option in development environment. This options adds HTML comments to the rendered output indicating where each template begins and ends.
None affected
Manually
=> Enable annotate_rendered_view_with_filenames in development

spec/support/capybara.rb
Resolves #2512
Replaced driver initialization `option` parameter in favor of `capabilities` as indicated in the depreciation warning
No permissions affected
Manually
=> Fix selenium depreciation warning

app/javascript/src/stylesheets/shared/layout.scss, app/views/casa_cases/show.html.erb
Resolves #2495
Modified styling of Case Details buttons so they top align
- Volunteer permissions: na
- Supervisor permissions: na
- Admin permissions: na
only styling changes
How to embed:
=> Top Aligns Case Details Buttons

package.json, yarn.lock
https://docs.stimulusreflex.com/hello-world/setup#heads-up-issue-with-webpacker
This was not caught by ci because we only run docker in ci, not the webserver. Maybe we should change that...
=> fix webpacker server issue

.github/workflows/yarn_lint_and_test.yml, package.json
Running the js unit tests don't lint before hand
Having it lint before hand makes writing jest tests really slow
=> removed lint from js unit test script

app/javascript/src/casa_case.js, app/javascript/src/stylesheets/pages/casa_cases.scss
Resolves #2383
- Added javascript (sorry, I couldn't find a way around this) that increases the court mandates textarea depending on how much text it contains
- Updated the styling of the implementation status dropdown and delete button to align better with a larger textarea (I can remove this if you don't agree)
N/A
- could not find a straightforward way to test this in capybara unfortunately
=> Increase court mandates textarea size

app/javascript/src/dashboard.js
Resolves #2695
As asked in #2695, I changed the default sort in volunteer table
- Volunteer permissions: nothing
- Supervisor permissions: They will see with new sort settings as default
- Admin permissions: They will see with new sort settings as default
How to embed:
=> change volunteer table order default

app/controllers/case_court_reports_controller.rb, app/controllers/concerns/accessible.rb, app/controllers/reimbursements_controller.rb, app/helpers/template_helper.rb, app/helpers/ui_helper.rb, app/models/case_contact.rb, app/views/reimbursements/_needs_review.html.erb, app/views/reimbursements/_table.html.erb, app/views/reimbursements/index.html.erb, config/routes.rb, db/migrate/20200329050100_create_casa_cases.rb, db/migrate/20200329062155_devise_create_users.rb, db/migrate/20200329064203_add_role_to_user.rb, db/migrate/20200329071025_change_casa_case_teen_to_required.rb, db/migrate/20200329071327_change_casa_case_number_to_required.rb, db/migrate/20200329071626_add_unique_index_on_case_case_number.rb, db/migrate/20200329074655_create_supervisor_volunteers.rb, db/migrate/20200329081206_create_case_assignments.rb, db/migrate/20211023165907_add_reimbursement_complete_to_case_contacts.rb, db/schema.rb
Resolves #2762
Developed view for reimbursements review according to [designs](https://www.figma.com/proto/HBcfH4G9W2pD8psX67orhg/CASA-Redesigns?page-id=30%3A267&node-id=32%3A2&viewport=345%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=67%3A202&show-proto-sidebar=1)
Did not implement:
- fields: expense type, description, amount calculation (currently the field displays mileage)
- pagination
- search
- filter by buttons
Not affected
[In progress]
=> Add Reimbursements Data to Needs Review Tab 

app/views/casa_cases/_form.html.erb
Resolves #2800 
Makes case number field required, avoiding to send a request.
Should I test this?
How to embed:
=> Makes case number required when creating new casa cases

app/views/supervisors/index.html.erb
1. Fixed invalid HTML: "li" outside of "ul" and extraneous "a" tags.
2. Standardized checkbox + label HTML for checkboxes.
Resolves #2906
=> Cleaned up Status filter on supervisors index.

app/views/casa_orgs/edit.html.erb
By restricting the file field to png, gif, and jpeg we should be able to
avoid issues with problematic file types being uploaded as logos.  This
needs to be supplemented with a check on the back end, possibly using a
gem such as activestorage-validator.
Resolves #2909
=> Added "accept" attribute to org logo field.

app/views/casa_cases/_form.html.erb, app/views/casa_orgs/edit.html.erb, app/views/contact_type_groups/_form.html.erb, app/views/contact_types/_form.html.erb, app/views/hearing_types/_form.html.erb, app/views/judges/_form.html.erb, app/views/mileage_rates/_form.html.erb
This change moves all checkbox + label pairs to the standard Bootstrap 4 layout - checkbox before label and each with "form-check-input" or "form-check-label" class.  Additionally, it is embedded in a div with "form-check" class.
=> Adds basic Bootstrap 4 styling for all check boxes.

db/schema.rb
Seems to have fixed itself when running migrations locally.
Hopefully it doesn't go back to the other way.
No official issue, but here's the issue that was opened up on paper trail for the weirdness:
https://github.com/paper-trail-gem/paper_trail/issues/1347
=> fix weird t.string `"{:null=>false}"` bug

db/seeds/db_populator.rb
Resolves #2838 
Now when seeding it checks if the "volunteer1@example.com" has a transition age youth case, if not it will create at least one.
It will not.
Just replant the database
=> Improve QA seed for volunteer1 

.github/workflows/add-help-wanted-labels.yml
Resolves #2634
- add option to manually run the bot
- number of cards issues to label no longer limited to 100
- process exits on fatal errors
- columns can be specified using project name and column name
- a summary of labeling and errors are printed in the output
- documentation for code and bot usage
Manual runs at https://github.com/FireLemons/gh-actions-sandbox/actions/workflows/add-help-wanted-labels.yml
=> update bot and add manual run option

app/views/casa_cases/_court_dates.html.erb
Resolves #2953 
Added the name of hearing types (when not nil) to displayed court_dates listed in a casa_case's show page.
Found no existing tests for casa_case show page. Assumed they were unnecessary for render only view.
`![yay](https://media.giphy.com/media/Ge86XF8AVY1KE/giphy.gif)`
=> Added hearing type to court dates list.

app/views/court_dates/_form.html.erb
Resolves #2932 
I changed the select boxes to a calender because the issue asked for it
- Volunteer permissions:  no affect
- Supervisor permissions: no affect
- Admin permissions:  no affect 
it not tested because its a UI change and I do not how to test it.
https://media.giphy.com/media/h36vh423PiV9K/giphy.gif
=> Switch to use date picker on New Court Date page

app/javascript/src/stylesheets/pages/supervisors.scss, app/views/supervisors/index.html.erb
Resolves #2958
Updated the bar graph styles on the supervisor index page to make it clearer.
It won't
Only style changes so tested manually.
=> Tweak bar graph styles on supervisor index

app/javascript/src/stylesheets/pages/supervisors.scss, app/javascript/src/stylesheets/shared/layout.scss, app/views/supervisors/index.html.erb
- Made supervisor legend text larger
- fixed non rounded corners for stat bars with only green or red bars
- minimized code
- fixed filter dropdown buttons not being vertically aligned for entire site
- if a supervisor has no volunteers, text now shows up explaining so
- fixed transition aged youth count on new line in mobile view 
Manually
How to embed:
=> Rounded corners on supervisor bars fix

app/views/volunteer_mailer/account_setup.html.erb
Resolves #3122
Add youtube link to volunteer intro mailer
Because a stakeholder asked for it
=> Add youtube link to volunteer intro mailer

app/decorators/casa_case_decorator.rb, app/javascript/src/addToCalendarButton.js, app/views/casa_cases/_calendar_button.html.erb, app/views/casa_cases/show.html.erb
Resolves #3093 
Calendar invite dates were previously incorrect due to:
1. A timezone issue resulting from using `format: :default` instead of `format: :long`; and
2. The Google calendar end date being *exclusive* for all-day events and thus needing to be adjusted
(see the Recommended answer here: https://support.google.com/calendar/thread/128416249/calendar-url-generator-which-parameters?hl=en)
Manual testing (had to verify correct dates on external site)
=> Fix incorrect calendar invite dates

.github/workflows/codeql-analysis.yml, .github/workflows/cypress.yml, .github/workflows/docker.yml, .github/workflows/erb_lint.yml, .github/workflows/factory_bot_lint.yml, .github/workflows/rspec.yml, .github/workflows/ruby_lint.yml, .github/workflows/security.yml, .github/workflows/spec_checker.yml, .github/workflows/yarn_lint_and_test.yml
- Fixed `.md` glob pattern
- Limit erb linter to `.erb` and `.html` file extensions
- Limit yarn linter to only `.js` and  `.jsx` file extensions
You can check the `.md` changes at https://globster.xyz/
=> Limit linters with file extensions

.standard.yml
standardrb no longer looks in the storage folder
The storage folder can actually reach a few MB in size
=> ignore storage folder locally for standardrb

.github/workflows/add-labels-based-on-column.yml
ensure all issues in the not ready to build column has the not-ready-to-build label
Nope
=> auto label not ready to build issues

app/views/casa_cases/index.html.erb, app/views/reimbursements/_table.html.erb, app/views/volunteers/index.html.erb
Resolves #3323
Fix table overflow sizing for the casa_cases, reimbursements, and volunteers tables.
When the window was not wide enough, some larger tables were overflowing past their parent card div. The simple fix implemented here is to wrap the table in a div with bootstrap's table-responsive class which makes it automatically scroll horizontally as needed: https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables
Manual testing in UI only.
<details>
<summary>Before - Volunteers Table...</summary>
<br>
</details>
<details>
<summary>Before - Cases...</summary>
<br>
</details>
<details>
<summary>Before - Reimbursement Queue...</summary>
<br>
</details>
What gif best describes your feeling …
=> Fix table overflow styling

.github/workflows/after-deploy.yml
Remove code to prevent bot script from being run if no recent deploy occurred for debug
=> always run bot script for debug

app/controllers/reimbursements_controller.rb
Resolves #3377 
Eager load associations to prevent N+1 queries
None affected
Not tested, just mannually reviewed
Before
After
=> Speed up Reimbursement Queue

app/views/case_contacts/_case_contact.html.erb, app/views/case_contacts/_followup.html.erb
Resolves #3369
The delete button didn't belong to the same wrapping context of the buttons to its left. I just moved the delete button to the same wrapping div and made sure they were equally spaced.
Test's not applicable
How to embed:
=> Fix delete button wrapping on some case contacts on a casa case page

app/controllers/casa_cases_controller.rb, app/models/casa_case.rb
Resolves #3368
Previously IDs were displayed. Now I am displaying the names associated.
In a seeded local, 
- navigate and edit a case details. 
- Add a few Contact Types in this screen 
- Click button to select update
How to embed:
=> 3368 ContactType updates to Cases show ContactType names instead of ids

app/views/all_casa_admins/edit.html.erb
Resolves issue #3439
We replaced a call to t() with the text "Email".
How to embed:
=> Update t() in all_casa/admins/edit view

app/views/all_casa_admins/casa_admins/edit.html.erb
Resolves #3436 
Replaced locale strings in the casa admin edit view to make the code more understandable and maintainable
Loaded page on main, located email and warning text. Made changes and reloaded the page, and verified that the text appeared the same.
What gif best describes your feeling working on this issue? 
=> Replace locale strings in casa admin edit view

app/views/casa_cases/edit.html.erb
Resolves #3453 
Removed the usage of t() in `app/views/casa_cases/edit.html.erb` and replaced it with the string found in `config/locales/views.en.yml`
This will simplify our templates and make it easier to maintain the code going forward.
How to embed:
=> Railsconf 15: update t() in app/views/casa_cases/edit.html.erb

app/views/all_casa_admins/new.html.erb
Resolves #3440
Replaced `I18n.t` call for `common.email` with the actual text `Email`
How to embed:
=> Updated "common.email" translation with "Email"

app/views/casa_org/_hearing_types.html.erb
Remove localization from _hearing_types.html.erb 
Resolves #3459 
Removed translation method and replaced with the English translation
Ran locally and manually tested changes
How to embed:
=> Issue 25: Remove localization

app/views/casa_cases/_volunteer_assignment.html.erb
Resolves #[3542](https://github.com/rubyforgood/casa/issues/3452) (RailsConf 14)
Replace localization method calls with string literals in app/views/casa_cases/_volunteer_assignment.html.erb
No effect on permissions
=> Replace localization method calls with string literals in the volunteer assignment view

app/views/casa_admins/edit.html.erb
Resolves #3442
Replaced uses of t() in casa_admins/edit.html.erb with a hardcoded English string
No effect on permissions.
=> update t() in casa admin edit view #3442

app/views/contact_type_groups/edit.html.erb
Found in config/locales/views.en.yaml:
```
...
contact_type_groups:
new:
title: New Contact Type Group
edit:
title: Edit Contact Type Group
form:
active: Active
```
Closes: #3474
Resolves #3474
Nothing user facing for our users (non-international, only English). Should just show "Edit Contact Type Group" on contact_type_groups/edit.
It doesn't.
It's a view, it doesn't seem to be tested from the request tests, but I also think it'd be kinda overkill and can just be validated visually.
Internet is kind of janky, but will test and attach screenshot once I build the codebase
I am old and don't know how to use emojis …
=> contact_type_groups/edit: Just use string, instead of l18n file

app/views/casa_admins/_form.html.erb
Resolves #3441
Updating `t()` to English text in `app/views/casa_admins/_form.html.erb`
Checked the site in development & passed existing tests
How to embed:
=> [RailsConf] Update View to replace t() with english text

app/views/case_court_reports/index.html.erb
Resolves #3493
Replace localization method calls with string literals in app/views/case_court_reports/index.html.erb
N/A
=> Replace localization method calls with string literals in app/views/case_court_reports/index.html.erb

app/views/contact_types/_form.html.erb
Resolves #3497
Replace localization method calls with string literals in app/views/contact_types/_form.html.erb
N/A
=> Replace localization method calls with string literals in app/views/contact_types/_form.html.erb

app/views/contact_type_groups/_form.html.erb
Resolves #3494
Replace localization method calls with string literals in app/views/contact_type_groups/_form.html.erb
N/A
=> Replace localization method calls with string literals in app/views/contact_type_groups/_form.html.erb

app/javascript/src/stylesheets/shared/footer.scss, app/views/layouts/footers/_not_logged_in.html.erb, config/locales/views.en.yml, public/sms-terms-conditions.html
Resolves #1791
Users can view their `SMS Terms & Conditions` in the site footer
- Made SMS terms of service link
- Created  `sms-terms-conditions.html` and added to `/public`
- Volunteer, Supervisor, Admin permissions: n/a
https://user-images.githubusercontent.com/58965520/169710205-f0d6570c-9278-4b42-91e5-6ea076cba47f.mov
=> Feature/1791 Users can view their SMS Terms & Conditions

app/views/casa_cases/_court_dates.html.erb
Resolves #3445
app/views/casa_cases/_court_dates.html.erb - translation strings replaced with straight - up strings
- Volunteer permissions: nah
- Supervisor permissions: nah 
- Admin permissions: nah
How to embed:
=> removed translations strings from 'casa_cases/_court_dates'

app/javascript/src/import.js
Resolves #3547 
* Changed `import.js` to only add event listeners when on import page to avoid undefined errors in console on other pages
* Tests for `import.js` were already written in #3380 
N/A
=> fix import js to only run when import elements are present

app/views/case_contacts/_case_contact.html.erb
Resolves #3485 
Replaced translations `t()` with text
- Admin permissions: no effect
n/a
n/a
How to embed:
=> Update translations in app/views/case_contacts/_case_contact.html.erb

Gemfile.lock
It looks like https://github.com/rubyforgood/casa/commit/1c9d571c4efb012fcae12d600894936bd83691f4 removed some platforms. We'll probably need to add `arm64-darwin-21` as well.
=> Add x86_64-darwin-21 platform

app/controllers/emancipations_controller.rb
Resolves #3332
The filename was not set to reflect the case number. This was a requested feature. 
Tested functionally. 
**Note: I did not add tests because this is a rails method with an additional parameter, and that seems unnecessary.**
How to embed:
=> 3332: Add Case Number to Filename When Downloading Emancipation Checklist

app/models/case_assignment.rb, config/application.rb
Resolves #3314 
This PR is to enable the listed config option, and remove the inverse call from an association on the `case_assignment` model that causes tests to fail. 
This is a spec fix that didn't require changes to the spec, but to the model being tested due to config change. 
How to embed:
=> #3314 Enable active_record.has_many_inversing config option

app/views/casa_cases/index.html.erb
Resolves #3590
Did some refactoring to make maintaining the code easier. 
n/a
Before:
After:
=> Issue #3590 remove t in app/views/casa_cases/index.html.erb

app/views/supervisors/new.html.erb, app/views/volunteers/_form.html.erb
Resolves #3609 
This PR adds a telephone field when creating a new vonlunteer or supervisor.
Supervisor:
Volunteer:
=> feat: add telephone field to volunteer and supervisor form

Gemfile.lock
As stated in
https://github.com/arzezak/casa/commit/c6fabd410012fdd69e3ab6fd2ddbd1db7df7b95f,
we're adding back the arm64 platform in order to bundle on M1 macs.
=> Add arm64-darwin-21 platform back

.github/workflows/docker.yml, .github/workflows/rspec.yml, Gemfile.lock
Added section to github actions for rspec and docker that will save the outputs on the Capybara screenshots so they can be viewed upon failure.
=> Capture selenium screenshot output so they are viewable in Github Actions

app/javascript/src/require_communication_preference.js
Resolves #3710
This component behavior was really weird (as you can see on the video), so a lot of code changed.
I'm a backend developer, so please forgive me for any mistakes in this PR.
Fixed communication preferences checkboxes behaviour:
Tests weren't implemented due to time, but i plan on work on them next week.
Original behavior:
https://user-images.githubusercontent.com/36737050/176967702-bdb83109-e42e-4f06-a952-c8c07540f9e4.mp4
Fixed behavior:
https://user-images.githubusercontent.com/36737050/176967773-a6f21643-fa41-465d-a5b7-a1bc39be05fb.mp4
=> fix checkbox click behaviour

app/javascript/src/require_communication_preference.js
Resolves #3709
Change communication preference popup error text per issue request.
Manual testing only.
How to embed:
=> Change communication preference text

app/helpers/sms_body_helper.rb
Removed line `breaks and dash` from case_contact_flagged_msg body. Added during development so the text message displays nicely on a Twilio trial account, but this will cause odd line breaks and a dash in the message body outside of using a trial account. 
- Volunteer, Supervisor, Admin permissions: n/a
n/a
=> Updated case_contact_flagged_msg body

app/controllers/case_contacts_controller.rb
…at case contact form will submit when additonal expenses input is left blank
Resolves #3783 
I dug around in pry a bit and realized something was glitching in a conditional statement of the create_case_contact_for_every_selected_casa_case method. It looks the the instance variable was not defined or accessible so I updated it to the local variable defined in the method and the form began to save regardless of if an additional expense was added. 
I tested this manually. All other tests that were previously in the case_contact_controller spec still pass though.
=> Case contacts save if additional expenses are blank - updated case contact controller

app/services/court_report_due_sms_reminder_service.rb, app/services/no_contact_made_sms_reminder_service.rb, app/services/sms_reminder_service.rb
Replace class with only class methods with module ``` extend self ```
"Reason is that Class is too heavy for creating only class methods. As we discussed earlier a class is supposed to have both data and behavior. If the only thing you care about is behavior then ruby suggests to implement it as a module."
more details: [https://www.bigbinary.com/blog/extend-self-in-ruby](https://www.bigbinary.com/blog/extend-self-in-ruby)
=> replace class with method in class << self to modules

Gemfile.lock
This PR has the goal to fix web mock version. Because current version can no longer be found in that source
link: 
```
Fetching gem metadata from https://rubygems.org/.........
[215](https://github.com/rubyforgood/casa/runs/7778570716?check_suite_focus=true#step:4:216)
Your bundle is locked to webmock (3.16.0) from rubygems repository
[216](https://github.com/rubyforgood/casa/runs/7778570716?check_suite_focus=true#step:4:217)
https://rubygems.org/ or installed locally, but that version can no longer be
```
=> fix webmock version

.github/workflows/issue-auto-unassign.yml
Override warning_inactive_message from https://github.com/rubyforgood/unassign-issues to make the bot instructions more clear for contributors
=> configure unassign bot

lib/tasks/deployment/20220825005830_enable_show_additional_expenses.rake
Resolves #3815 
This PR has the goal to create after party task, to enable show additional expenses feature.
=> add after party task to enable show additional expenses feature

app/assets/stylesheets/pages/patch_notes.scss, app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/async_notifier.js, app/javascript/src/type_checker.js, app/views/all_casa_admins/patch_notes/_patch_note.html.erb, app/views/all_casa_admins/patch_notes/index.html.erb
Related to https://github.com/rubyforgood/casa/issues/3651
- Patch notes can be deleted
- fixed a key reference error for json responses
- Created a module for parameter type checking
- Errors that crash patch note page js are printed to the console
No
Not yet
=> Site update notes

app/controllers/other_duties_controller.rb
Resolves #3785
> We wrote [PR 3800](https://github.com/rubyforgood/casa/pull/3800) to display a message when no other duties were present. The view was checking a condition that was previously not set. This PR moves the logic into the controller and sets that variable. 
> We are working on controller tests but wanted to get this fix ready since it was a bug in production.
See Above
How to embed:
=> Display message when no other duties are found for volunteers

app/views/layouts/_sidebar.html.erb
Resolves #3945
Added link_to with the logo image with path "/" to redirect to root path as shown in example below
```diff
-<%= image_tag("default-logo.png"), %>
to
+<%= link_to image_tag("default-logo.png"), "/" %>
```
Should not have any impact on any permissions
- Volunteer permissions
- Supervisor permissions
- Admin permissions
Since I'm on windows I haven't tested it yet, but its a very basic change and I hope a maintainer can help me with tests :)
I could install ruby on rails through other mediums if necessary.
=> Logo linked to website root page

README.md, doc/WSL_SETUP.md
No official issue.
Newer versions of Ubuntu require the chromium snap when trying to run chromium. 
This presents an issue for anyone running Ubuntu on WSL because snap requires Systemd to be running as the main process, but WSL has a different main process to provide for interoperability with Windows (see [this SO answer](https://stackoverflow.com/a/71722804)).
This PR adds instructions for how to download and install Google Chrome and the appropriate chromedriver for WSL Ubuntu users who need to do it entirely via the linux command line.
Manual testing. 
The test suite failed and returned a bunch of errors regarding the chromium snap prior to running through these steps. 
After these steps, test suite …
=> update WSL docs for installing chrome

app/assets/stylesheets/pages/patch_notes.scss, app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/type_checker.js, bin/asset_bundling_scripts/build_js.js
Related to #3651
- New patch notes can be deleted(the yellow ones)
- Can enter into edit mode
- Can cancel out of edit mode
Edit Before
Edit Mode
Edit Changes
Edit Cancel
Not yet
=> Can delete new patch notes and the editing patch note UI works

app/assets/stylesheets/shared/async_notifier.scss, app/javascript/src/all_casa_admin/patch_notes.js, app/javascript/src/async_notifier.js
Related to #3651
Required user to click several times to delete a patch note
Gave async notifier a higher z-index 
Not yet
=> confirm before delete

app/views/casa_cases/_volunteer_assignment.html.erb, app/views/shared/_manage_volunteers.html.erb, app/views/supervisors/edit.html.erb
Resolves #3112
Refactored out the common elements of the "Manage Volunteers" section for the Casa Case and Supervisor edit pages into a shared partial. DRYs up the code a little bit. 
Unfortunately, not as much of the table code was reusable as I'd hoped since one page was a table of case assignments, while the other was a table of the supervisor's volunteers. There might be another way to refactor this even more, but it would likely be a much more invasive change.
Existing tests all pass.
Looks exactly the same 🙂 
How to embed:
We are very interested in your …
=> 3112 Manage volunteer assignments partial

app/views/judges/_form.html.erb
Resolves #3921
Removes calls to `t()` on the judges form.
N/A
Existing tests
=> Remove Translations 5: Judges form

app/views/layouts/application.html.erb
Resolves #3927 
Updated the following:
application:
javascript_instrucion:
enable: Please enable javascript
require: This app requires javascript to work
How to embed:
`![alt text](https://media.giphy.com/media/Kan0fXfAiFuiiB59vT/giphy.gif)`
=> Resolves 3927 Replace t() with string

app/views/layouts/footers/_logged_in.html.erb, app/views/layouts/footers/_not_logged_in.html.erb
Resolves #3928 
Updated the following:
footers:
logged_in:
built_by: Built by
link:
report_site_issue: Report a site issue
sms_terms_and_conditions: SMS Terms & Conditions
ruby_for_good: Ruby For Good
the footer when logged in: 
How to embed:
=> 3928 remove footers logged in translations

app/views/learning_hours/index.html.erb
Resolves #3933 
Updated:
learning_hours:
index:
heading:
name: Title
type: Learning Type
occurred_at: Date
time: Time Spent
action: Action
title: Learning Hours
Sadly, I cannot access to take screenshots
How to embed:
=> Resolves 3933 Replace t() with string

app/views/volunteers/index.html.erb
Resolves #4021
Moved the "pick displayed columns" button.
It won't
Is it ok like that?
=> move pick displayed columns button

app/javascript/src/require_communication_preference.js
Resolves #4035 
Used the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to stop throwing an error when `emailToggle` is `null` or `undefined`.
Not tested, as the functionality is part of the JavaScript language.
**Before - email toggle hidden**
**After - email toggle hidden**
Would've been useful to have reproduction steps, or the following details:
- which page it's happening on
- when is it happening?
- which user to log in with to see the error happen
=> prevent null reference error when emailToggle not present

README.md
Resolves #4086
- Remove the broken link to Cypress document.
- View Readme and the Cypress link should not be there
How to embed:
=> Fix broken link to Cypress in README.md

app/assets/stylesheets/pages/case_contacts.scss, app/javascript/src/case_contact.js, app/models/user_reminder_time.rb, app/views/case_contacts/_form.html.erb
Add simple 'Highlight' button and placeholder modal to new case contact form. Actual implementation of highlight feature to follow.
Resolves #3566
Add 'highlight button' to New Case Contact Form
Add simple 'Highlight' button and placeholder modal to new case contact
form. Actual implementation of highlight feature to follow.
No tests yet. Not sure how/if we do feature specs
=> Add 'highlight button' to New Case Contact Form

app/assets/stylesheets/pages/reimbursements.scss
Resolves #4098
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: input field from reimbursement page was fixed
Only updates scroll style, visual checking.
BEFORE
AFTER
=> fix: fix scroll bar on input field

app/javascript/src/case_emancipation.js
Resolves #4108 
I changed the regex in `case_emancipation.js` to look for both letters and digits because the pathname seems to have changed.
I didn't add any tests for this, but if you think it's important I can try to think of some tests 🙂
=> Updated the regex in case_emancipation.js

doc/DOCKER.md, docker-compose.yml, docker/build, docker/build-assets, docker/build-log, docker/seed, docker/server-log, docker/test-log
This fixes the issue with running docker/build (#4050). However, is docker and the various scripts in the docker directory being used to facilitate easy local development setup, CI, deployment etc.? Depending on the answer we could recommend additional changes and would be happy to issue a follow up PR.
Resolves #4050
- Add `docker/build-assets` to the `docker/build` script to include asset bundling before launching the web server.
- Updated existing docker helper scripts to be more compatible with the `docker/build` command.
- Update docker-compose file to store bundler and yarn packges in persistent volumes. This should speed up local startup times.
- Update the echo output from the various docker/ scripts to have more consistent and concise status updates. …
=> Resolves #4050 Add js and css bundling to docker/build script

app/assets/stylesheets/shared/dashboard.scss, app/assets/stylesheets/shared/layout.scss
Resolves #4200 
Added a margin-bottom to  `app/assets/stylesheets/shared/layout.scss`
=> add margin-top to .dashboard-table-header

Procfile
Removed webpack server command from `Procfile` because we don't use webpack or have it installed  
also cloud66 emailed us a lot about it  
Commit that added it:
https://github.com/rubyforgood/casa/commit/80d497678998b94273a7d13bb300126471664f2b
=> deleted webpack server command from procfile

spec/support/docx_inspector.rb
Resolves #4285
DocxInspector now saves unsorted words lists.
word lists accessors now have a sorted parameter.
```rb
#Use example:
document_inspector.get_word_list_document(sorted: false)
```
It won't
There are no tests, since this is a rspec helper.
This class could be refactored, having a "word_list_contains?(session, str)" instead of one method per session.
If it interests you, I can work on it!
=> Fix DocxInspector "contains_in_order"

app/views/mileage_rates/_form.html.erb, app/views/mileage_rates/edit.html.erb, app/views/mileage_rates/index.html.erb, app/views/mileage_rates/new.html.erb
Resolves [#4321](https://github.com/rubyforgood/casa/issues/4321)
This PR updates the views in the the `/views/mileage_rates` directory to use the new [plainadmin](https://plainadmin.com/) theme.
See https://github.com/rubyforgood/casa/issues/4304 for more context.
The diff on this PR seems to have pretty good test coverage via the existing request tests at `./spec/requests/mileage_rates_spec.rb` and `spec/views/mileage_rates/index.html.erb_spec.rb`. I'm open to adding more test coverage if reviewers are aware of any additional edge cases they'd like coverage for.
I also did manual testing (filling out the form, etc.)
* [Before](https://user-images.githubusercontent.com/1179668/208957780-92914a55-b2fd-4248-9ef8-09cbe7549d5a.png)
* …
=> Add new plainadmin theme to the mileage_rates views

app/views/judges/_form.html.erb
Resolves #4318
This PR updates the views in the the `/views/judges` directory to use the new [plainadmin](https://plainadmin.com/) theme.
* [Before](https://user-images.githubusercontent.com/1179668/208986966-434ec832-e8b6-4a32-96ed-2076e4fcc114.png)
* [After](https://user-images.githubusercontent.com/1179668/208987005-21e66172-a331-4cf4-aec5-a828319440cb.png)
How to embed:
=> Add new plainadmin theme to the judges form

app/views/languages/_form.html.erb
Resolves #4319
This PR updates the views in the the /views/languages directory to use the new [plainadmin](https://plainadmin.com/) theme.
* [Before](https://user-images.githubusercontent.com/1179668/208991777-fb5ccc3b-c0fb-4cff-b183-eb544905dec0.png)
* [After (new)](https://user-images.githubusercontent.com/1179668/208991399-d01fc1ad-ca87-4262-881d-bdbac64d7c16.png)
* [After (edit)](https://user-images.githubusercontent.com/1179668/208991511-4d78a032-61a9-47be-868f-e9e5a70b36c6.png)
How to embed:
=> Add new plainadmin theme to the languages form

app/views/contact_type_groups/_form.html.erb
Resolves #4311
This PR updates the views in the /views/contact_type_groups directory to use the new [plainadmin](https://plainadmin.com/) theme.
* [Before](https://user-images.githubusercontent.com/1179668/208996353-ac9c72c7-c8c3-44a1-a9e5-3cd08bc4ddc1.png)
* [After](https://user-images.githubusercontent.com/1179668/208996405-58fccc96-6c45-4d95-80bf-a8320cf743e5.png)
* [After (form validation)](https://user-images.githubusercontent.com/1179668/208996457-ddb20ed7-ba39-45c1-84a5-e49c4e90377b.png)
How to embed:
We are very interested in your feedback! Please give us some :) …
=> Add plainadmin theme: new contact type group form

app/views/casa_admins/_form.html.erb, app/views/casa_admins/index.html.erb, app/views/shared/_edit_form.html.erb, app/views/shared/_error_messages.html.erb, app/views/shared/_invite_login.html.erb
Resolves #4305 
-Adds plainadmin container wrapper, title wrapper, card wrapper, as well as other plainadmin stylings for casa_admin index and form. 
-Converted shared/_edit_form - /_error_messages - /inite_login style classes to plainadmin ones as well as removing "field" and "form" style classes.
-ran spec/views/casa_admins and all passed!
Admins Index
Admins New
Edit Admins (I added a plainadmin effect for the button so it changes the bg color and font color when hovered, I thought it'd be a cute touch)
Admins New w/ Error
Admins Edit w/Error
How to embed:
`![alt text](https://media.giphy.com/media/1nP7ThJFes5pgXKUNf/giphy.gif …
=> 4305 new theme casa admins pages

app/views/case_court_reports/index.html.erb
Resolves #4308
Refactory case_court_reports index page to use new theme.
- go to Generate Court Report in side menu
=> refactory index.html.erb to new theme

app/views/hearing_types/_form.html.erb, app/views/shared/_error_messages.html.erb
Resolves #4316
This PR updates the views in the `/views/hearing_types` directory to use the new [plainadmin](https://plainadmin.com/) theme.
`hearing_types/new` :
`hearing_types/#/edit` :
=> Add plainadmin theme to hearing_types pages

app/views/checklist_items/_form.html.erb
Resolves #4310
This PR changes the theme for the checklist item new and edit pages.
n/a
Before:
After:
If anything needs to change please let me know.
=> New style for checklist item new and edit pages

app/views/learning_hours/_confirm_note.html.erb, app/views/learning_hours/_form.html.erb, app/views/learning_hours/_update_form.html.erb, app/views/learning_hours/edit.html.erb, app/views/learning_hours/index.html.erb, app/views/learning_hours/new.html.erb, app/views/learning_hours/show.html.erb
Resolves #4320
Html tags and classes to convert existing learning hours pages to use the new theme.
Visually tested.
How to embed:
=> Adds new theme to learning hours pages

app/helpers/sidebar_helper.rb, app/views/layouts/_sidebar.html.erb
Resolves #4331 
`menu_item` method of sidebar helper and sidebar partial to show correct active link.
Visually.
How to embed:
=> Updates helper methods and sidebar partial to show correct active links

app/views/casa_org/_languages.html.erb
Moved language description out of new page to under section header.
This is rebased with main
=> moved language description to under language section

app/views/casa_org/_contact_type_groups.html.erb, app/views/casa_org/_contact_types.html.erb, app/views/casa_org/_hearing_types.html.erb, app/views/casa_org/_judges.html.erb, app/views/casa_org/_languages.html.erb, app/views/casa_org/_sent_emails.html.erb, app/views/casa_org/edit.html.erb
Resolves #4307
This PR updates the views in the `/views/casa_org` directory to use the new [plainadmin](https://plainadmin.com/) theme.
`/views/casa_org` :
=> Add plainadmin theme to case_org pages

app/views/contact_type_groups/_form.html.erb
Resolves #4281 
Contact type groups form.
- Volunteer permissions: No effect
- Supervisor permissions: No effect
- Admin permissions: No effect
Visually
How to embed:
=> Adds description to contact type groups' form.

app/views/imports/_cases.html.erb, app/views/imports/_csv_error_modal.html.erb, app/views/imports/_sms_opt_in_modal.html.erb, app/views/imports/_supervisors.html.erb, app/views/imports/_volunteers.html.erb, app/views/imports/index.html.erb
Resolves #4317 
Updates to (mostly) CSS classes and a bit of the tag structure to move over to the new theme.
Visually tested.
Of course if there's anything you'd like me to improve upon/fix, I'd be more than happy to do so :)
=> Convert imports pages to plainadmin theme

app/views/court_dates/_form.html.erb, app/views/court_dates/edit.html.erb, app/views/court_dates/new.html.erb, app/views/court_dates/show.html.erb
Resolves #4313
This PR updates the views in the `/views/court_dates` directory to use the new [plainadmin](https://plainadmin.com/) theme.
`/views/court_dates/new` :
`/views/court_dates/show` :
`/views/court_dates/edit` :
=> Add plainadmin theme to court_dates pages

app/views/layouts/_sidebar.html.erb
Hey @seanmarcia, here is the fix you requested.
Issue description: [Fix requested in comment](https://github.com/rubyforgood/casa/pull/4387#issuecomment-1369111839)
CSS class for not showing the dropdown expanded by default.
Visually
How to embed:
=> Don't show group actions expanded by default

app/views/notes/edit.html.erb, app/views/notifications/index.html.erb
Resolves #4332
Update theme for notes and notifications views
- Volunteer permissions: No changes
- Supervisor permissions: No changes
- Admin permissions: No changes
Verified locally. Theses changes are CSS-based and so probably should not be tested in an automated fashion.
Please note the following issues:
1. The footer styling is not consistent with the rest of the site (background color)
2. I was not able to test notifications since creating them locally is a pain (testing on heroku should make this easier)
How to embed:
=> Update theme for notes and notifications

app/javascript/src/sidebar.js
Hey @seanmarcia, this is regarding the group actions in the sidebar. Now it will be expanded when any of the child is active.
I tried the approach of making it like `active_class` in the sidebar helper but found that an additional `show` class was added by javascript on render. It was beyond the control of the helper method.
So I took the javascript approach. Let me know if any changes are required. 
- Volunteer permissions: No effect
- Supervisor permissions: No effect
- Admin permissions: No effect
Visually.
How to embed:
=> Show dropdown open when any of the child anchor is active

Gemfile.lock, app/views/judges/_form.html.erb, app/views/languages/_form.html.erb
Resolves #4435 
The previous button styling was from prior theme, updated to have submit buttons contain small sizing and checkmarks on the new judges and language pages. 
No permissions should be affected; just visual changes.
Tested in `spec/views/languages/new.html.erb_spec.rb` and `spec/views/judges/new.html.erb_spec.rb`
=> Updated submit button icons

app/javascript/src/dashboard.js
When one the datatable's ajax requests returns with status 401(Unauthorized) instead of refreshing the page, it displays the error as an alert and prints it to console
nope
=> Remove refresh on unauthorized response

db/migrate/20230121174227_remove_court_data_from_casa_cases.rb, db/schema.rb
Resolves #2907
Removes `court_date` field from `casa_cases` table since it is no longer being used. This is part 1 of 2 PRs, the [other](https://github.com/rubyforgood/casa/pull/4465) will remove `court_date` from `ignored_columns` in the `CasaCase` model. This migration but be deployed and ran before https://github.com/rubyforgood/casa/pull/4465 is deployed.
N/A
N/A
N/A
How to embed:
=> 2907: Create migration to remove court_date from casa_cases table

app/models/casa_case.rb
Resolves #2907
Removes `court_date` from `ignored_columns` in the `CasaCase` model since its no longer being used. This PR is a continuation of https://github.com/rubyforgood/casa/pull/4464 and should not be deployed until https://github.com/rubyforgood/casa/pull/4464 has been deployed and the migration has been ran.
N/A
N/A
N/A
How to embed:
=> 2907: Remove court_date from ignored_columns in CasaCase model

app/javascript/src/case_contact_autosave.js
Resolves #4236
The 'case_contact_autosave.js' autoload was overwriting checked casa cases.
Now, if the box was already checked it won't uncheck it.
It won't
Previously created case_contact in "CINA-08-1002"
[Screencast from 03-01-2023 13:05:54.webm](https://user-images.githubusercontent.com/36737050/210395224-52ea9996-7698-46fd-8679-f626900ee33d.webm)
=> Remove overwriting of already checked checkboxes

app/javascript/src/reimbursements.js, package.json, yarn.lock
Resolves #4570
- fixed a bug where the reimbursement date could not be parsed on firefox
- removed an unnecessary dependency 
Before
After
=> Fix date parsing reimbursements firefox

app/views/layouts/_header.html.erb
Resolves #4549 
The anchor tag in sidebar partial.
- Volunteer permissions: No effect
- Supervisor permissions: No effect
- Admin permissions: No effect
Visually.
NA
How to embed:
=> Fixes edit organization link in admin header

app/assets/stylesheets/shared/noscript.css, app/views/layouts/application.html.erb
Resolves #4568
An issue was identifed with the noscript tag wrapper not appearing on Linux versions of Chrome/Firefox, but the inner content was still rendering.  This fix moves the styling from the noscript tag to an inner div tag to ensure the styling appears.
Moved the styling from the noscript tag to the inner div.
Added the plainadmin alert, alert-danger, and alert-heading classes to their respective divs.
Changed the noscript tag selector to a class.
Changed the noscript styles to move the notification in to a more prominent position in the middle of the page and made it larger.
- Volunteer permissions: unaffected
- Supervisor permissions: unaffected
- Admin permissions: unaffected
Unable to test noscript style existence. …
=> Fix the noscript style bug and update notification styling

app/assets/config/manifest.js, app/views/static/index.html.erb
Resolves #4567
- Added a `noscript` tag to the static page
- Added noscript.css to static page to style the tag
How to embed:
=> Ensure warning for disabled js on landing page

app/views/all_casa_admins/patch_notes/_patch_note.html.erb
Resolves #4562 (new theme)
edit and delete button patch notes were not working
- Admin permissions: patch notes
manually tested
Before:
After clicking delete:
=> edit and delete button patch notes

app/models/all_casa_admin.rb, app/views/all_casa_admins/passwords/new.html.erb
Partially resolves #4652
Removed the phone number validation from all_casa_admins reset password since they can't be texted
The `phone_number` column is ignored at the moment.
The following [PR](https://github.com/rubyforgood/casa/pull/4661) will be then merged with a migration that will delete the column safely.
- Volunteer permissions: x
- Supervisor permissions: x
- Admin permissions: x
How to embed:
=> 4652: Remove phone number for all casa admin password reset

app/assets/stylesheets/pages/reimbursements.scss
`auto` is better than `scroll` because on some browsers, `scroll` always shows the scrollbar even if you can't scroll
=> change scroll to auto

app/javascript/src/all_casa_admin/patch_notes.js
Resolves  #4662
both buttons are working (delete and edit)
- Supervisor permissions:n/a
- Admin permissions:n/a
manually tested
How to embed:
=> both buttons work

app/views/notifications/_notification.html.erb
Resolves #4679
Use the created_at attribute instead of updated_at in notifications partial/index page.
No tests added here.
I think test coverage will be added by this ticket: https://github.com/rubyforgood/casa/issues/4681
How to embed:
=> use created_at attribute in notifications partial

doc/MAC_SETUP.md
N/A
Adds `yarn install` step to mac setup doc. This was something I bumped into while getting up and running.
N/A
N/A
N/A
N/A
N/A
=> Add js dependency install step to mac setup doc

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
The new theme has been merged and deployed to production, so we no longer need a link to the temp app (which no longer exists anyway).
=> Remove link to new theme from Issue templates

app/views/casa_org/edit.html.erb
… heading and associated checkbox to just above submit button
Resolves #4810 
Added Organization Features heading for the new on/off reimbursement checkbox, and moved both elements down to just above the submit button, with a thematic break in place.
- Admin permissions: affects org/edit route
None required
How to embed:
=> Issue 4810 - add Org Pre

app/views/devise/mailer/reset_password_instructions.html.erb
Resolves #4726
Adds a notice to the password reset email template laying out how long the user has to reset their password.
Devise is configured to expire password reset tokens 6 hours after issuing them. This is set in the initializer at `config/initializers/devise.rb` and is the only condition that causes password reset tokens to expire.
```ruby
config.reset_password_within = 6.hours
```
N/A
Manually
Updated template:
=> Update messaging in password reset email

config/locales/en.yml
Resolves #4808
Small fix to Small fix to 4771 edit profile timestamp #4808 - Added a `space` character between 'at' and the time string.
Before fix:
After fix:
How to embed:
=> Small fix to 4771 edit profile timestamp #4808 - Add space between 'at' and time

config/locales/en.yml
The test at `/spec/system/users/edit_spec.rb:114` is currently breaking the build
removed space padding for a formatted date. The test fails because the browser automatically truncates consecutive spaces
The `%l` option blank pads numbers less than
10, which is causing the spec to be flaky,
and leaves an extra space in the time
display: "May 17, 2023 at&nbsp;&nbsp;3:21 AM". This
change removes the blank padding.
=> Flaky spec fix: Do not use blank padding for hour display

lib/tasks/deployment/20230419224330_backfill_user_prefernce_sets.rake
This is the second Pr out of three to fix issue #2698     -Pr1: [https://github.com/rubyforgood/casa/pull/4769](url)
In this second Pr I am Adding an after party task to backfill the preferences_sets. This is needed because in Pr1 I added a migration to add a new column to this table. 
Ref #2698 
This Pr Adds an after party task to backfill the preference_sets. This is needed because in Pr1 I added a migration to add a new column "table_state" to preference_set
- Supervisor permissions:n/a
- Admin permissions:n/a
N/a ... I think?
How to embed:
We are very interested in your feedback! Please give us some :) …
=> Pr2 for Issue #2698 - Adds a task to backfill user preference sets. 

README.md
Changed the Ruby version in the setup instructions from 3.1.2 to 3.2.2 to match `.ruby-version`.
=> Update README to reflect current Ruby version

app/views/case_contacts/_form.html.erb
=> removed extra margin below additional expense

app/assets/stylesheets/shared/layout.scss, app/views/case_contacts/_form.html.erb
Resolves #4869 
When creating a new case contact, the first section "Select all relevant CASA cases" card can be very large when a supervisor or admin views it (when they are not impersonating a volunteer). To make for a smoother feeling workflow, I housed the selectable cases in a Scroll box 
Have not written a test so far. It is a CSS feature change to one layout file. I can write a `requests` test if needed.
https://github.com/rubyforgood/casa/assets/74928397/7bcd15b9-3d92-40a8-ad93-3df8f19851b5
How to embed:
`![Yes!](https://media.giphy.com/media/3o6UB3VhArvomJHtdK/giphy.gif)`
We are very interested in your feedback! Please …
=> Create a new CSS class and use it to wrap CASA cases list for scrolling

app/assets/stylesheets/pages/casa_cases.scss
Resolves #4853 
Slightly modified the width and aligned the text in the center
just checked visually
How to embed:
=> fix add to calendar button text overflow

.github/workflows/toc.yml, README.md
Resolves #2516 
Added a yml file to configure the doctoc github action
Automatically updated the readme table of content on push
Note: the github token used by the bot needs to be correctly configured for it to work (needs write permission or maybe a github token, see https://github.com/marketplace/actions/toc-generator for more details). It works on my repo, I don't know if it will work on casa
No tests, i saw it work on my local repo
How to embed:
=> Automatically update readme anchors with doctoc

app/views/all_casa_admins/edit.html.erb, app/views/layouts/_header.html.erb, app/views/users/edit.html.erb
Resolves https://github.com/rubyforgood/casa/issues/4936
Applied CSS style with the proper background color for buttons. Also changed the type of "Update Profile" element from input to button.
How to embed:
=> Fix inaccessible background colors for buttons

app/views/layouts/_sidebar.html.erb
Resolves #4925
The logo height in the sidebar partial `_sidebar.html.erb` was updated to match the ratio of the dimensions of the CASA logo provided in the assets folder.
Displayed logo was compared to the CASA logo for proper ratio
=> Update image height to match casa logo aspect ratio

app/views/users/edit.html.erb
Resolves https://github.com/rubyforgood/casa/issues/4952
Added a white background to the card. Modified header to look like other sections.
How to embed:
=> Added white background card to communication preference section

app/assets/stylesheets/application.scss
Resolves #5008 
Removed unused stylesheet import that `yarn build:css:dev` was complaining about.
N/A
No tests required, as this is just a CSS import
_Terminal error before_
_Terminal after_
_Browser error before_
_Browser after_
=> remove unused stylesheet import

db/seeds/db_populator.rb
Resolves #4999
The seeds have been updated to show a `date_in_care` on each `CasaCase`
This PR only touches seeds, so no tests are needed.
To verify that this has worked, run the following commands in your Terminal and make sure the last one returns a date:
=> add random date_in_care to CasaCase seeds

Rakefile
Gem is only installed in dev
Should fix build errors on Heroku:
```
-----> Detecting rake tasks
!
!     Could not detect rake tasks
!     ensure you can run `$ bundle exec rake -P` against your app
!     and using the production group of your Gemfile.
!     rake aborted!
!     LoadError: cannot load such file -- bundler/audit/task
!     <internal:/tmp/build_7d353d22/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
!     <internal:/tmp/build_7d353d22/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
!     /tmp/build_7d353d22/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
!     /tmp/build_7d353d22/Rakefile:8:in `<top (required)>'
! …
```
=> Only require the bundler/audit/task in dev environment

bin/update
nvm is not necessarily required if you are using a different package manager. Remove from `bin/update` so it can run successfully by developers who are not using nvm.
=> Remove nvm use from bin/update file, not necessary

app/models/casa_case.rb, db/migrate/20230729213608_remove_hearing_type_id_and_judge_id_from_casa_cases.rb, db/schema.rb
Resolves #5044
Add migration to remove `hearing_type_id` and `judge_id` columns from `casa_cases` table. Remove mentions of these columns from the codebase.
- Volunteer permissions: X
- Supervisor permissions: X
- Admin permissions: X
N/A
=> Remove hearing_type_id and judge_id from casa_cases table

app/controllers/case_contacts_controller.rb, app/controllers/supervisor_volunteers_controller.rb
Resolves https://github.com/rubyforgood/casa/issues/5056
This PR corrects a typo in the codebase that was affecting the proper functioning of the application. 
The issue was related to the misspelling of 'referrer' in the code. The correct spelling 'referer' has been applied throughout the affected file. 
Additionally, fixes the 'recrusive' typo, replacing it with 'recursive', ensuring the correct behavior in the application.
=> fix typo error

app/javascript/src/dashboard.js, app/views/volunteers/index.html.erb
Resolves https://github.com/rubyforgood/casa/issues/4980
This PR adds an error notification to the preferences saving process. If there's an error while saving preferences, a notification is displayed to the user, and the error message is logged to the console for debugging purposes. 
I tested the changes by simulating user interactions on the frontend. Specifically, I tested the preferences saving process by triggering the saving action and intentionally causing errors. I confirmed that the error notification is shown to the user when an error occurs during preferences saving.
How to embed: …
=> Add error notification for preferences saving

db/migrate/20230809002819_drop_languages_users.rb, db/schema.rb
Deleted `languages_users` table from db because I suspect `user_languages` is used instead.
Adding a language to a user only makes a row in the latter table
Do not merge until we can confirm the prod version of `languages_users` has no rows
=> Delete unused languages_users table from db

.github/ISSUE_TEMPLATE/flaky_test.md
Both the options run rspec. People might get confused
=> make environment options more clear

app/views/supervisor_mailer/_active_volunteer_info.html.erb, lib/tasks/deployment/20211023145114_store_deploy_time.rake, lib/tasks/test_checker.rake
References #5037
The test suite is currently outputting a lot of noise relating to some deprecation warnings and changed autoloading behavior. I have addressed the 2 main culprits:
- In the `_active_volunteer_info.html.erb` partial, there was a call to a deprecated method from ActiveSupport that allowed passing an argument to the `to_s` method on various objects. In the Rails 7 release this method was moved to `to_fs` and the overridden `to_s` method was deprecated.
- In the `test_checker.rake` task there were 2 constants defined at the top level of the task. Due to the way the autoloader works, these were causing a ton of warnings due to this file being autoloaded and redefining the constant (rake files aren't namespaced in a traditional way so technically that constant is available more …
=> Fix test suite warnings

app/javascript/src/add_additional_expense.js
- moved click listener from entire document to just the add additional expense button
- replaced 3 DOM lookups and a for loop with just one DOM lookup
Just a refactor. Tests exist
=> add_additional_expense.js improvements

app/javascript/src/add_to_calendar_button.js
- for loop easier to spot
- removed if statement with always false conditional
=> remove if false, make for loop more readable

app/views/layouts/_sidebar.html.erb
Resolves #5152
Removed the inbox from the sidebar.
- Supervisor permissions: No
Not required.
=> Remove Inbox from Sidebar

app/views/case_contacts/_confirm_note_content_dialog.html.erb
Resolves #5153
Update the modal close button according to Bootstrap 5.3
- Supervisor permissions: No
Doesn't apply.
https://github.com/rubyforgood/casa/assets/51321005/b840e029-36c9-48b3-84d4-a7431d935926
=> Update modal close btn according to latest Bootstrap

README.md, flake.lock, flake.nix, gemset.nix
This PR is not dependent on any particular issue.
It seems there is a lot of "work" to get casa up and running.  Especially for new users. I decided to make a nix flake that will allow people to begin development quickly. You don't need to worry about installing or configuring rvm, yarn, postgresql, nodejs or even ruby. Just run this file and all the dependencies will be available in an environment separate from your host system. 
I ran this on macOS (Intel) and Linux
=> Add nix flake

app/views/emancipations/show.html.erb
None
Fixed wonky emancipation checklist download button positioning
manual testing
Before:
After:
What gif best describes your feeling working on this issue? 
=> fix emancipation download btn positioning

db/seeds/db_populator.rb
Resolves #5244 
The seed data for mileage rates had their effective dates in the future, with this fix they will be in the past
- Volunteer permissions: Not effected
- Supervisor permissions: Not effected
- Admin permissions: Not effected
You can try this command in the dev or testing environment rails console after running db:seed and check whether the dates are in the past
`MileageRate.pluck(:effective_date)`
Before change
After change
=> created past mileage data for test data

app/views/layouts/_sidebar.html.erb
Resolves #5249 
Relocated the banners as asked in the issue ;D
- Admin permissions: Relocates an item in menu
=> Relocate banners position on navbar

app/assets/stylesheets/pages/case_contacts.scss, app/javascript/src/case_contact.js, app/views/case_contacts/_form.html.erb
Resolves #5285
The `+ Highlight' button was removed from the "New Case Contact" Form. Related JavaScript and CSS files were modified to reflect the change.
- Volunteer permissions: not affected
- Supervisor permissions: not affected
- Admin permissions: not affected
Navigated to page and confirmed that the button was removed.
Re-ran test suite locally to ensure existing tests still pass.
=> Remove “+ Highlight” button from New Case Contact form

app/assets/stylesheets/shared/notifier.scss
- fixed parts of the notifier taking up too much space
Manually
Before
After
=> reduce space taken up by notifier

app/views/casa_cases/_form.html.erb
Resolves #5312 
Instead of being hidden the youth's birth month/year field are disabled on the form for users who can't edit it. @bcastillo32 confirmed with stakeholders this is what they wanted.
How to embed:
=> Allow supervisors to see youths birth month/date in form

.github/workflows/rake-after_party.yml
A rake upgrade pr is unable to get the "rake after_party" CI check to pass because it uses the wrong version of rake
Tested by CI
=> rake CI check uses project's version of rake

.bundle_copy/config, Gemfile.lock, README.md, flake.nix, gemset.nix
Resolves #5341 
- Update README instructions on how to setup a Nix environment for the project
- Fix the `flake.nix` file to handle a proper environment creation and overriding platform-specific gems installation
- Add the auto-stop database server functionality when exiting the environment
- Created environment is fully self-contained, which means that all gems and dependencies are sourced by the Nix store
- Added the ruby platform on `Gemfile.lock` to include non-platform-specific gems
No tests were created since only files related to the Nix environment creation were modified
Passed all project tests, checking that not previous functionality was lost
Environment properly built and server running after `nix develop`:
All gems and dependencies being sourced by Nix store:
=> Nix environment deployment with built-in gems installation

spec/support/capybara.rb
Resolves #5124
Modified options for Chrome driver used in Docker by adding `--disable-dev-shm-usage` flag.
System tests were massively failing during some runs in a Docker environment. [Chrome documentation](https://developer.chrome.com/docs/puppeteer/troubleshooting/#tips) mentions that memory allocated by Docker is usually too small and can cause Chrome to crash.
Ran `docker-compose exec web rspec spec` until I identified a seed that replicated the mass test failure.
Implemented the fix and re-ran tests with the same seed to check that tests now pass.
n/a
=> Modify options for Chrome driver in Docker

app/views/case_contacts/new.html.erb
Resolves #5324
- This PR updates the header for the Case Contacts Header Page to "Record new case contact"
=> Update Case Contact Page Header

lib/mailers/previews/fund_request_mailer_preview.rb
Resolves #5344 
Added missing preview for FundRequest mail.
Manually test by running http://localhost:3000/rails/mailers
**Mail Preview**
**Fund Request Mailer**
=> Add Previews for the Fund Request Mailer

app/javascript/src/case_contact_autosave.js
Some inputs contain values set by the backend. The user is not normally able to modify those values like in the case of input type=hidden. I have removed the ability for the case contact autosave to override the values for inputs like these.
Inputs ignored for value override include: 
- checkbox
- hidden
- image(like a submit)
- radio
- reset(a button that clears the form)
- submit
Manually for now. The plan is to later convert the case contact autosaver into a class so it can be unit tested
autosave data in localstorage: 
Notice the row with id `case_contact_casa_case_id_1` and value `8`
Without the fix. The value of the checkbox has been changed to 8 from localstorage
After the fix. The true value is preserved.
=> fix autosave overriding values on inputs where the value shouldn't be changed

app/views/case_contacts/_form.html.erb
Resolves a bug for multiple users logged in on the same computer where the autosave functionality of the case contact form could make it look like cases were checked when they really were not.
[Loom](https://www.loom.com/share/bb8c1b91851a420593f5133cbc87f68e?sid=ec011541-ea72-432d-bb60-894d06ccae37)
It will reduce the number of identical keys in the case contact autosave hash so autosave data will have a reduced chance of populating parts of a case contact form where the autosave data did not originate from. i.e. when another user logs in to use the case contact form
=> Case Contact Case ID Fix

README.md, doc/NIX_SETUP.md, doc/WSL_SETUP.md
The nix setup instructions were under the general setup instructions section which confused new contributors into thinking nix was a required step in setting up the project.
- The nix setup instructions have been moved to its own platform installation README
- Also moved all of the WSL setup instructions into the platform specific install file.
=> Remove nix installation from general setup instructions

app/javascript/src/case_contact_autosave.js
Fixed an uncaught exception caused by a null reference
=> make uncaught exception impossible

package.json, yarn.lock
Resolves #5337 
Bumped datatables.net-dt to version 1.13.8 instead of 1.13.7
Version 1.13.7 was not uploading the datatables objects properly
Comparison between dependencies versions from failed to merge previous request and actual request
=> build: datatables.net-dt to 1.13.8

app/views/volunteers/_manage_cases.erb
Resolves #5378
The assignment status color was update to a visible color.
- Volunteer permissions: not affected
- Supervisor permissions: not affected
- Admin permissions: not affected
Navigate to volunters/id/edit and go to manage cases now the active and unassigned status will be black.
=> update text color status on volunteers edit page

app/javascript/src/display_app_metric.js, app/views/health/index.html.erb
- Formatting graph data is faster
- All hours and days are visible
- Titled the graph, removed chart labels from below the chart and in the legend.
- Removed the legend because there's only one dataset and clicking it disabled the only dataset
- Errors are shown to the user via the notifier component
Manually
Old: 
New:
=> Fine tuning for metric chart

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/flaky_test.md, .github/ISSUE_TEMPLATE/problem_validation.md, README.md, doc/CONTRIBUTING.md
None.
- The Slack links expired.
- Links were update to match the invite link present on the website: https://rubyforgood.org/join-us
- @mattzollinhofer updated this last month on [this commit](https://github.com/rubyforgood/casa/commit/3be583491380ccfea46440171151b03460efd2f7)
- Click the link in the an incognito / private browsing window if you're already a member of Slack.
Before:
=> Update Slack expired links

app/mailers/fund_request_mailer.rb, lib/mailers/previews/fund_request_mailer_preview.rb
Resolves #5396 
Added the extra parameter `bugsnag_active` to `FundRequestMailer` to confirm the Bugsnag notifications will be active.
Set the parameter default value to `true`, in order to change only the calls that are triggering the exception to be overridden.
Set FundRequestMailerPreview call of `FundRequestMailer` to `false`.
=> Email preview uncaught exception

config/initializers/rswag_api.rb, config/initializers/rswag_ui.rb, spec/swagger_helper.rb
[Resolves #5467](https://github.com/rubyforgood/casa/issues/5467)
Update Rswag gem syntax, swapping out instances of `swagger_*` with `openapi_*`, due to below warning message when resetting the database:
`DEPRECATION WARNING: swagger_root= is deprecated and will be removed from rswag-api 3.0 (use openapi_root= instead) (called from block in <top (required)> at .../casa/config/initializers/rswag_api.rb:6)`
N/A
RSpec passed for `spec/requests/api/v1/users/sessions_spec.rb` and `spec/swagger_helper.rb`.
_I'm still a beginner in open source PR and junior with Rails, so apologies if it's wildly incorrect!_
=> Update Rswag initializers

.github/workflows/rspec.yml
It is confusing for people why CI is not
running when making documentation changes.
=> Remove restrictions for running CI on PRs

app/models/learning_hour.rb, app/policies/learning_hour_policy.rb, app/views/learning_hours/_supervisor_admin_learning_hours.html.erb, app/views/learning_hours/index.html.erb, db/schema.rb
Resolves #5474
when a supervisor or admin clicks on a volunteer on the learning hours features it will route to the volunteer's learning page
log in as a supervisor or as an admin, click on the learning hours feature on the side, then click on a volunteer
How to embed:
=> volunteer's learning hours page

lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake
https://dashboard.heroku.com/apps/casa-production/activity/releases/249
=> make rake task not error in prod

lib/tasks/data_post_processors/case_contact_populator.rb, lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake
Resolves #5501 
There are some additional expenses in the database that would no longer be considered valid. The update of the older Case Contacts is causing the validation on these to fail. This is reproducible given the following steps:
1. Reseed your database: `rails db:seed:replant`
2. In `app/models/additional_expense.rb` comment out the validation line
3. Make a new soon-to-be-invalid Additional Expense in the console: `CaseContact.first.additional_expenses.create!`
4. Set the specified CaseContact as a draft: `CaseContact.first.update(status: "started")`
5. Uncomment the validation line from step 2
6. Comment out the fix in this pull request from `lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake` (lines 7-9)
7. Run AfterParty: `bundle exec rake after_party:run`. …
=> 5501 Bug in Case Contacts AfterParty task

app/controllers/case_contacts_controller.rb, app/controllers/court_dates_controller.rb
Resolves #5502 
- In `CaseContactsController`, removed the `update` action (which isn't defined) from the `only` list for one of the callbacks
- In `CourtDatesController`, removed the `generate` action (which isn't defined) from the `only` list for one of the callbacks
In Rails 7.1, they've added a new configuration to catch typo'd and undefined controller actions listed in the `only` or `except` lists to a controller filter. [Relevant PR](https://github.com/rails/rails/pull/43487).
This configuration option is written by default in `config/environments/test.rb` and `config/environments/development.rb`. In the upgrade to Rails 7.1 in #5478, this configuration was disabled in order to pass the tests. By re-enabling it, we were able to catch a couple of places where unused actions were …
=> Remove unused actions in controller filters

config/initializers/bugsnag.rb
Without an API key bugsnag displays the following warning: 
```sh
Not delivering sessions due to an invalid api_key
```
It is something that new people often get worried about and is very annoying when using irb for debugging. This PR sends that warning to `dev/null` if an API key is not provided.
Solution take from [here](https://github.com/chaskiq/chaskiq/issues/251#issuecomment-1813804184)
=> Fixes bugsnag console message

app/mailers/supervisor_mailer.rb
Resolves #5597 
- New where the condition is added in in the `SupervisorMailer#weekly_digest` in order to get the volunteer of same organization only
How to embed:
=> WIP: [Fix] Weekly supervisor email bottom section includes unknown names - probably volunteers from other orgs

app/controllers/application_controller.rb, app/views/case_contacts/form/expenses.html.erb
https://rubyforgood.slack.com/archives/G01143RQ7DG/p1714155460842599
How to embed:
=> Case Contact Form Bug

app/controllers/case_contacts/form_controller.rb
fix prod more
https://app.bugsnag.com/ruby-for-good/casa/errors/6637007c6857010008cfc9dd?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production&filters[error.status]=new
=> wrap it in a rescue

.github/workflows/ci.yml, .github/workflows/combine_and_report.yml, .github/workflows/rspec.yml
Dependabot does not get passed secrets. Just don't run the actions that require secrets if they aren't passed in.
=> fix: dependabot failures due to no secrets

app/components/form/hour_minute_duration_component.html.erb, app/views/case_contacts/form/details.html.erb
Resolves #5348 
Updated text content to match updated design spec in figma file. Also updated contact duration input fields.
Tested by existing specs.
**Desktop**
**Mobile**
Our work currently differs from the figma in a couple of ways. Here's ours:
And here's what's in the figma
For the first difference, changing `Text/Email` isn't so straightforward because it relies on these [string values](https://github.com/rubyforgood/casa/blob/main/app/models/case_contact.rb#L157-L162) that are saved to the database. Changing this input value introduces a conflict between the form and the underlying data. Any preference for how to proceed on this?
For the second difference, introducing text content that directly trails the numeric input value is tricky to do and is less accessible than just having …
=> Restyle Enter Contact Details form on case contact form

.github/workflows/ci.yml, .github/workflows/rspec.yml, .github/workflows/rspec_parallel.yml
RSpec parallel is still too flaky. Bring back old pipeline until the new one is ready.
This is one option. If there is not enough CI budget for all the runners I will open a PR to disable the parallel ones completely until they are more ready.
=> fix: restore old rspec in CI

app/models/casa_org.rb, config/initializers/bugsnag.rb
Last deploy failed due to
```console
URI::InvalidURIError: bad URI(is not URI?): "https://api.twilio.com/2010-04-01/Accounts/{\"p\":\"\",\"h\":{\"iv\":\"WCWQJURMuJ7Cy1y4\",\"at\":\"GSwNz4L/qh0FMCOAHc2rxQ==\"}}/Messages.json" (URI::InvalidURIError)
```
https://app.bugsnag.com/ruby-for-good/casa/errors/664d4d0b29d5440008cf42d8?filters%5Bevent.unhandled%5D=true&filters%5Bevent.since%5D=30d&filters%5Bapp.release_stage%5D=production
This PR add some logging for that error so we can figure out what the issue is.
=> fix: add logging for URI error in afterparty

app/models/learning_hour.rb, db/migrate/20240523101303_fix_local_discrepencies.rb, db/schema.rb
N/A
This should fix the issue with local setups having bad schema listings. I verified these changes are already in prod and just need to be added to `schema.rb`.
I initially made this with a migration that looked like this, and then emptied the migration file.
I ran the following commands after the commit and got no additional changes:
```
bin/rails db:migrate
bin/rails db:reset
bin/update
bin/setup
```
How to embed:_
=> Fixes local database discrepencies

.github/workflows/docker.yml, .github/workflows/rspec.yml, .github/workflows/rspec_parallel.yml
Maybe this will reduce memory consumption? (Is memory consumption even the issue?)
`rails assets:precompile` does the equivalent of `yarn:build` + `yarn:build:css` + compiles other assets to serve statically
=> feat: precompile assets in CI

app/views/layouts/_sidebar.html.erb
Resolves #5599
Un nested "generate court reports" from group action and got rid of group actions for Volunteers only.
For Volunteer
For Supervisor
How to embed:_
=> FIx: un nest generate court report for volunteers only

.github/workflows/rspec_parallel.yml
It seems like a lot of the timeouts are happening after the tests finish but when simplecov is outputting the coverage reports.
Lets try disabling simplecov and seeing what happens.
=> feat: disable simplecov in parallel ci

Gemfile.lock, app/assets/stylesheets/pages/volunteers.scss, app/views/volunteers/index.html.erb
Resolves rubyforgood#5761
The button no longer moves the page down by becoming invisible instead of being removed. Additionally, the checkboxes now have a darker background color for better contrast.
No changes in tests since it's UI only.
_What gif best …
=> Fix 'Manage Volunteers' Styling on /volunteers page rubyforgood#5761

.devcontainer/.env.codespaces, .devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/post-create.sh, config/environments/development.rb
Most of dev container code sourced from HE
https://github.com/rubyforgood/human-essentials/tree/main/.devcontainer
and Rails 7.2.beta
https://github.com/rails/rails/tree/main/.devcontainer
Needed to add values from rails/rails with otherwise the node version was very out of date
Had to disable CSRF in dev (pretty yikes). Otherwise logins from whatever-github.app.dev would not work.
=> feat: add devcontainers

app/controllers/notifications_controller.rb
A recent PR removed the authorization step at the `/notifications` page, this resulted in issues where unauthorized requests would hit the index page but they don't have the required values to actually show the page.
```plaintext
NoMethodError · undefined method `notifications' for nil:NilClass @notifications = current_user.notifications.includes([:event]).newest_first ^^^^^^^^^^^^^^
app/controllers/notifications_controller.rb:7 index
def index
@deploy_time = Health.instance.latest_deploy_time
@notifications = current_user.notifications.includes([:event]).newest_first
@patch_notes = PatchNote.notes_available_for_user(current_user)
end
```
=> fix: qa notification bugs

.github/workflows/rspec.yml
We occasionally have timeouts with our RSpec Github Action. Lets save the planet a little and cancel it if it goes too long (20 mins)
=> feat: add timeout and concurrency limit to rspec GH action

app/views/reports/_filter.html.erb
Resolves #5795
changed the button type to 'button'. It was defaulted to 'submit' and making the form submit when pressed on it
=> 5795- Modal closing  error in export filter fixed

db/seeds/db_populator.rb
The seeder for case contacts does not set `draft_case_ids` resulting in seeded case contacts not showing up on the case contacts index page. This is a fix for that to match the factory.
=> fix: add draft ids to seeded case contacts

app/controllers/case_contacts_controller.rb, app/models/case_contact.rb, app/presenters/case_contact_presenter.rb, app/views/casa_cases/show.html.erb
`CaseContactsController#index` was our worst page according to scout.
This was mainly because we had 2 N+1 queries:
Those have been fixed.
=> fix: n+1 issues in case_contacts#index

config/database.yml
Better response time lower throughput.
See https://edgeguides.rubyonrails.org/7_2_release_notes.html#set-a-new-default-for-the-puma-thread-count
=> feat: change Puma thread count from 5 to 3

app/views/case_contacts/index.html.erb
Resolves #5864 
The Filter Modal was not closing even when clicked on button to hide. The problem there was a syntax error and also a validation which resulted true always. these events were led to this error.
And also from user perspective , Once the user clicks on  Filter button  inside the modal  after reloading the page with new results the filter modal should be closed as size of it is huge (it occupies total view port) and  makes the user to scrollnup
to see what the  results are after applying filters. if he is not satisfied he need to scroll up again and vary the filter inputs. If the filter closes on default on page load, user can see the results right on top of page without scrolling up and can vary filter inputs by opening modal by just clicking on Show / Hide button if he …
=> 5864- Fixing the Double click error

config/routes.rb
The controller action does not exist but there is a route to it.
=> fix: remove case_contact show route

db/seeds.rb, db/seeds/db_populator.rb
Resolves [5844](https://github.com/rubyforgood/casa/issues/5844)
- `@create_other_duties_counter` attr. `initialized` equal to `0`
- a private method, `create_other_duties `was created; iterates through each `Volunteer object `and creates `2` `OtherDuty `instances per volunteer
- each time `other_duty` is created it, is `incremented onto the counter` `(+= 1)`
- `prints how many other duties have been created` by string interpolating the final counter 
Issue does not require tests;
Tested locally in Rails Console using Volunteer and OtherDuty objects + Faker for dummy data.
From the console:
=> Issue 5844: Seeder other duties

app/views/volunteers/_send_reminder_button.html.erb
Resolves #5729 
I changed the div classes to correct the alignment and make sure the checkbox is next to the checkbox label.
There are already tests for the functionality in `spec/system/volunteers/edit_spec.rb:470-517`
=> change div classes to fix checkbox location

app/controllers/supervisor_volunteers_controller.rb
If an admin attempts to unassign a supervisor when they have already been unassigned it returns a 500 error. This way it will just return a flash message about an issue.
=> fix: prevent 500 if attempting to unassign supervisor twice

app/views/users/edit.html.erb
Resolves #5178
The edit user page has an alert that displays the shared error messages template. This seemed to have double wrapped the alert in the `alert-box` and `danger_alert` classes.
There was a couple ways to achieve a fix here. One was to edit the shared errors messages page but that would have had implications in the other 36 references
It appears since the styles were double wrapped we can just remove the top level on the edit page thus only affecting that page in this change while also adding the desired padding
Achieving the request of the ticket of
> Make the error shown below the width of the parent container with some margin.
This was tested using the browser to replicate different widths. I wasn't aware of any actual unit or e2e tests that would cover this type of style …
=> Fix: Expand width of errors alert on edit user page

README.md
Resolves #5962 
Updated "our google calendar" link from relative to absolute url
Click "our google calendar" link in README
=> fix: google calendar link in README

Dockerfile
Moved all yarn actions to the second stage of the build. Bundle takes the most time and having anything run synchronously with bundle takes longer.
```
Benchmarks
(current)
casa-web                           latest    c611b7f38df0   9 hours ago   696MB
selenium/standalone-chrome-debug   latest    aaf43463c572   2 years ago   1.11GB
postgres                           12.5      5fa7773911d6   3 years ago   314MB
real	4m16.865s
user	0m8.035s
sys	0m4.681s
Github: [8m53s, 11m 17s] 5 runs
(Balanced Multi-stage Build)
casa-web                           latest    ff9941b85870   About a minute ago   732MB
selenium/standalone-chrome-debug   latest    aaf43463c572   2 years ago          1.11GB
postgres                           12.5      5fa7773911d6   3 years ago          314MB
real	3m18.398s
user …
```
=> Speed up docker multi stage balance

config/environments/test.rb, spec/rails_helper.rb
No Issue, concerns local development only.
Prior to change, running `bin/rspec` locally would produce following error in my (mac) environment:
```sh
lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:105:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
```
(Note I did not do what the above error says to do, that was the 'old' way to do it before Rails 7.1, I guess rspec hasn't updated the error?)
So, the only way to run a specific spec or file was to use focus tag (`fit`, `fdescribe`, etc...) while running `bin/rails spec`, which runs javascript/css builds each run - annoying if running backed / not changing javascript/css.  The focus tag could also …
=> Local-friendly RSpec setup

Gemfile, Gemfile.lock, app/javascript/application.js, app/views/case_contacts/_case_contact.html.erb, app/views/case_contacts/_followup.html.erb, app/views/case_contacts/index.html.erb, app/views/layouts/application.html.erb, app/views/layouts/devise.html.erb, package.json, yarn.lock
Resolves #5906 but with stipulations
- Adds turbo-rails gem
- Removes turbolinks package (does not look like it was being used anyway)
- Adds a turbo frame on the case_contacts/index view to prevent full page reloads when filtering and demonstrate turbo is working
- Disables Turbo Drive from applying globally by default
- Also does not bring redis in, which `turbo:install` does by default. This means turbo streams will not work unless we wire up an alternative to redis, but turbo frames and turbo drive should work fine without it. I left a note in the Gemfile calling attention to this incase anyone tries to add a stream and thinks this was a mistake.
I think this covers the criteria of the issue while making the most minimum changes.
It may be desired to not have Turbo Drive disabled …
=> 5906 add turbo with disabled turbo drive

app/views/supervisors/index.html.erb
Resolves #6025 
Added a table name to the table that shows active volunteers without supervisors. The title is `Volunteers without Supervisors`. Changed the styling of this table to match the other tables in the supervisors page.
=> Added table name and styling to volunteers without supervisors table

app/models/case_contact.rb
Addresses #5860 
Addresses (temporarily?) issue where validation failed when user selected current day in browser. 
Date could now be wrong (tomorrow) for those situations, however. Also changes Date.tomorrow to Time.zone.tomorrow to possibly to mitigate that.
Current tests only.  Cannot find a decent solution for setting capybara browser driver timezones to tests the difference between browser and server. Possibly could add request spec sending date as browser would send... but unsure how to account for TimeZone differences there?
=> Add extra day to case contact date validation

app/helpers/ui_helper.rb, app/models/volunteer.rb
Resolves #5894
When editing a Volunteer, an N+1 query occurred.
After the changes, it doesn't happen an the code is faster.
N+1 queries are tested with Bullet gem, a message is shown in the console
Previous queries
Actual queries
=> [5894] Fix VolunteersController#edit N+1 issues

Dockerfile, README.md
Added comment for strange install so maybe it can be removed in the future
=> Add comment about why install is different from the others

.github/workflows/toc.yml
n/a
The TOC Generator step in GitHub actions sometimes tries to run against branches that no longer exist and fails. This config update should have it only check/run against the main branch.
This update also has the TOC Generator create a PR for readme changes instead of pushing them directly.
Need to see how this runs in GitHub actions.
😀 😀 
First time collaborating with @FireLemons! 🎉
=> Update GH Workflow TOC Generator

bin/git_hooks/lint
`Calling `erblint` is deprecated, please call the renamed executable `erb_lint` instead.`
=> Fix erblint deprecation warning

app/views/layouts/devise.html.erb
Previously, network tools show a 404 getting /users/assets/images/favicon.svg on /users/sign_in, and some tests intermittently failed with this 404. Delete the extraneous favicon link from devise boilerplate to let the normal favicon work on the login screen.
Fixes test flake at
https://github.com/rubyforgood/casa/wiki/Flaky-tests#suspected-testing-tool-crash
Resolves [flaky test at ](https://github.com/rubyforgood/casa/wiki/Flaky-tests#suspected-testing-tool-crash). The test reports sometimes failing with `No route matches [GET] "/users/assets/images/favicon.svg"`.
The devise-generated view at `app/views/layouts/devise.html.erb` had its own favicon, which would make 404s on the page, and these 404s would fail some tests. Deleting this link tag lets the normal favicon present on other …
=> fix: delete boilerplate favicon on login page

.github/dependabot.yml, Dockerfile, docker-compose.yml
=> trying to fix docker build

Procfile.dev
N/A
After the PR to migrate from `yarn` to `npm` [was merged](https://github.com/rubyforgood/casa/commit/4356348b7a8745f1d2fc6fb78b1991d416393911), I noticed that running `bin/dev` locally no longer seemed to start the dev server for me and exited immediately. Also saw that a CI check started failing, and it seemed related.
I changed the scripts in `Procfile.dev` to make use of the `dev` versions for building js and css and this seemed to fix the issue. Still not entirely sure why the switch from `yarn` to `npm` mattered here. This is a bit out of my wheelhouse, so not sure if I missed anything important. Please let me know if anything seems off!
_Note: We …
=> updates Procfile.dev to use dev js and css build scripts

app/controllers/volunteers_controller.rb
Resolves #NaN
Noticed an error with `volunteers#create` through the discord. 
Likely due to an invalid or non standard email.
I refactored it to ensure in the volunteers_controller `create` function....
- Invitations to Invalid emails throw an alert
=> Attempt to address volunteer#create invalid email error in bot-bugsag

app/controllers/api/v1/users/sessions_controller.rb, app/controllers/volunteers_controller.rb
Resolves #XXXX
Removed comments that described the code under them to DRY up code.
The code under the comments was readable to begin with.
\- @FireLemons 
How to embed:_
`![alt …
=> Suggested comment removal

app/controllers/api/v1/users/sessions_controller.rb
Reverts rubyforgood/casa#6254 because it was merged to trigger CI and did not include the changes detailed in the PR
=> Revert "Suggested comment removal"

app/models/emancipation_option.rb, app/models/user_language.rb, db/migrate/20250331032424_validate_constraint_mileage_rates.rb, db/migrate/20250331033339_validate_constraint_notes.rb, db/migrate/20250331033350_validate_constraint_placements.rb, db/migrate/20250331033418_remove_duplicate_indexindex_emancipation_options_on_emancipation_category_id.rb, db/migrate/20250331033441_remove_duplicate_indexindex_user_languages_on_language_id.rb, db/schema.rb
Resolves https://github.com/rubyforgood/casa/issues/6288
=> [#6288] Fix pg hero issues

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/flaky_test.md, .github/ISSUE_TEMPLATE/problem_validation.md, README.md, doc/CONTRIBUTING.md
=> Replace expired slack invite link with a link that will expire on June 6, 2025 because its the best we got

app/models/custom_org_link.rb, db/migrate/20250528092341_trim_whitespace_from_custom_org_links.rb, db/schema.rb
Resolves #6404 
- Added a `before_save` callback in `CustomOrgLink` to trim whitespace from the `text` field before saving.
- Added a migration to trim whitespace from existing `CustomOrgLink` records (please review if this is desired). Used `up`/`down` methods since this is a data migration and not reversible. Tested locally to confirm it works.
=> Fix #6404: Trim whitespace from custom link text before saving

config/scout_apm.yml
We are excited to announce that Scout's Error Monitoring is now in Beta! Easily find errors by type and by endpoint all in one place. 
To enable error reporting please use either of these two methods:
1. In your config/scout_apm.yml set `errors_enabled: true` 
2. Or you can set the environment variable SCOUT_ERRORS_ENABLED=true
Once you have deployed, you will see the Errors tab on the homepage.
You can expect
10,000 monthly errors on our free tier.
Transparent pricing: $15/month for 100k errors, $5 for each additional 50k
30-day data retention 
Correlate logs, traces, and errors
Please send us feedback!
We would love to hear about your experience to help us make this feature as valuable as possible.
=> Enable Scout error monitoring in production config
